// PIECESPLAY (navigator 2026-10-06: "the piece's own lead, play minor as it is"): stage 3's ten pieces are exported one
// module a piece and fetched only when THE DJ deals one; they join each family's deck beside one live-settle card
// (THE DECK RULE); a dealt piece plays from the first bar line after it arrives, the set before playing on meanwhile;
// while it plays the lead is the piece's own lead and the root, mode and chord are the piece's, with no shift and no
// key lift; a replay of a piece's tag fetches the piece and plays it; the layers play the lead on its sixteenths.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import { Ctx } from './fakeaudio.mjs';
import { createHouseDJ, SETTLE_CARD, PIECE_WAIT_BARS, PIECE_ONLY_FAMILIES } from '../src/mix-dj.js';
import { isPiece, leadOfBar, notesOfBar, pieceRoot, pieceMode, chordOfBar, pieceToSet } from '../src/dj-trained-notes.js';
import { loadPieceIndex, loadPiece, pieceLoads, resetPieceLoads } from '../src/dj-pieces.js';
import { createMixSet } from '../src/mix-layers.js';
import { encodeTag, decodeTag, situationOf } from '../src/dj-tag.js';
import { THEME_FAMILY } from '../src/dj-trained-plan.js';
import { midiHz } from '../src/tuning.js';
import { configure, unlockNow } from '../src/index.js';
import models from '../src/dj-trained-models.js';
import INDEX from '../src/dj-pieces-index.js';

const tick = () => new Promise((r) => setImmediate(r));

// a small hand-made minor piece (A minor), whole, for the tests that need exact notes
function minorPiece(id = 'test-minor', family = 'house', kick = [1, 1]) {
  const roles = models.roles;
  const blocks = kick.length;
  const bars = 8 * blocks;
  const drums = [];
  for (let b = 0; b < bars; b++) for (const i of [0, 4, 8, 12]) drums.push([16 * b + i, 1, 36, 110]);
  return {
    format: 'djnotes-piece/v1', id, name: 'Test minor', family, bpm: 124, steps_per_bar: 16, bars, swing: 0,
    key: { tonic: 9, tonic_name: 'A', mode: 'minor' }, roles, grid: roles.map((r) => (r === 'kick' ? kick.slice() : kick.map(() => 1))), gates: kick.map((_, t) => (t ? 1 : 0)), arc: kick.map(() => 0.3),
    events_order: models.events, events: models.events.map(() => '.'.repeat(bars)),
    chords: Array.from({ length: bars }, (_, b) => (b % 2 ? 11 : 1)), chord_names: Array.from({ length: bars }, (_, b) => (b % 2 ? 'Fm' : 'Am')),
    tracks: [
      { name: 'drums', channel: 9, program: 0, notes: drums },
      { name: 'bass', channel: 0, program: 38, notes: [[0, 4, 45, 100]] },
      { name: 'lead', channel: 3, program: 81, notes: Array.from({ length: bars }, (_, b) => [16 * b + 2, 3, 69 + (b % 3), 96 + b]) },
    ],
  };
}

test('THE EXPORT: one module a piece, the cards name every module with its size, and the fence rides with each piece', async () => {
  assert.equal(INDEX.format, 'dj-pieces/v1');
  assert.equal(INDEX.pieces.length, 10, 'stage 3 wrote ten pieces');
  assert.equal(INDEX.fence.hitsFirst, 1814, 'the note fence caught 1,814 phrases on the first settle');
  assert.equal(INDEX.fence.writtenHitsFinal, 0, 'and none is left in the written pieces');
  const families = new Set();
  for (const c of INDEX.pieces) {
    const file = new URL(`../src/pieces/${c.id}.js`, import.meta.url);
    assert.equal(statSync(file).size, c.bytes, `${c.id}: the card's size is the module's size`);
    const p = (await import(file.href)).default;
    assert.ok(isPiece(p), `${c.id} is a djnotes-piece/v1`);
    assert.equal(p.family, c.family);
    assert.equal(p.fence.writtenHitsFinal, 0, `${c.id}: no fence hit left in the written piece`);
    assert.ok(p.fence.hitsFirst > 0, `${c.id}: its first-settle hits ride with it`);
    families.add(c.family);
  }
  assert.ok(Math.min(...INDEX.pieces.map((c) => c.bytes)) > 30000 && Math.max(...INDEX.pieces.map((c) => c.bytes)) < 300000);
  // every piece is reachable from some theme's deck: a live family, or a piece-only family placed on a theme
  const reach = new Set([...Object.values(THEME_FAMILY).flat(), ...Object.values(PIECE_ONLY_FAMILIES).flat()]);
  for (const f of families) assert.ok(reach.has(f), `the ${f} piece can be dealt`);
  // the exporter is the only writer: its --check would refuse a hand-edited module (run by python, not here)
  assert.match(readFileSync(new URL('../src/dj-pieces-index.js', import.meta.url), 'utf8'), /GENERATED by SETTLE\/gridlearn\/export_pieces\.py/);
});

test('ONE AT A TIME: the loader fetches only the piece asked for, once, and refuses an id that is not a piece', async () => {
  resetPieceLoads();
  const a = await loadPiece('shoreline');
  assert.equal(a.id, 'shoreline');
  await loadPiece('shoreline');
  assert.deepEqual(pieceLoads().map((r) => r.id), ['shoreline'], 'a second deal of the same piece fetches nothing');
  assert.equal(pieceLoads()[0].bytes, INDEX.pieces.find((c) => c.id === 'shoreline').bytes);
  await assert.rejects(loadPiece('../dj-trained-models'), /no stage 3 piece/);
  await assert.rejects(loadPiece('not-a-piece'), /no stage 3 piece/);
  assert.equal(pieceLoads().length, 1, 'a refused id fetches nothing');
  assert.equal((await loadPieceIndex()).pieces.length, 10);
});

test('THE DECK RULE: a family deals each of its pieces once and one live settle once a round', () => {
  const pieces = [minorPiece('test-a', 'house'), minorPiece('test-b', 'house'), minorPiece('test-c', 'trance')];
  const dj = createHouseDJ({ seed: 11, theme: 'highlands', trained: models, pieces });
  const byFamily = { house: [], trance: [] };
  let d = dj.bar({ theme: 'highlands' });
  for (let k = 0; k < 60; k++) {
    if (d.newSet && d.trained) byFamily[d.trained.family]?.push(d.piece?.id ?? SETTLE_CARD);
    dj.nextSet();
    d = dj.bar({ theme: 'highlands' });
  }
  for (const [fam, want] of [['house', ['test-a', 'test-b', SETTLE_CARD]], ['trance', ['test-c', SETTLE_CARD]]]) {
    const seq = byFamily[fam];
    assert.ok(seq.length >= 2 * want.length, `${fam}: enough sets to see two rounds`);
    for (let i = 0; i + want.length <= seq.length; i += want.length) assert.deepEqual(seq.slice(i, i + want.length).sort(), want.slice().sort(), `${fam} round ${i / want.length}`);
  }
});

test('FETCHED WHEN DEALT: nothing up front; the set before plays on until the piece arrives, then it starts on the next bar line', async () => {
  const calls = [];
  const waiters = new Map();
  const load = (id) => { calls.push(id); return new Promise((res) => waiters.set(id, res)); };
  const cards = [{ id: 'test-late', name: 'Test late', family: 'house', key: { tonic: 9, mode: 'minor' } }, { id: 'test-trance', name: 'Test trance', family: 'trance' }];
  let clock = 1000;
  const dj = createHouseDJ({ seed: 4, theme: 'highlands', trained: models, now: () => clock });
  dj.setPieces(cards, { load });
  assert.deepEqual(calls, [], 'no piece is fetched before it is dealt');
  let d = dj.bar({ theme: 'highlands' });
  let guard = 0;
  while (!dj.pendingPiece && guard++ < 12) { dj.nextSet(); d = dj.bar({ theme: 'highlands' }); }
  const want = dj.pendingPiece;
  assert.ok(want, 'a piece card was dealt');
  await tick();
  assert.deepEqual(calls, [want.id], 'only the dealt piece is fetched');
  const before = d.trained?.view ?? null;
  clock += 2000;
  d = dj.bar({ theme: 'highlands' });
  assert.equal(d.piece, null, 'it has not arrived: no piece plays');
  assert.equal(d.newSet, false, 'the set before plays on');
  assert.equal(d.trained?.view ?? null, before);
  waiters.get(want.id)(minorPiece(want.id, cards.find((c) => c.id === want.id).family));
  await tick(); await tick();
  clock += 500;
  d = dj.bar({ theme: 'highlands' });
  assert.equal(d.piece?.id, want.id, 'it plays from the bar after it arrived');
  assert.ok(d.newSet);
  assert.equal(d.piece.start.dealtAt, 1000, 'the first bar carries the deal\'s clock');
  assert.ok(d.piece.start.waitBars >= 1);
});

test('A PIECE THAT DOES NOT ARRIVE: after PIECE_WAIT_BARS bars a live settle plays instead, never silence', () => {
  const dj = createHouseDJ({ seed: 4, theme: 'highlands', trained: models });
  dj.setPieces([{ id: 'test-never', name: 'never', family: 'house' }, { id: 'test-never2', name: 'never', family: 'trance' }], { load: () => new Promise(() => {}) });
  let d = dj.bar({ theme: 'highlands' });
  let guard = 0;
  while (!dj.pendingPiece && guard++ < 12) { dj.nextSet(); d = dj.bar({ theme: 'highlands' }); }
  assert.ok(dj.pendingPiece);
  let started = null;
  for (let b = 0; b < PIECE_WAIT_BARS + 1; b++) { d = dj.bar({ theme: 'highlands' }); if (d.newSet && d.trained) started = d; }
  assert.ok(started, 'a new set began');
  assert.equal(started.piece, null, 'a live settle, not the missing piece');
  assert.equal(dj.pendingPiece, null);
});

test('THE PIECE PLAYS AS WRITTEN: its own lead, its own key and mode (a minor piece under a major theme), its chord, no key lift', () => {
  // two drops (kick back at blocks 2 and 4), so the planner wants a key lift on the second one
  const piece = minorPiece('test-minor', 'house', [1, 0, 1, 0, 1]);
  const dj = createHouseDJ({ seed: 9, theme: 'highlands', trained: models, pieces: [piece] }); // highlands is lydian: a major theme
  let d = dj.bar({ theme: 'highlands' });
  for (let k = 0; k < 8 && !d.piece; k++) { dj.nextSet(); d = dj.bar({ theme: 'highlands' }); }
  assert.equal(d.piece?.id, 'test-minor');
  assert.equal(d.mode, 'aeolian', 'minor stays minor under a major theme');
  assert.equal(((d.root % 12) + 12) % 12, 9, 'the piece\'s tonic, A, is the root: no shift to the theme');
  assert.equal(d.trained.piece.shift, 0);
  assert.equal(d.lead.kind, 'piece');
  assert.equal(d.lead.label, 'Test minor');
  assert.equal(d.piece.keyName, 'A minor');
  assert.equal(d.piece.minor, true);
  const sb = d.plan.setBar;
  assert.deepEqual(d.notes, leadOfBar(notesOfBar(pieceToSet(piece).notes, sb)), 'the lead is the piece\'s own lead of this bar');
  assert.equal(d.piece.chordName, piece.chord_names[sb]);
  assert.deepEqual(d.chord, chordOfBar(pieceToSet(piece), sb, d.root).notes, 'the chord of the bar is the piece\'s');
  // through the whole set: no key lift (where the planner wanted one), no surfacing tune, the lead always the piece's
  let wanted = 0;
  for (let b = 0; b < 39; b++) {
    d = dj.bar({ theme: 'highlands' });
    if (!d.piece) break;
    if (d.plan.keyLift) wanted += 1;
    assert.equal(d.keyLift, 0);
    assert.ok(!d.moves.some((m) => m.key === 'key-lift'));
    assert.equal(d.surfacing, null);
    assert.equal(d.lead.kind, 'piece');
  }
  assert.ok(wanted > 0, 'the planner wanted a key lift on the second drop, so the test can see one refused');
  assert.equal(pieceMode({ mode: 'major' }), 'ionian');
  assert.equal(pieceRoot({ tonic: 2 }, 57), 62);
  assert.equal(pieceRoot({ tonic: 10 }, 57), 58);
});

test('A REPLAY OF A PIECE\'S TAG fetches the piece and plays it from the tag\'s bar once it arrives', async () => {
  const piece = minorPiece('test-replay', 'house');
  const src = createHouseDJ({ seed: 9, theme: 'highlands', trained: models, pieces: [piece] });
  let d = src.bar({ theme: 'highlands' });
  for (let k = 0; k < 8 && !d.piece; k++) { src.nextSet(); d = src.bar({ theme: 'highlands' }); }
  for (let b = 0; b < 3; b++) d = src.bar({ theme: 'highlands' });
  const tag = encodeTag(situationOf({ theme: 'highlands', section: d.section, setBar: d.plan.setBar, set: d.plan.set, layers: d.mix.yes, trained: { family: d.trained.family, seed: d.trained.seed, blocks: d.trained.blocks, piece: { id: d.trained.piece.id, shift: d.trained.piece.shift } } }));
  let calls = 0;
  const other = createHouseDJ({ seed: 70, theme: 'crystals', trained: models });
  other.setPieces([{ id: 'test-replay', name: 'Test minor', family: 'house' }], { load: async () => { calls += 1; return piece; } });
  other.load(decodeTag(tag), null);
  assert.equal(calls, 0, 'the fetch starts on the next tick, not inside load');
  await tick(); await tick();
  assert.equal(calls, 1);
  const r = other.bar({ theme: 'highlands' });
  assert.equal(r.piece?.id, 'test-replay', 'the replay plays the same piece');
  assert.equal(r.plan.setBar, d.plan.setBar, 'from the tag\'s bar');
  assert.deepEqual(r.notes, d.notes, 'the same lead');
});

test('THE LAYERS: a piece\'s lead note sounds on its own sixteenth, at its own pitch class', () => {
  const piece = minorPiece('test-layers', 'house');
  const dj = createHouseDJ({ seed: 9, theme: 'highlands', trained: models, pieces: [piece] });
  let d = dj.bar({ theme: 'highlands' });
  for (let k = 0; k < 8 && !d.piece; k++) { dj.nextSet(); d = dj.bar({ theme: 'highlands' }); }
  while (!d.notes.length) d = dj.bar({ theme: 'highlands' });
  configure({ createContext: () => new Ctx() });
  const E = unlockNow();
  const mix = createMixSet(E.ctx, E.ctx.destination, { seed: 2 });
  const t0 = 4;
  const beatDur = 0.5;
  const seen = [];
  const orig = E.ctx.createOscillator.bind(E.ctx);
  E.ctx.createOscillator = () => { const o = orig(); o.start = (t) => { o.started = true; o.startAt = t; }; seen.push(o); return o; };
  mix.bar(t0, { ...d, mix: { ...d.mix, yes: { ...d.mix.yes, lead: true } } }, beatDur);
  const n = d.notes[0];
  const at = t0 + n.step * beatDur / 4;
  const pcOf = (hz) => ((Math.round(12 * Math.log2(hz / midiHz(69)) + 69) % 12) + 12) % 12;
  const hit = seen.some((o) => Math.abs((o.startAt ?? -1) - at) < 1e-6 && pcOf(o.frequency.value) === n.midi % 12);
  assert.ok(hit, `a lead oscillator starts at ${at} on pitch class ${n.midi % 12}`);
  mix.dispose();
});

test('THE HERO SYMPHONY WITH THE PIECES ON (its default): a dealt piece plays, djLive names it, the tag carries it, and NEXT moves on', async () => {
  const { createSymphony, djLive, nextSet } = await import('../src/index.js');
  const { createBrainStore } = await import('../src/dj-brain.js');
  const { loadTrainedModels } = await import('../src/dj-trained.js');
  configure({ createContext: () => new Ctx() });
  const s = createSymphony({ seed: 8, theme: 'embers', auto: false, house: true, steer: null, votes: null, djBrain: createBrainStore('trained') });
  const E = unlockNow();
  await loadTrainedModels();
  await loadPieceIndex();
  await new Promise((r) => setTimeout(r, 20));
  // the event loop runs between bars, as it does in a page, so a dealt piece can arrive
  const bar = async () => { E.ctx.currentTime += 2; s.tick(); await new Promise((r) => setTimeout(r, 15)); };
  let found = null;
  for (let b = 0; b < 30 && !found; b++) {
    await bar();
    if (s.state.mix?.music?.piece) found = s.state.mix.music.piece;
    else nextSet();
  }
  assert.ok(found, 'a piece was dealt and played within 30 bars');
  const live = djLive.get();
  assert.equal(live.music.piece.id, found.id, 'djLive names the piece');
  assert.ok(live.trained.view.piece?.id === found.id, 'the view is the piece\'s set');
  assert.equal(s.state.mix.lead.kind, 'piece', 'the lead is the piece\'s own');
  const tag = decodeTag(s.state.tag, { pieces: INDEX.pieces });
  assert.equal(tag.trained.piece.id, found.id, 'the tag carries the piece');
  assert.equal(tag.trained.piece.shift, 0, 'played in its own key');
  assert.equal(tag.tune.kind, 'composed', 'the tag\'s tune fields still name the composed tune');
  const set = s.state.mix.set;
  nextSet();
  let moved = -1;
  for (let b = 1; b <= PIECE_WAIT_BARS + 1; b++) { await bar(); if (s.state.mix.set !== set) { moved = b; break; } }
  assert.ok(moved >= 1 && moved <= PIECE_WAIT_BARS + 1, `NEXT moved on after ${moved} bar(s)`);
  s.dispose();
});
