// settle-hear · tunes/athole-b - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Reader athole-b: printed pages 131 to the end of the Athole Collection (wikis/WIKI_OLD_MELODIES/books/BOOK_ATHOLE_B.md).

export const SOURCE = {
  kind: 'print',
  book: 'The Athole Collection of the Dance Music of Scotland',
  compiler: 'James Stewart-Robertson of Edradynate',
  year: 1884,
  scan: 'https://archive.org/details/athole-collection',
};

export const TUNES = [
  {
    id: "athole-p158-tullochgorum",
    title: "Tullochgorum",
    region: "scottish",
    kind: "strathspey",
    key: "G",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey; printed in G major for violin with a piano bass; second strain printed once and closed with a sign directing a return",
    tags: ["strathspey", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Tullochgorum\nM:C\nL:1/8\nK:G\nd/c/ |: B/G3/2d/G3/2 c/=F3/2A3/2c/ | B/G3/2d/G3/2 B3/2c/d/g3/2 |\nB/G3/2d/G3/2 c/=F3/2A3/2c/ | B/G3/2d/G3/2 A/B/c BA :|\nG3/2g/d3/2g/ =f/=F3/2 A2 | G3/2g/d3/2g/ B3/2g/d3/2g/ |\nG3/2g/d3/2g/ =f/=F3/2 A2 | G3/2g/d3/2B/ c2 BA |\nG3/2g/d3/2g/ =f/=F3/2 A2 | G3/2g/d3/2e/ =f/c3/2f3/2g/ |\na/g/f/e/ =fd c/=F3/2A/a3/2 | g3/2d/ g/a/b e3/2g/d3/2g/ |]",
    source: { ...SOURCE, where: "p. 158 (PDF page 170), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 170, each treble staff in thirds at 400 dpi, note heads located against the measured staff lines, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p158-monymusk",
    title: "Monymusk",
    region: "scottish",
    kind: "strathspey",
    key: "G",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey (Daniel Dow's Sir Archibald Grant of Monymusk); printed in G major for violin with a piano bass, second strain with first and second time endings",
    tags: ["strathspey", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Monymusk\nM:C\nL:1/8\nK:G\ne | d/G3/2B3/2G/ d3/2G/c/e3/2 | d/G3/2B3/2G/ (3ABA c3/2e/ |\nd/G3/2B3/2G/ B/d3/2d3/2g/ | e3/2c/A3/2d/ B/G3/2G :|:\nf | g3/2d/B3/2g/ d3/2g/B3/2g/ | g3/2d/B3/2g/ c3/2g/A3/2f/ |\n|1 g3/2d/e3/2g/ d3/2g/B3/2g/ | e3/2c/A3/2d/ B/G3/2G :|\n|2 g3/2d/e3/2g/ d/b3/2c/a3/2 | B/g3/2A/g3/2 B/G3/2G |]",
    source: { ...SOURCE, where: "p. 158 (PDF page 170), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 170, each treble staff in thirds at 400 dpi, note heads located against the measured staff lines, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p164-lord-macdonald",
    title: "Lord Macdonald",
    region: "scottish",
    kind: "reel",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; printed in G major for violin with a piano bass in four strains, the first and third repeated, the second and fourth printed once",
    tags: ["reel", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Lord Macdonald\nM:C|\nL:1/8\nK:G\nB/c/ | d3e dBg2 | dBg2 aAAB | d^cde dBgB | A/B/c BA BGG :|\nB | DGBG AGBG | DGBG AGEA | DGBG AGBG | DEDC B,G,G,G |\nDGBG AGBG | DGBG AGEB | cBAG GFED | EFGA BGG ||\n|: B/c/ | d3e dBg2 | g2fg aAAB | d^cde dBgB | A/B/c BA BGG :|\ng | dgbg agbg | dgbg aeeg | dgbg agbg | ded=c BGGg |\ndgbg agbg | dgbg aeea | bagf gfed | efga bgg |]",
    source: { ...SOURCE, where: "p. 164 (PDF page 176), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 176, each treble staff in thirds at 400 dpi, note heads located against the measured staff lines, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p147-the-white-cockade",
    title: "The White Cockade",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish country dance on the Jacobite song tune; printed among the Country Dances in G major for violin with a piano bass, both strains repeated",
    tags: ["dance", "march", "highlands", "scottish"],
    abc: "X:1\nT:The White Cockade\nM:C|\nL:1/8\nK:G\nGA | B2B2B2AB | G2B2B2ge | d2B2B2AG | B2A2A2GA |\nB2Bd cBAG | A2B2g3a | bagf efge | d2B2B2 :|\n|: Bc | d2B2g2B2 | d2d2d3e | d2B2g2fg | a2A2A2GA |\nB2Bd cBAG | A2B2g3a | bagf efge | d2B2B2 :|",
    source: { ...SOURCE, where: "p. 147 (PDF page 159), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 159, each treble staff in thirds at 400 dpi, note heads located against the measured staff lines, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p146-the-deuks-dang-oer-my-daddie",
    title: "The Deuks Dang o'er my Daddie",
    region: "scottish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Scottish jig on the old song tune (Burns wrote words to it); printed among the Country Dances in D major for violin with a piano bass, both strains repeated",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:The Deuks Dang o'er my Daddie\nM:6/8\nL:1/8\nK:D\nf/e/ | d2A F2D | EFE BAB | d2A F2E | FDD D2 f/e/ |\nd2A F2D | EFE BAB | d2A F2E | FDD D2 :|\n|: A | dcd Bcd | efd cBA | dcd efg | fdd d2 e/f/ |\ngfg Bcd | efd cBA | d2A F2E | FDD D2 :|",
    source: { ...SOURCE, where: "p. 146 (PDF page 158), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 158, each treble staff in halves at 300 dpi and thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 600 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p146-flowers-of-edinburgh",
    title: "Flowers of Edinburgh",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish country dance tune (eighteenth century); printed among the Country Dances in G major for violin with a piano bass, both strains repeated, each strain closing on a short bar before its repeat",
    tags: ["dance", "reel", "highlands", "scottish"],
    abc: "X:1\nT:Flowers of Edinburgh\nM:C|\nL:1/8\nK:G\nGE | D3E G3A | BGdG cBAG | FGFE DEFG | AFdF E3F |\nD3E G3A | BGBd efge | d=cBA GFGA | B2G G2 :|\n|: d | gfga gbag | fdfg fagf | edef gfed | B2e3/2f/ efge |\ndBGB B/=c/d cB | egfa g2fe | d=cBA GFGA | B2G G2 :|",
    source: { ...SOURCE, where: "p. 146 (PDF page 158), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 158, each treble staff in halves at 300 dpi and thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 600 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p147-east-neuk-of-fife",
    title: "East Neuk of Fife",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish country dance tune; printed among the Country Dances in G major for violin with a piano bass, both strains repeated",
    tags: ["dance", "reel", "highlands", "scottish"],
    abc: "X:1\nT:East Neuk of Fife\nM:C|\nL:1/8\nK:G\nD2 | G2G2G2Bc | dBGB dBGB | A2A2A2gf | edef g2fe |\nd=cBA GABc | dBGB d2=cB | ABcd BcAB | G2E2E2 :|\n|: dc | B2G2G2dc | B2G2G2ed | c2A2A2eg | a2A2A2dc |\nB2G2d2G2 | g2G2d2cB | ABcd BcAB | G2E2E2 :|",
    source: { ...SOURCE, where: "p. 147 (PDF page 159), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 159, each treble staff in halves at 300 dpi and thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 600 to 1000 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p147-miss-forbes-farewell-to-banff",
    title: "Miss Forbes' Farewell to Banff",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish tune printed among the Country Dances in G major for violin with a piano bass, both strains repeated",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:Miss Forbes' Farewell to Banff\nM:C|\nL:1/8\nK:G\nGA | B3d cBAG | B2d2 efge | d3e dBAG | B2A2A2GA |\nB2d2 cBAG | B2d2 efge | d3e dBAG | B2G2G2 :|\n|: d | g3a gfed | edef g3b | d3e dBAG | B2A2A2d2 |\ngfga gfed | edef g2fe | d3e dBAG | B2G2G2 :|",
    source: { ...SOURCE, where: "p. 147 (PDF page 159), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 159, each treble staff in halves at 300 dpi and thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p150-petronella",
    title: "Petronella",
    region: "scottish",
    kind: "country-dance",
    key: "F",
    mode: "major",
    meter: "2/4",
    origin: "Scottish country dance tune; printed among the Country Dances in F major for violin with a piano bass, both strains repeated",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:Petronella\nM:2/4\nL:1/8\nK:F\nf/c/ | A c/A/ G c/A/ | FFF A,/C/ | F B,/D/ G =F | E G/E/ C f/c/ |\nA c/A/ G c/A/ | FFF A,/C/ | F B,/D/ GE | F2 F :|\n|: e/c/ | A a/f/ c a/f/ | b b/g/ e/c/B/G/ | E g/e/ c b/g/ | a a/f/ c/g/c/A/ |\nF a/f/ c a/f/ | b b/g/ e/c/B/G/ | E g/e/ c/b/g/e/ | fff :|",
    source: { ...SOURCE, where: "p. 150 (PDF page 162), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 162, each treble staff in halves at 300 dpi and thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p184-neil-gows-lament-for-abercairny",
    title: "Neil Gow's Lament for Abercairny",
    region: "scottish",
    kind: "lament",
    key: "G",
    mode: "major",
    meter: "C",
    origin: "Scottish slow strathspey by Niel Gow; marked Slow Strathspey and printed in G major for violin with a piano bass; first strain repeated, second strain printed once and closed with a sign directing a return to the start",
    tags: ["air", "slow", "lament", "strathspey", "highlands", "scottish"],
    abc: "X:1\nT:Neil Gow's Lament for Abercairny\nM:C\nL:1/8\nK:G\nB, | G,3/2B,/ D3/2G/ E3/2G/ D3/2G/ | A3/2B/ c/B/A/G/ E2 E3/2G/ |\nG,3/2B,/ D3/2G/ EG Dg/e/ | d3/2G/ d/=c/B/A/ G2 G :|\nB/c/ | d e/f/ g3/2d/ e3/2d/ g3/2B/ | c a/c/ B g/B/ A2 A3/2B/ |\nG,3/2B,/ D3/2G/ E3/2G/ D g/e/ | d3/2G/ d/=c/B/A/ G2 G/A/B/c/ |\nd e/f/ g3/2d/ e3/2d/ g3/2B/ | c a/c/ B g/B/ A2 A B/c/ |\ne/d/c/B/ d/c/B/A/ c/B/A/G/ B/A/G/F/ | A/G/F/E/ D/E/D/B,/ G,2 G,/C/B,/A,/ |]",
    source: { ...SOURCE, where: "p. 184 (PDF page 196), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 196, each treble staff in thirds at 450 dpi, note heads located against the measured staff lines, every low ledger note and doubtful spot at 600 to 1000 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p164-the-waking-of-the-fauld",
    title: "The Waking of the Fauld",
    region: "scottish",
    kind: "strathspey",
    key: "A",
    mode: "dorian",
    meter: "C",
    origin: "Scottish song air marked Slow Strathspey; printed with a one-sharp signature, ending on A, for violin with a piano bass; eight bars played through once",
    tags: ["strathspey", "air", "slow", "highlands", "scottish"],
    abc: "X:1\nT:The Waking of the Fauld\nM:C\nL:1/8\nK:Ador\nA/G/ | E/A3/2 A3/2B/ A2 g3/2e/ | d3/2B/ A3/2G/ E2 D3/2E/ |\nG3/2A/ B3/2A/ G/E3/2 D3/2E/ | G/A3/2 B3/2A/ G/E3/2 D3/2G/ |\nE/A3/2 A3/2B/ A2 G3/2A/ | B3/2A/ B3/2d/ e2 g3/2a/ |\nb3/2a/ g3/2e/ d e/f/ g3/2B/ | A/G3/2 E3/2G/ A3 |]",
    source: { ...SOURCE, where: "p. 164 (PDF page 176), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 176, each treble staff in thirds at 450 dpi, note heads located against the measured staff lines, every dot, partial beam and ledger note at 800 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p148-corn-rigs",
    title: "Corn Rigs",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish country dance on the old song tune; printed among the Country Dances in G major for violin with a piano bass in three strains, the first repeated",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:Corn Rigs\nM:C|\nL:1/8\nK:G\nD | G3A cBAG | FEFG A2D2 | G3A BcAB | G2de d2D2 |\nG3A cBAG | FEFG A2D2 | EFGE AGFE | D2G2 G3 :|\nD | G2d2 BcdG | FEFG A2D2 | G2dc BcAB | G2de d2D2 |\nG2d2 edcB | cBAG F2D2 | EFGE AGFE | D2G2 G3D |\nG2d2 BcdG | FEFG A2D2 | G2dc BcAB | G2de d2ef |\ngfed edcB | cBAG GFED | EFGE AGFE | D2G2 G3 |]",
    source: { ...SOURCE, where: "p. 148 (PDF page 160), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 160, each treble staff in thirds at 400 dpi, note heads located against the measured staff lines, doubtful spots at 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p248-sweet-molly",
    title: "Sweet Molly",
    region: "scottish",
    kind: "reel",
    key: "E",
    mode: "minor",
    meter: "C|",
    origin: "Scottish reel; printed in E minor for violin with a piano bass; first strain repeated, second strain of eight bars printed once",
    tags: ["reel", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Sweet Molly\nM:C|\nL:1/8\nK:Em\ne | E/E/E BE dE Be | dBAF DEFD | E/E/E BE dE Be | dBAF BBE :|\nF | Eeef gfed | BdAF DEFD | Eeef gfed | BdAF BEEF |\nEeef gfed | BdAF DEFf | afge fde^c | dBAF BBE |]",
    source: { ...SOURCE, where: "p. 248 (PDF page 260), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 260, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p134-the-stool-of-repentance",
    title: "The Stool of Repentance",
    region: "scottish",
    kind: "jig",
    key: "A",
    mode: "major",
    meter: "6/8",
    origin: "Scottish jig; printed among the Jigs in A major for violin with a piano bass, both strains repeated",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:The Stool of Repentance\nM:6/8\nL:1/8\nK:A\ne |: a2e c2e | agf edc | aff f2e | fag f2e |\na2e c2e | agf edc | d2f efg | a2c B2A :|\n|: cAA eAA | cAA edc | dBB fBB | dBB fed |\ncAA eAA | cAA edc | d2e f2e | fac B2A :|",
    source: { ...SOURCE, where: "p. 134 (PDF page 146), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 146, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p134-teviot-bridge",
    title: "Teviot Bridge",
    region: "scottish",
    kind: "jig",
    key: "A",
    mode: "major",
    meter: "6/8",
    origin: "Scottish jig; printed among the Jigs in A major for violin with a piano bass; first strain of eight bars repeated, second strain of sixteen bars printed once",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Teviot Bridge\nM:6/8\nL:1/8\nK:A\nf | ecA E2A | F2A E2A | EFE E2c | d2c B2f |\necA E2A | F2A E2c | d2f ecA | B3 A2 :|\nf | ecA Ace | fgf fga | ecA AcA | BGE E2f |\necA Ace | agf edc | d2f ecA | B3 A2f |\necA Ace | fgf fga | ecA ABA | BGE E2f |\nece fdf | agf edc | dfa ecA | B3 A2 |]",
    source: { ...SOURCE, where: "p. 134 (PDF page 146), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 146, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p136-the-general-gathering-1745",
    title: "The General Gathering 1745",
    region: "scottish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Scottish jig; printed among the Jigs in D major for violin with a piano bass; first strain repeated, second strain of sixteen bars printed once; the last note is a double stop whose top note is given",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:The General Gathering 1745\nM:6/8\nL:1/8\nK:D\nf | d2F FGF | ABc def | edc dcB | A2E E2f |\nd2F FGF | ABc def | edc dcB | A2F F2 :|\nd | AGF AGF | AGF ABc | dcB AGF | A2E E2B |\nAGF AGF | ABc def | edc dcB | A2F F2d |\nAGF AGF | AGF ABc | dcB AGF | A2E E2B |\nAGF ABc | def efg | agf edc | dAF F2 |]",
    source: { ...SOURCE, where: "p. 136 (PDF page 148), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 148, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p136-lads-of-duns",
    title: "Lads of Duns",
    region: "scottish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Scottish jig; printed among the Jigs in D major for violin with a piano bass; first strain repeated, second strain of sixteen bars printed once",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Lads of Duns\nM:6/8\nL:1/8\nK:D\nB | A2D DED | DED B2A | Bcd AFA | BGE E2d |\nA2D DED | DED B2A | Bcd AFd | AFD D2 :|\ng | fef d2e | fga B2A | Bcd AFA | BGE E2g |\nfef d2e | fga B2A | Bcd AFd | AFD D2g |\nfef d2e | fga B2A | Bcd AFA | BGE E2f/g/ |\nafa geg | fdf ece | dcB AFd | AFD D2 |]",
    source: { ...SOURCE, where: "p. 136 (PDF page 148), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 148, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p138-old-isle-of-mull-tune",
    title: "Old Isle of Mull Tune",
    region: "scottish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Scottish tune printed among the Jigs in D major for violin with a piano bass, as the first tune of The Dervaig Medley; first strain repeated, second strain of sixteen bars printed once; where the violin plays a double stop the top note is given",
    tags: ["jig", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Old Isle of Mull Tune\nM:6/8\nL:1/8\nK:D\nB | AAA A3 | F2A d2B | AAA A2B | A2F E2B |\nAAA A3 | A2A d2e | fdd d2B | A2F D2 :|\ne | fdd d2d | d2d d2e | fdd d2f | e2c A2e |\nfdd d2d | d2d d2d | BGG G2B | A2F D2e |\nfdd d2d | d2d d2e | fdd d2f | e2c A2e |\nfdd dAA | BAA dAA | BGG AFF | A2F D2 |]",
    source: { ...SOURCE, where: "p. 138 (PDF page 150), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 150, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p139-irish-washerwoman",
    title: "Irish Washerwoman",
    region: "irish",
    kind: "jig",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish jig, printed among the Jigs of this Scottish collection in G major for violin with a piano bass; both strains repeated",
    tags: ["jig", "dance", "irish"],
    abc: "X:1\nT:Irish Washerwoman\nM:6/8\nL:1/8\nK:G\nd/c/ | BGG DGG | BGB dcB | cAA EAA | cAc edc |\nBGG DGG | BGB dcB | cBc Adc | BGG G2 :|\n|: d | gdg gdg | gdg bag | =fcf fcf | =fcf agf |\negg dgg | cgg Bgg | cBc Adc | BGG G2 :|",
    source: { ...SOURCE, where: "p. 139 (PDF page 151), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 151, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p142-meg-merrilees",
    title: "Meg Merrilees",
    region: "scottish",
    kind: "country-dance",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Scottish country dance; printed among the Country Dances in A major for violin with a piano bass; two strains of eight bars, each printed once; where the violin plays a double stop the top note is given; a natural on D after a sharpened grace note is kept",
    tags: ["dance", "reel", "highlands", "scottish"],
    abc: "X:1\nT:Meg Merrilees\nM:C|\nL:1/8\nK:A\ncd | edcd eagf | feee e2cd | efec efec | cBBB B2cd |\nedcd eagf | feee e2cd | efec BABc | A2AA A3 ||\ne | defe =deBe | ceAe BeGe | defe =dcdB | BAAA A2e2 |\ndefe =deBe | ceAe BeGe | BABc defg | agag a2 |]",
    source: { ...SOURCE, where: "p. 142 (PDF page 154), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 154, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p206-bonny-lass-of-ballantrae",
    title: "Bonny Lass of Ballantrae",
    region: "scottish",
    kind: "reel",
    key: "F",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; printed in F major for violin with a piano bass; first strain repeated, second strain of eight bars printed once",
    tags: ["reel", "dance", "highlands", "scottish"],
    abc: "X:1\nT:Bonny Lass of Ballantrae\nM:C|\nL:1/8\nK:F\nf | cFAc dfef | cFAF GDDd | cFAc dfeg | afce f2f :|\nc | fcfa gceg | f/g/a gf ecce | fcfa gcgb | afce f2fc |\nfcfa gceg | f/g/a gf eccf | dBfd cFAc | dfeg f2f |]",
    source: { ...SOURCE, where: "p. 206 (PDF page 218), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 218, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p296-jack-a-tar",
    title: "Jack a' Tar",
    region: "scottish",
    kind: "hornpipe",
    key: "E",
    mode: "minor",
    meter: "C|",
    origin: "Hornpipe, the first of the Hornpipes in this Scottish collection; printed with a one-sharp signature for violin with a piano bass, both strains ending on E; two strains of eight bars, each printed once",
    tags: ["dance", "hornpipe", "highlands", "scottish"],
    abc: "X:1\nT:Jack a' Tar\nM:C|\nL:1/8\nK:Em\nB2 | e2e2 efge | d2B2-B2dB | ABde faef | d2A2-A2z2 |\ne2ef g2fe | dBGB d2BA | GFGE DEFA | G2E2E2 ||\nGA | BGEG BGEG | BAGF E2FG | AFDF AFDF | AGFE D2EF |\nGFGE g2fe | dBGB d2BA | GFGE DEFA | G2E2E2 |]",
    source: { ...SOURCE, where: "p. 296 (PDF page 308), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 308, each treble staff in quarters at 400 dpi against guides drawn on the measured staff lines, doubtful heads and beams at 600 to 700 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p143-jenny-nettles",
    title: "Jenny Nettles",
    region: "scottish",
    kind: "country-dance",
    key: "A",
    mode: "minor",
    meter: "C|",
    origin: "Scottish country dance on the old song tune; printed first among the Country Dances with no key signature, ending on A, for violin with a piano bass; first and second strains of four bars each repeated, third strain of eight bars printed once",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:Jenny Nettles\nM:C|\nL:1/8\nK:Am\nA/B/ | c2B2 A2a2 | e^fge dBGB | cdBc A2a2 | ge^fd e2A :|\n|: B | cdeA cdec | BAGd BGdB | cdeA cdea | ge^fd e2A :|\nB | cde^f gage | gage dBGB | cde^f gage | aba^g a2AB |\ncde^f gage | gage dBGB | cde^f gagf | ea^gb a2A |]",
    source: { ...SOURCE, where: "p. 143 (PDF page 155), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 155, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p296-wests",
    title: "Wests",
    region: "scottish",
    kind: "hornpipe",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Hornpipe, the second of the Hornpipes in this Scottish collection; printed in D major for violin with a piano bass; two strains of eight bars, both repeated",
    tags: ["dance", "hornpipe", "highlands", "scottish"],
    abc: "X:1\nT:Wests\nM:C|\nL:1/8\nK:D\nA2 | d2FG AFAF | d2FG AFAF | BAGF E2ef | gfed cABc |\nd2FG AFAF | d2FG AFAF | BAGF E2eg | fdec d2 :|\n|: de | f2df dfdf | e2ce cece | f2df dfdf | edcB A2Bc |\ndBdB cAcA | dBdB cAcA | afge fdec | d2d2d2 :|",
    source: { ...SOURCE, where: "p. 296 (PDF page 308), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 308, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p153-neil-gows-farewell-to-whisky",
    title: "Neil Gow's Farewell to Whisky",
    region: "scottish",
    kind: "country-dance",
    key: "G",
    mode: "major",
    meter: "C|",
    origin: "Scottish tune by Neil Gow, printed among the Country Dances in G major for violin with a piano bass; two strains of four bars, both repeated; the opening goes down to the violin's low G",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:Neil Gow's Farewell to Whisky\nM:C|\nL:1/8\nK:G\nB,/A,/ | G,G/A/ B/A/G/B/ AE EF/G/ | DG/A/ B/A/G/B/ dB B3/2d/ |\ne/f/g/f/ e/d/B/d/ c/B/A/G/ A3/2B/ | D/E/G/A/ B/A/G/A/ BGG :|\n|: B/c/ | dB gB/d/ =c/B/A/G/ AB/c/ | dBgB dgg3/2d/ |\ne/f/g/f/ e/d/B/d/ c/B/A/G/ A/c/B/A/ | D/E/G/A/ B/A/G/A/ BGG :|",
    source: { ...SOURCE, where: "p. 153 (PDF page 165), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 165, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p153-whats-a-the-steer",
    title: "What's a' the Steer",
    region: "scottish",
    kind: "country-dance",
    key: "C",
    mode: "major",
    meter: "2/4",
    origin: "Scottish country dance on the song tune; printed among the Country Dances with no key signature, ending on C, for violin with a piano bass; two strains of eight bars, each printed once",
    irregular: "bar 4 is printed as a quarter note and an eighth rest, one eighth short of the 2/4 bar, kept as printed",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:What's a' the Steer\nM:2/4\nL:1/8\nK:C\ne2 e3/2d/ | e2 e/g3/2 | e2 e3/2d/ | e2 z |\ng3/2a/ ge | a2 =g3/2e/ | g3/2a/ g3/2e/ | d2 ze |\ncA GA | c2 e3/2d/ | c3/2A/ GA | c2 ze |\ne3/2f/ g3/2e/ | a2 da | g3/2e/ ed | c2 z |]",
    source: { ...SOURCE, where: "p. 153 (PDF page 165), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 165, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p152-maclauchlanes-scotch-measure",
    title: "MacLauchlane's Scotch Measure",
    region: "scottish",
    kind: "country-dance",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish Scotch Measure, printed among the Country Dances in D major for violin with a piano bass; two strains of eight bars, both repeated",
    tags: ["dance", "highlands", "scottish"],
    abc: "X:1\nT:MacLauchlane's Scotch Measure\nM:C|\nL:1/8\nK:D\nF3/2E/ | D2DF EDEF | A2E2- E2F3/2E/ | D2DF EDEF | AFED d2d3/2e/ |\nf3/2e/df edBe | dBAF E2F3/2E/ | DEFG ABdA | F2D2D2 :|\n|: f3/2e/ | d2a2 fgaf | b2e2- e2f3/2e/ | d2a2 fgab | agfe d2d3/2e/ |\nf3/2e/df e3/2d/Be | dBAF E2F3/2E/ | DEFG ABdA | F2D2D2 :|",
    source: { ...SOURCE, where: "p. 152 (PDF page 164), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 164, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p299-college",
    title: "College",
    region: "english",
    kind: "hornpipe",
    key: "Bb",
    mode: "major",
    meter: "C|",
    origin: "The College Hornpipe, printed under the title College among the Hornpipes of this Scottish collection, in B flat major for violin with a piano bass; two strains of eight bars, both repeated; where the violin plays a double stop the top note is given",
    tags: ["dance", "hornpipe", "english"],
    abc: "X:1\nT:College\nM:C|\nL:1/8\nK:Bb\nBA | B2B,2B,2FE | DFB2B2dB | c2C2C2cB | Acf2f2ga |\nbagf gfed | edcB BAGF | GBAc Bdce | d2B2B2 :|\n|: FE | DFBF DFBF | G2E2E2G=F | =EGcG EGcG | A2F2F2ed |\ne2g2 gfed | edcB BAGF | GBAc Bdce | d2B2B2 :|",
    source: { ...SOURCE, where: "p. 299 (PDF page 311), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 311, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p300-morpeth-rant",
    title: "Morpeth Rant",
    region: "english",
    kind: "hornpipe",
    key: "Bb",
    mode: "major",
    meter: "C|",
    origin: "The Northumbrian Morpeth Rant, printed among the Hornpipes of this Scottish collection in B flat major for violin with a piano bass; two strains of eight bars, both repeated",
    tags: ["dance", "hornpipe", "english"],
    abc: "X:1\nT:Morpeth Rant\nM:C|\nL:1/8\nK:Bb\nFG/A/ | B2FE DB,DF | GEGB AFAc | dBec fdcB | A2c2c2BA |\nB2FE DB,DF | GEGB AFAc | Bbag fedc | B2d2B2 :|\n|: ga | bfdB Aceg | fdcB BAGF | ecec dBdB | A2F2F2_A2 |\nGEGB edcB | AFAc fedc | Bbag fedc | d2B2B2 :|",
    source: { ...SOURCE, where: "p. 300 (PDF page 312), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 312, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p297-fishers",
    title: "Fishers",
    region: "english",
    kind: "hornpipe",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "The Fisher's Hornpipe, printed under the title Fishers, first among the Hornpipes of this Scottish collection, in D major for violin with a piano bass; two strains of eight bars, both repeated; where the violin plays a double stop the top note is given",
    tags: ["dance", "hornpipe", "english"],
    abc: "X:1\nT:Fishers\nM:C|\nL:1/8\nK:D\ndc | dAFA GBAG | FAFA GBAG | FDFD GEGE | FDFD E2dc |\ndAFA GBAG | FAFA GBAG | FAdf gedc | d2d2d2 :|\n|: cd | ecAc ecge | fdAd fdaf | ecAc ecgf | edcB A3A |\nBGDG BGdB | AFDF AFdA | BdcB AGFE | D2D2D2 :|",
    source: { ...SOURCE, where: "p. 297 (PDF page 309), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 309, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
  {
    id: "athole-p250-ill-hap-ye-in-my-plaidie",
    title: "I'll Hap ye in my Plaidie",
    region: "scottish",
    kind: "strathspey",
    key: "E",
    mode: "minor",
    meter: "C",
    origin: "Scottish strathspey on the song tune, printed among the tunes in E minor for violin with a piano bass; the first strain of four bars is repeated, the second of eight bars is printed once",
    tags: ["strathspey", "dance", "highlands", "scottish"],
    abc: "X:1\nT:I'll Hap ye in my Plaidie\nM:C\nL:1/8\nK:Em\ng | d3/2B/A3/2G/ E3/2D/E3/2G/ | d3/2e/d3/2B/ d3g |\nd3/2B/A3/2G/ E3/2D/E3/2G/ | e3/2f/e3/2^d/ e2e :|\ng | d3/2e/g3/2a/ g/a/b a3/2g/ | d3/2e/d3/2B/ d3g |\nd3/2e/g3/2a/ g/a/b a3/2g/ | e/b3/2a3/2g/ e3g |\nd3/2e/g3/2a/ g/a/b a3/2g/ | d3/2e/d3/2B/ d3g |\nd3/2B/A3/2G/ E3/2D/E3/2G/ | e2 e3/2^d/ e3 |]",
    source: { ...SOURCE, where: "p. 250 (PDF page 262), Internet Archive athole-collection, 1961 Oliver & Boyd reprint from the original 1884 plates" },
    transcription: "read from the scan (PDF page 262, each treble staff in halves and thirds at 450 to 500 dpi against guides drawn on the measured staff lines, doubtful heads, ledger notes and beams again at 600 to 900 dpi, then proofed bar by bar) by lane MELODIES200 reader athole-b, 2026-10-02",
  },
];

export default TUNES;
