// settle-hear · tunes/athole-a - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book: wikis/WIKI_OLD_MELODIES/books/BOOK_ATHOLE_A.md. The melody is the top (violin) staff of the 1884 print;
// the scan is the 1961 Oliver and Boyd reprint from the original plates (PDF page = printed page + 12).

export const SOURCE = {
  kind: 'print',
  book: 'The Athole Collection of the Dance Music of Scotland',
  compiler: 'James Stewart-Robertson of Edradynate',
  year: 1884,
  scan: 'https://archive.org/details/athole-collection',
};

export const TUNES = [
  {
    id: "athole-p5-masons-apron",
    title: "Mason's Apron",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the print returns to the sign (D.S.) for a second time through with A above the stave as the first note, written out here in full",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Mason's Apron\nM:C|\nL:1/8\nK:A\ne | cA-AB ABAF | EFAB c2BA | dB-Bc BcBA | Bcde f2ed |\ncA-AB ABAF | EFAB c2BA | Bcde fefa | A/A/A c3/2B/ A2A ||\ne | cAeA fAeA | cAeA fedc | dBfB bBfB | dBfB f2ed |\ncAeA fAeA | ceaf fedc | dcde fgaf | edcB Aagb ||\naA-AB ABAF | EFAB c2BA | dB-Bc BcBA | Bcde f2ed |\ncA-AB ABAF | EFAB c2BA | Bcde fefa | A/A/A c3/2B/ A2A ||\ne | cAeA fAeA | cAeA fedc | dBfB bBfB | dBfB f2ed |\ncAeA fAeA | ceaf fedc | dcde fgaf | edcB Aagb |]",
    source: { ...SOURCE, where: "p. 5 (PDF page 17)" },
    transcription: "read from the scan (PDF page 17, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p1-auld-lang-syne",
    title: "Auld Lang Syne",
    region: "scottish",
    kind: "strathspey",
    key: "A",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey, the old air; the print says as arranged by John McAlpin, Killin",
    tags: ["highlands", "strathspey", "dance", "scottish"],
    abc: "X:1\nT:Auld Lang Syne\nM:C\nL:1/8\nK:A\nE | A2 A3/2c/ B3/2A/B3/2c/ | AAA3/2a/ f2 f3/2a/ | e/c3/2c3/2A/ B3/2A/B3/2c/ | A3/2F/E3/2F/ A2A :|\n|: a | e/c3/2c3/2A/ B3/2A/B3/2c/ | e/c3/2c3/2e/ f3/2g/a3/2f/ | e3/2c/c3/2A/ B3/2A/B3/2c/ | A3/2F/E3/2F/ A2A :|",
    source: { ...SOURCE, where: "p. 1 (PDF page 13)" },
    transcription: "read from the scan (PDF page 13, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p11-the-deil-amang-the-tailors",
    title: "The Deil amang the Tailors",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the second strain is repeated with first and second time endings, as printed",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:The Deil amang the Tailors\nM:C|\nL:1/8\nK:A\ne/f/ | a2ef a2ef | a2ea fedc | dfBf dfBf | dfBf gabg |\na2ef a2ef | a2ea fedc | fgaf ecBA | EBGB A2A ||\n|: e | ceAe ceAe | ceAa gedc |1 dfBf dfBf | dfBf gabe :|2 fgaf ecBA | EBGB A2A |]",
    source: { ...SOURCE, where: "p. 11 (PDF page 23)" },
    transcription: "read from the scan (PDF page 23, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p11-keel-row",
    title: "Keel Row",
    region: "english",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Tyneside song tune printed as a reel in this Scottish collection; the second strain has first and second time endings, as printed",
    tags: ["reel", "dance", "english", "highlands"],
    abc: "X:1\nT:Keel Row\nM:C|\nL:1/8\nK:A\ne/d/ | cA A/A/A d2Bd | c2 A3/2c/ BGEe | cA A/A/A d2 B3/2d/ | cABG A2A :|\n|: d | ceea f2ed | cAAc BGEe |1 ceea f2 e3/2d/ | cABG A2A :|2 ce ef/g/ aefd | cABG A2A |]",
    source: { ...SOURCE, where: "p. 11 (PDF page 23)" },
    transcription: "read from the scan (PDF page 23, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p11-lady-madelina-sinclair",
    title: "Lady Madelina Sinclair",
    region: "scottish",
    kind: "strathspey",
    key: "A",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey; the first strain is repeated, the second played once, as printed",
    tags: ["highlands", "strathspey", "dance", "scottish"],
    abc: "X:1\nT:Lady Madelina Sinclair\nM:C\nL:1/8\nK:A\nf | e3/2A/c/A3/2 c/d/e f2 | e3/2A/ f/e/d/c/ B2 B3/2f/ | e3/2A/c3/2A/ c/d/e a2 | A3/2A/c3/2B/ A2A :|\ng | a3/2e/f3/2e/ (3fga (3gab | a/g/f/e/ a3/2c/ B2 B3/2g/ | a3/2e/f3/2e/ (3fga (3gab | (3agf (3efg a2 ef/g/ |\na3/2f/g3/2e/ f3/2d/e3/2c/ | d3/2b/c3/2a/ B3d | c/d/e f2 c/d/e a2 | AAc3/2B/ A2A |]",
    source: { ...SOURCE, where: "p. 11 (PDF page 23)" },
    transcription: "read from the scan (PDF page 23, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p6-reel-of-tulloch",
    title: "Reel of Tulloch",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the print marks a sign at the first bar and again at the last bar to go back to it, written here as a repeat after the opening pickup",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Reel of Tulloch\nM:C|\nL:1/8\nK:A\na/f/ |: e2 A3/2c/ e3/2c/ A3/2a/ | e2 A3/2c/ d3/2B/ =G3/2f/ | e2 A3/2c/ e3/2A/ c3/2A/ | B3/2E/ c/d/e d3/2B/ =G3/2f/ |\ne2 e3/2c/ ecAa | e2 e3/2c/ dB=Gf | e2 e3/2a/ e3/2A/ c3/2A/ | Bece d3/2B/ =G3/2B/ ||\nc3/2A/ c/d/e cAAB | c3/2A/ c/d/e dB=GB | cA c/d/e cAcA | BEBe dB=GB |\ncA c/d/e cAAB | cA c/d/e dB=GB | cA c/d/e c2 c3/2e/ | Bece d3/2B/ =G3/2f/ :|",
    source: { ...SOURCE, where: "p. 6 (PDF page 18)" },
    transcription: "read from the scan (PDF page 18, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p15-speed-the-plough",
    title: "Speed the Plough",
    region: "english",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "English reel, here in a Scottish collection; each strain is printed once, its second half a varied repeat of its first",
    tags: ["reel", "dance", "english", "highlands"],
    abc: "X:1\nT:Speed the Plough\nM:C|\nL:1/8\nK:A\nE | A2 Ac efec | eaec efec | dfdB cecA | FBBA GABc |\nABcd efec | eaga ecAc | decd BcAB | FAGB A2 A ||\ng | a2 ag aece | aAgA fAec | dfdB cecA | FBBA GABd |\ncAce aece | fgaf ecAc | decd BcAB | FAGB A2 A |]",
    source: { ...SOURCE, where: "p. 15 (PDF page 27)" },
    transcription: "read from the scan (PDF page 27, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p33-high-road-to-linton",
    title: "High Road to Linton",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; both strains repeated, as printed",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:High Road to Linton\nM:C|\nL:1/8\nK:A\ne | ceeg a2 a3/2e/ | fefg a2 ae | ceeg a2 ae | faec B2 A :|\n|: d | ceea fddf | ecce fBBd | ceea fddf | ecac B2 A :|",
    source: { ...SOURCE, where: "p. 33 (PDF page 45)" },
    transcription: "read from the scan (PDF page 45, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p83-jenny-dang-the-weaver",
    title: "Jenny Dang the Weaver",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the print marks a sign at the first bar and again at the end to go back to it, written here as a repeat after the opening pickup",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Jenny Dang the Weaver\nM:C|\nL:1/8\nK:D\nf/e/ |: d3/2A/ A/A/A AFAB | d3/2A/ A/A/A f2 ef | d3/2B/ B/B/B BABd | ABde faef |\nd3/2A/ A/A/A AFAB | d3/2A/ A/A/A f2 ef | dB B/B/B BABd | ABde f2 e || f |\nd2 fd efge | d2 fd e2 cA | d2 fd efge | aA A/A/A f2 ef |\nd2 fd efge | defd e2 cA | defd efge | abag faef :|",
    source: { ...SOURCE, where: "p. 83 (PDF page 95)" },
    transcription: "read from the scan (PDF page 95, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p97-marquis-of-huntlys-highland-fling",
    title: "Marquis of Huntly's Highland Fling",
    region: "scottish",
    kind: "strathspey",
    key: "D",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey; the second strain has first and second time endings, as printed; the second ending closes on a double stop whose top note is given",
    tags: ["highlands", "strathspey", "dance", "scottish"],
    abc: "X:1\nT:Marquis of Huntly's Highland Fling\nM:C\nL:1/8\nK:D\nA | d/d3/2 f3/2d/ g3/2e/ f/d3/2 | B/B3/2 e3/2d/ c3/2A/ A3/2c/ | d/d3/2 f3/2d/ g3/2e/ f3/2d/ | B3/2e/ d/c/B/A/ d2 d :|\n|: B | A3/2D/ F3/2D/ A3/2B/ d3/2e/ | f/d3/2 g3/2f/ e3/2d/ B/d3/2 | A3/2D/ F3/2D/ A3/2B/ d/b3/2 |1 a/f3/2 e3/2f/ d2 d :|2 (3agf (3gfe d2 d |]",
    source: { ...SOURCE, where: "p. 97 (PDF page 109)" },
    transcription: "read from the scan (PDF page 109, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p116-lovats-restoration",
    title: "Lovat's Restoration",
    region: "scottish",
    kind: "strathspey",
    key: "D",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey; the first strain is repeated with two-bar first and second time endings, as printed; the print returns to the sign at the first bar after the second strain, and the tune is written here once through",
    tags: ["highlands", "strathspey", "dance", "scottish"],
    abc: "X:1\nT:Lovat's Restoration\nM:C\nL:1/8\nK:D\nf |: d/d3/2 f3/2d/ e3/2d/ f3/2d/ | B/B3/2 e3/2B/ c3/2A/ e/A3/2 |1 d3/2d/ f3/2d/ e3/2d/ f/d3/2 | F/F3/2 d3/2F/ E2 D3/2f/ :|2 d3/2d/ f3/2d/ e3/2d/ f/d3/2 | e3/2c/ d3/2F/ E2 D || B |\nA/F3/2 d3/2F/ e3/2F/ d3/2F/ | A/F3/2 d3/2F/ E3/2F/ G/B3/2 | A/F3/2 d3/2F/ e/c3/2 d/f3/2 | A/d3/2 F/d3/2 E2 D3/2B/ |\nA/F3/2 d3/2F/ e3/2F/ d3/2F/ | A/F3/2 d3/2F/ E3/2F/ G/g3/2 | a3/2f/ e3/2c/ d3/2f/ B/d3/2 | A/d3/2 F/d3/2 E2 D3/2f/ |]",
    source: { ...SOURCE, where: "p. 116 (PDF page 128)" },
    transcription: "read from the scan (PDF page 128, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p42-miss-lyall",
    title: "Miss Lyall",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "minor",
    meter: "C|",
    origin: "Scottish reel; the first strain is repeated, the second printed once, and the print returns to the sign at the first bar at the end; the tune is written here once through",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Miss Lyall\nM:C|\nL:1/8\nK:Am\nc/B/ | AE E/E/E cABG | EGDG B,G,DB, | A,/A,/A, EA, CDEd | cAc^G A/A/A A :|\nB | Aaa^g ae^cA | Bgg^f gdBG | Aaa^g ae^fd | e^ceB =cAAB |\nAaa^g ae^cA | Bgg^f gdBG | AcBd ced^f | ea^g^f ed^cB |]",
    source: { ...SOURCE, where: "p. 42 (PDF page 54)" },
    transcription: "read from the scan (PDF page 54, each staff in halves at 400 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p113-the-fairy-dance",
    title: "The Fairy Dance",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; each strain is repeated with first and second time endings, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:The Fairy Dance\nM:C|\nL:1/8\nK:D\n|: f2fd f2fd | f2fd cAeA | f2fd gfed |1 cABc d2de :|2 cABc defg ||\n|: a2af b2ba | gfge a2ag |1 fefd B2 e3/2d/ | cABc defg :|2 fefd Bged | cABc d2D2 |]",
    source: { ...SOURCE, where: "p. 113 (PDF page 125)" },
    transcription: "read from the scan (PDF page 125, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p44-muileann-dubh",
    title: "Muileann Dubh",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "minor",
    meter: "C|",
    origin: "Scottish reel, Gaelic title Muileann Dubh (the black mill); printed once through with no repeats; the eighth bar ends on a dotted eighth before the second strain's eighth-note pickup, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Muileann Dubh\nM:C|\nL:1/8\nK:Am\na | ede^f g2fe | dGdB dGdg | ede^f g2fe | dGdB A2 A3/2a/ |\nede^f g2fe | dGdB dGdg | ede^f gage | dBgB A2 A3/2 ||\na | eAed eAAB | dGdB dGGg | eAed eAAB | dGdB A2 A3/2a/ |\neAed eAAB | dGdB dGGg | ede^f gbge | dgBg A2 A |]",
    source: { ...SOURCE, where: "p. 44 (PDF page 56)" },
    transcription: "read from the scan (PDF page 56, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p89-the-wind-that-shakes-the-barley",
    title: "The Wind that Shakes the Barley",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Reel, here in a Scottish collection; the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:The Wind that Shakes the Barley\nM:C|\nL:1/8\nK:D\nA | FAAB AFED | B2BA B2d2 | FAAB AFED | gfed B2d :|\ne | f2fd g2ge | f2fd Bcde | f2fd g2gb | afed B2 d3/2e/ |\nf2fd g2ge | f2fd Bcde | fafd gbge | afed B2d |]",
    source: { ...SOURCE, where: "p. 89 (PDF page 101)" },
    transcription: "read from the scan (PDF page 101, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p89-rachel-rae",
    title: "Rachel Rae",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Rachel Rae\nM:C|\nL:1/8\nK:D\nA, | D2FA d2Ac | d2fd fedc | d2Ad BAGF | E2AE FDD :|\nA | defg a2fd | g2bg e2cA | defg a2fd | Agfe fddA |\ndefg fafd | g2bg eecA | d2Ad BAGF | E2AE FDD |]",
    source: { ...SOURCE, where: "p. 89 (PDF page 101)" },
    transcription: "read from the scan (PDF page 101, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p89-old-set-of-the-braes-of-mar",
    title: "Old Set of the Braes of Mar",
    region: "scottish",
    kind: "strathspey",
    key: "D",
    mode: "major",
    meter: "C",
    origin: "Scottish strathspey, the old setting of The Braes of Mar; both strains repeated, as printed",
    tags: ["highlands",  "strathspey",  "dance",  "scottish"],
    abc: "X:1\nT:Old Set of the Braes of Mar\nM:C\nL:1/8\nK:D\nA | F/A3/2 AB/c/ d3/2e/ f3/2e/ | d/B3/2 B3/2A/ d/B3/2 BA/G/ | F/A3/2 A3/2B/ d3/2e/ f3/2d/ | e/g3/2 f/a3/2 e2 d :|\n|: g | f/a3/2 a2 f/d3/2 a3/2f/ | g/b3/2 b2 g/e3/2 b3/2g/ | f/a3/2 a2 f/d3/2 a3/2f/ | g/b3/2 f/a3/2 e2 d :|",
    source: { ...SOURCE, where: "p. 89 (PDF page 101)" },
    transcription: "read from the scan (PDF page 101, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p105-this-is-no-my-ain-house",
    title: "This is no' my ain House",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel on the old song tune; the first strain is repeated, the second printed once in full, as printed; a scanning smear covers the lower part of the first two sixteenth notes in bar 4, whose heads, beams and the identical figure in bar 2 fix them as B and c",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:This is no' my ain House\nM:C|\nL:1/8\nK:D\nA | FAAa f2ed | B/c/d AF BEEG | FADa f2ed | B/c/d AG FDD :|\nA | FAAd B/c/d AF | GBAF BEEG | FAAd B/c/d AF | GBAG FDDG |\nFAAd B/c/d AF | GBAF BEEG | FADa gfed | B/c/d AG FDD |]",
    source: { ...SOURCE, where: "p. 105 (PDF page 117)" },
    transcription: "read from the scan (PDF page 117, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p118-the-honey-moon",
    title: "The Honey Moon",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Reel, here in a Scottish collection; both strains repeated, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:The Honey Moon\nM:C|\nL:1/8\nK:D\nA | Addd dffa | gfed ce A2 | Addd dffa | gfge d2d :|\n|: A | dA A2 BcdB | AFED CE E2 | dA A2 Bcde | fgef d2d :|",
    source: { ...SOURCE, where: "p. 118 (PDF page 130)" },
    transcription: "read from the scan (PDF page 130, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p118-mrs-moray-of-abercairny-reel",
    title: "Mrs Moray of Abercairny",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, the first of two tunes of this name on the page (the second is a strathspey); the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Mrs Moray of Abercairny\nM:C|\nL:1/8\nK:D\nA | F2DF ABAF | ABdF E2EA | FDDF ABAF | ABdF A2A :|\nB | defd ecdB | AFdF E2Ee | defa efde | dBAF A2AB |\ndefd ecdB | AFdF E2EG | FAAd Bdef | dBAF D2D |]",
    source: { ...SOURCE, where: "p. 118 (PDF page 130)" },
    transcription: "read from the scan (PDF page 130, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p70-bonny-lass-of-fisherrow",
    title: "Bonny Lass of Fisherrow",
    region: "scottish",
    kind: "reel",
    key: "C",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the first strain is repeated, the second printed once in full, as printed; two small marks on the staff lines before bar 7 are printing specks, not a repeat sign",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Bonny Lass of Fisherrow\nM:C|\nL:1/8\nK:C\nA | GEcG AcGE | CEGE D/D/D A2 | GEGc AFAc | BdGB c/c/c c :|\nf | ecgc egca | gcec Bddf | ecgc egca | gede c/c/c cf |\necgc egca | gcec Bddf | ecGc Acfa | gede c/c/c c |]",
    source: { ...SOURCE, where: "p. 70 (PDF page 82)" },
    transcription: "read from the scan (PDF page 82, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p43-little-donalds-wife",
    title: "Little Donald's Wife",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "minor",
    meter: "C|",
    origin: "Scottish reel, Gaelic title An gabh thu bean, a Dho'ill bhig; both strains repeated, as printed; each strain closes on G natural",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Little Donald's Wife\nM:C|\nL:1/8\nK:Am\nA | EAA^G ABcA | EAA^G A2 A3/2^G/ | EAA^G ABce | dcBA G2G :|\n|: B | c2ec dcBG | c2ec A2 A3/2B/ | cBcd e^fge | dcBA G2G :|",
    source: { ...SOURCE, where: "p. 43 (PDF page 55)" },
    transcription: "read from the scan (PDF page 55, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p93-the-lads-of-foss",
    title: "The Lads of Foss",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel; the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:The Lads of Foss\nM:C|\nL:1/8\nK:D\nA | FA A/A/A B2AB | dBAF GEEG | FA A/A/A B2Ag | fdef d/d/d d :|\ng | f2df aeeg | f2df ecAg | f2df aeeg | fdef d/d/d dg |\nf2df aeeg | f2df ecAg | fefg aeeg | fdef d/d/d d |]",
    source: { ...SOURCE, where: "p. 93 (PDF page 105)" },
    transcription: "read from the scan (PDF page 105, each staff in parts at 600 dpi, doubtful heads at 1200 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-02",
  },
  {
    id: "athole-p60-cabar-feidh",
    title: "Cabar Feidh",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "dorian",
    meter: "C|",
    origin: "Scottish reel, Gaelic title Cabar Feidh (the deer's antlers), printed first under the book's heading Tunes in C major; printed with no key signature and ending on D, with C sharp as an accidental; each strain printed once, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Cabar Feidh\nM:C|\nL:1/8\nK:Ddor\nG | c2ed c2GB | c2GF ECCE | Ddd^c d2Ac | d2AG FDDB |\nc2ed c2GB | cGAF ECCE | DEFG ABcA | d2AG FDD ||\nf | ecgc acgc | ecgc ecce | fdad bdad | fgag fddf |\necgc acgc | GAcd eccg | afge fdf^c | d2AG FDD |]",
    source: { ...SOURCE, where: "p. 60 (PDF page 72)" },
    transcription: "read from the scan (PDF page 72, each staff in halves at 500 dpi, doubtful heads at 800 to 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p58-cutting-ferns",
    title: "Cutting Ferns",
    region: "scottish",
    kind: "strathspey",
    key: "A",
    mode: "minor",
    meter: "C",
    origin: "Scottish strathspey, marked Very old, Slow Strathspey, printed under the book's A minor heading; both strains repeated, as printed",
    tags: ["highlands",  "strathspey",  "dance",  "slow",  "scottish"],
    abc: "X:1\nT:Cutting Ferns\nM:C\nL:1/8\nK:Am\nB | A/A3/2 a2 g/e3/2 g2 | e3/2d/ B3/2A/ G3/2A/ B3/2G/ | A/A3/2 a2 g/e3/2 g2 | e3/2d/ B3/2g/ B/A3/2 A :|\n|: g | e3/2d/ B3/2A/ G3/2A/ B3/2G/ | e3/2d/ B3/2A/ B2 B3/2g/ | e3/2d/ B3/2A/ G3/2A/ B3/2d/ | e3/2d/ g3/2B/ A2 A :|",
    source: { ...SOURCE, where: "p. 58 (PDF page 70)" },
    transcription: "read from the scan (PDF page 70, each staff in thirds at 600 dpi with every note head placed against the staff lines by measurement, doubtful rhythms at 1000 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p66-argyle-bowling-green",
    title: "Argyle Bowling Green",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "dorian",
    meter: "C|",
    origin: "Scottish reel, printed under the book's C major heading with no key signature; the first strain ends on low D and the second on D above, so it is named D dorian here; the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Argyle Bowling Green\nM:C|\nL:1/8\nK:Ddor\nE | C2c2 cded | cdcA G=FED | C2c2 cded | cBcE D3 :|\nc | GEcE GEEA | GEcE G2GA | GEcE GEE=F | GAGE D2Da |\ngec'e geea | gec'e g2ga | gec'e geef | gage d2d |]",
    source: { ...SOURCE, where: "p. 66 (PDF page 78)" },
    transcription: "read from the scan (PDF page 78, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, high notes and doubtful heads at 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p66-double-kisses",
    title: "Double Kisses",
    region: "scottish",
    kind: "reel",
    key: "C",
    mode: "major",
    meter: "C|",
    origin: "Reel, here in a Scottish collection under its C major heading; the first strain is repeated, the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Double Kisses\nM:C|\nL:1/8\nK:C\ne | c2GE c2de | c2GE dDDe | c2GE cdec | fagf ec c :|\ne/f/ | gcge gcce/f/ | gcge add e/f/ | gcge afge | fagf ecce/f/ |\ngcge gcce/f/ | gcge add f/g/ | aege fdec | Aagf ec c |]",
    source: { ...SOURCE, where: "p. 66 (PDF page 78)" },
    transcription: "read from the scan (PDF page 78, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, doubtful heads at 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p63-fight-about-the-fireside",
    title: "Fight about the Fireside",
    region: "scottish",
    kind: "reel",
    key: "C",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, printed under the book's C major heading; the first strain is repeated and the second printed once in full; the print returns to the sign at the first bar after the second strain, and the tune is written here once through",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Fight about the Fireside\nM:C|\nL:1/8\nK:C\nc | GcEc Addc | GcEc GcEc | FcEc DddB | cGAF ECC :|\nf | ecgc eddf | ecgc acgc | fage d=cde | GAcd e2df |\necgc eddf | ecgc acge | fage d=cde | GAcd e2dc |]",
    source: { ...SOURCE, where: "p. 63 (PDF page 75)" },
    transcription: "read from the scan (PDF page 75, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, doubtful heads at 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p63-marquis-of-queensberry",
    title: "Marquis of Queensberry",
    region: "scottish",
    kind: "reel",
    key: "C",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, printed under the book's C major heading; the first strain is repeated and the second printed once in full; the print returns to the sign at the first bar after the second strain, and the tune is written here once through",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Marquis of Queensberry\nM:C|\nL:1/8\nK:C\nf | ec c/c/c c2ec | fedc Bagf | ec c/c/c c2ac | BGAB c3 :|\nG | EFGE F2Ac | BcdB c2eg | afaf gedc | BGAB c2cG |\nDEGE FGAc | BcdB cdeg | afaf gedc | BGAB cagf |]",
    source: { ...SOURCE, where: "p. 63 (PDF page 75)" },
    transcription: "read from the scan (PDF page 75, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, doubtful rhythms at 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p87-lassie-look-behind-ye",
    title: "Lassie look behind ye",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, printed under the book's D major heading; both strains repeated, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Lassie look behind ye\nM:C|\nL:1/8\nK:D\nB | ADFD EB,B,B | AD F/G/A d2 d3/2f/ | gfed eBBd | FD F/G/A d2 d :|\n|: f | dg f/g/a beef | dg f/g/a fdec | dBAF EFGA | FD F/G/A d2 d :|",
    source: { ...SOURCE, where: "p. 87 (PDF page 99)" },
    transcription: "read from the scan (PDF page 99, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, the low notes and doubtful heads at 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p84-the-swallow",
    title: "The Swallow",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, printed under the book's D major heading; the first strain is repeated, and the second strain has two-bar first and second time endings, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:The Swallow\nM:C|\nL:1/8\nK:D\nA | FD F/G/A d2 d3/2g/ | f2 d3/2f/ eEEA | FD F/G/A d2 d3/2g/ | faef dDD :|\n|: g | fefg aeeg | fdgf e3/2E/ E3/2g/ |1 fefg aeeg | fdec dDD :|2 fefg abag | fdec dDD |]",
    source: { ...SOURCE, where: "p. 84 (PDF page 96)" },
    transcription: "read from the scan (PDF page 96, each staff in thirds at 600 dpi with note heads placed against the staff lines by measurement, doubtful heads at 700 to 900 dpi) and proofed bar by bar by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p84-an-gearran",
    title: "An Gearran",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, Gaelic title An Gearran (the garron, a small Highland horse); marked J. S. R., the compiler James Stewart-Robertson's own tune; the first strain is repeated, and the second has two-bar first and second time endings, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:An Gearran\nM:C|\nL:1/8\nK:D\nA | FAAc d2AG | FAAF GEEG | FAAc d2Ag | faef dDD :|\n|: g | fdfg a2gf | edef gfeg |1 fdfg a2fa | bgeg fdd :|2 fdaf bgeg | faef dDD |]",
    source: { ...SOURCE, where: "p. 84 (PDF page 96)" },
    transcription: "read from the scan (PDF page 96, each staff in thirds at 600 dpi, then proofed bar by bar at 900 dpi with every note head placed against staff lines fitted across the bar) by lane MELODIES200 reader athole-a, 2026-10-03",
  },
  {
    id: "athole-p90-charlie-stewart",
    title: "Charlie Stewart",
    region: "scottish",
    kind: "reel",
    key: "D",
    mode: "major",
    meter: "C|",
    origin: "Scottish reel, printed under the book's D major heading; the first strain is repeated and the second printed once in full, as printed",
    tags: ["highlands",  "reel",  "dance",  "scottish"],
    abc: "X:1\nT:Charlie Stewart\nM:C|\nL:1/8\nK:D\nB | AFED G3B | AFED E3B | AFED GABd | AGFE D2D :|\nA | defd gfec | defd ecBA | defd gfeg | f/g/a ef d3A |\ndefd gfec | defa ecBA | defd gfeg | faef d2d |]",
    source: { ...SOURCE, where: "p. 90 (PDF page 102)" },
    transcription: "read from the scan (PDF page 102, each staff in thirds at 600 dpi, then proofed bar by bar at 900 dpi with every note head placed against staff lines fitted across the bar, doubtful rhythms checked by eye at 900 dpi) by lane MELODIES200 reader athole-a, 2026-10-03",
  },
];

export default TUNES;
