// settle-hear · tunes/bunting - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// The book is a piano setting in harp style: each melody is the top line of the right hand (the top note of
// any chord). The book has two paginations: four pages of introductory specimens (PDF pages 127 to 130),
// then the main collection, where PDF page = printed page + 130.

export const SOURCE = {
  kind: 'print',
  book: 'The Ancient Music of Ireland, arranged for the piano forte',
  compiler: 'Edward Bunting (1773-1843)',
  year: 1840,
  scan: 'https://archive.org/details/ancientmusicofir00bunt',
};

const READ = (pdf) => `read from the scan (PDF page ${pdf}, each staff in thirds at 600 to 1200 dpi) and proofed bar by bar by lane MELODIES200 reader bunting, 2026-10-03`;

export const TUNES = [
  {
    id: 'bunting1840-p1-lamentation-of-dierdre-for-the-sons-of-usneach',
    title: 'Lamentation of Dierdre for the Sons of Usneach',
    region: 'irish',
    kind: 'lament',
    key: 'Em', mode: 'minor', meter: '3/4',
    origin: 'Irish air from the introductory specimens of the oldest class, No. II, marked Very Ancient, Moderately Quick, "The Air repeated to each Stanza of the Poem"; Bunting gives it as the air to which the lament of Deirdre over the sons of Usnach was still sung. Printed as two strains of eight bars; read as printed, signature of one sharp, ending on E',
    tags: ['air', 'slow', 'lament', 'ancient', 'irish'],
    abc: 'X:1\nT:Lamentation of Dierdre for the Sons of Usneach\nM:3/4\nL:1/8\nK:Em\nG2 D2 E3/2A/ | G2 G2 G2 | c2 B2 A3/2G/ | B2 A2 B3/2A/ |\nc2 B2 B3/2A/ | z2 G3/2E/ G2 | G2 G2 G3/2B/ | A2 A2 G3/2E/ ||\nG2 D2 E3/2A/ | G2 G2 G2 | c2 B2 A3/2G/ | B2 A2 c3/2d/ |\nc2 B2 B3/2c/ | B2 A3/2E/ G2 | G2 G2 G3/2B/ | A2 A2 G3/2E/ |]',
    source: { ...SOURCE, where: 'introductory specimens, No. II, p. 1 (PDF page 127)' },
    transcription: READ(127),
  },
  {
    id: 'bunting1840-p4-did-you-see-the-black-rogue',
    title: 'Did you see the black rogue',
    region: 'irish',
    kind: 'song-air',
    key: 'A', mode: 'major', meter: '6/8',
    origin: 'Irish air, Irish title An bhfeaca tu an stuadhaire dubh (printed in Gaelic type in the index); No. 6, marked Very Ancient, Author and date unknown, Brisk and Lively; Bunting had it from H. Higgins, harper. Three strains of eight bars; grace notes left out',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:2\nT:Did you see the black rogue\nM:6/8\nL:1/8\nK:A\nE | A A/B/c/A/ Bce | ABc e2 a | A A/B/c/A/ Bce | B2 A A2 E |\nA A/B/c/A/ Bce | ABc e2 a | A A/B/c/A/ Bce | B2 A A2 ||\nefg a2 b | a2 b agf | ece f2 a | f2 a fec | efg agf | ece fga |\nA A/B/c/A/ Bce | B2 A A2 || e | efg aAa | aAa a/b/a/g/ f | c/B/c/e/c/e/ fAa |\nfFf f/g/f/e/ c | efg aAa | ece fga | A A/B/c/e/ abc' | B2 A A z |]",
    source: { ...SOURCE, where: 'No. 6, p. 4 (PDF pages 134 and 135)' },
    transcription: READ('134 and 135'),
  },
  {
    id: 'bunting1840-p5-the-blackbird-and-the-hen',
    title: 'The Blackbird and the Hen',
    region: 'irish',
    kind: 'song-air',
    key: 'A', mode: 'major', meter: '6/8',
    origin: 'Irish air, Irish title An londubh agus an cheirseach (in the index); No. 7, marked Very Ancient, Author and date unknown, In moderate time. The top line is read as printed, so the harp-style octave notes above the melody (d\' and c\' in bar 5, b in bars 6 to 8, c\' and b in bar 13, a in bar 14) are kept; the G natural in bar 9 is printed. Grace notes left out',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:3\nT:The Blackbird and the Hen\nM:6/8\nL:1/8\nK:A\ne/d/ | ccd BBc | AA B/c/ d2 B | fdB c/d/ e B | BAA A2 e/d/ |\ncc d' BB c' | AA B/c/ d2 b | fdB c/d/ e b | baa a2 d/c/ |\ndef =g e d/c/ | de f/^g/ a2 a | gee dBA | Bee e2 e/d/ |\nc' c/e/d/c/ b B/d/c/B/ | a A/B/c/A/ d2 B | f e/d/c/B/ c/d/e/c/d/B/ | BAA A2 |]",
    source: { ...SOURCE, where: 'No. 7, p. 5 (PDF page 135)' },
    transcription: READ(135),
  },
  {
    id: 'bunting1840-p20-the-jolly-ploughman',
    title: 'The Jolly Ploughman',
    region: 'irish',
    kind: 'song-air',
    key: 'E', mode: 'major', meter: '6/8',
    origin: 'Irish air, Irish title An t-oireamh sugach (in the index); No. 23, marked Very Ancient, Author and date unknown, Brisk and Lively; printed with English words beginning "\'Twas Jack the jolly ploughboy" and a chorus to the syllables "Too-ran-nan". Melody read as the top note of the right hand, words left out',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:4\nT:The Jolly Ploughman\nM:6/8\nL:1/8\nK:E\nE | E2 G G2 B | A3 F2 B | E2 G B2 B | B3- B2 G |\nA2 A F2 F | G3 E2 E | F2 F D2 D | E3 E2 :|\nB | B2 e e2 c | c2 B B2 G | B2 e e2 c | c3 B2 B |\nB2 e e2 c | c2 B B2 G | G F E F2 G | B2 A G2 F ||\nE C B, E2 E | E3 E2 G | F E C F2 F | F3 F G A |\nB A G B A G | e e B c B G | E C B, E2 E | E3 E2 |]",
    source: { ...SOURCE, where: 'No. 23, p. 20 (PDF page 150)' },
    transcription: READ(150),
  },
  {
    id: 'bunting1840-p106-achil-air',
    title: 'Achil Air',
    region: 'irish',
    kind: 'air',
    key: 'Bb', mode: 'major', meter: '3/4',
    origin: 'Irish air from Achill, Co. Mayo; No. 145, marked Very Ancient, Author and date unknown, Very Plaintive. Signature of two flats, ending on B flat, with the A flattened by printed accidentals in bars 2, 4, 6 and 14 and a printed natural in bar 11, and D flat in bar 13. The first strain is printed once and the second between repeat signs; trills left out',
    tags: ['air', 'slow', 'ancient', 'irish'],
    abc: "X:6\nT:Achil Air\nM:3/4\nL:1/8\nK:Bb\nF BB | B3 B cB | _A3 A AG | F3 E FG | _A3 F BB |\nB3 B cB | _A3 A AG | F3 E C3/2B,/ | B,2- B, ||\n|: F FF | F3 F GF | F3 F FF | G3 F G=A | B3 B BB |\n_d3 d dc | cB B_A FE | F3 E C3/2B,/ | B,2- B, :|",
    source: { ...SOURCE, where: 'No. 145, p. 106 (PDF page 236)' },
    transcription: READ(236),
  },
  {
    id: 'bunting1840-p108-the-gentle-maiden',
    title: 'The Gentle Maiden',
    region: 'irish',
    kind: 'air',
    key: 'Eb', mode: 'major', meter: '6/8',
    origin: 'Irish air; No. 148, marked Very Ancient, Author and date unknown, Very Slow and with great Expression. Both strains printed between repeat signs; trills and grace notes left out. As printed, the falling D C B figure is dotted in bar 1 and even in bars 5 and 13',
    tags: ['air', 'slow', 'ancient', 'irish'],
    abc: "X:7\nT:The Gentle Maiden\nM:6/8\nL:1/8\nK:Eb\nD | E3/2F/E D3/2C/B, | B3 c3/2d/e | B3/2A/G F2 E | C3- C2 D |\nE3/2F/E DCB, | B3 c3/2d/e | B3/2A/G F2 E | E3- E2 :|\n|: B | B3/2c/d e2 e | e3 e3/2d/c | B3/2A/G F2 E | C3- C2 D |\nE3/2F/E DCB, | B3 c3/2d/e | B3/2A/G F2 E | E3- E2 :|",
    source: { ...SOURCE, where: 'No. 148, p. 108 (PDF page 238)' },
    transcription: READ(238),
  },
  {
    id: 'bunting1840-p100-spinning-wheel-song-1-sung-by-women',
    title: 'Spinning Wheel Songs, 1st, sung by women',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '6/8',
    origin: 'Irish spinning wheel song, Irish title An luibhin (in the index); No. 134, the first of three spinning wheel songs printed together, marked Very Ancient, Author and date unknown, In moderate time, "1st sung by women". One six-bar strain ending with a double bar; the D flat in bar 3 is printed',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:8\nT:Spinning Wheel Songs, 1st, sung by women\nM:6/8\nL:1/8\nK:Eb\nEGB e2 f | gee e2 B | Bc_d cBG | BeG B2 c | BGE G2 F | GEE E2 z |]",
    source: { ...SOURCE, where: 'No. 134, p. 100 (PDF page 230)' },
    transcription: READ(230),
  },
  {
    id: 'bunting1840-p37-take-my-love',
    title: 'Take My Love',
    region: 'irish',
    kind: 'song-air',
    key: 'F#m', mode: 'minor', meter: '2/4',
    origin: 'Irish air, Irish title Beir mo ghradh (in the index, translated "Take my love to that young man"); No. 48, marked Author and date unknown, With Spirit. Signature of three sharps; the air opens around A and ends on F sharp, so it is named F sharp minor here. Turns left out',
    tags: ['air', 'irish'],
    abc: "X:9\nT:Take My Love\nM:2/4\nL:1/8\nK:F#m\nA3/2B/ cc | dB cc | A3/2B/ ce | dB B2 | A3/2B/ cc | dB cc | AA e d/c/ |\nBA G3/2A/ | FF F3/2G/ | EE AE | FF F G/F/ | EE A2 |\nFF F G/F/ | EE AE | A3/2B/ cB | AG F2 |]",
    source: { ...SOURCE, where: 'No. 48, p. 37 (PDF page 167)' },
    transcription: READ(167),
  },
  {
    id: 'bunting1840-p29-the-hornless-cow',
    title: 'The Hornless Cow',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '6/8',
    origin: 'Irish air, Irish title Bo mhaol (in the index); No. 37, marked Very Ancient, Author and date unknown, With spirit. Three strains, each repeated; the third strain repeats the melody of the second over a bass marked very soft, and is written out as printed',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:10\nT:The Hornless Cow\nM:6/8\nL:1/8\nK:Eb\nB2 c d2 B | e3 e2 e | B2 c d2 B | e2 e e3 |\ng2 f g2 e | f2 d B2 A | G2 A G2 F | G2 E E3 :|\n|: E3 F2 G | E3 E3 | E3 F2 A | G2 E E3 |\nE3 F2 G | E3 E3 | e3 B2 A | G2 E E3 :|\n|: E3 F2 G | E3 E3 | E3 F2 A | G2 E E3 |\nE3 F2 G | E3 E3 | e3 B2 A | G2 E E3 :|",
    source: { ...SOURCE, where: 'No. 37, p. 29 (PDF page 159)' },
    transcription: READ(159),
  },
  {
    id: 'bunting1840-p103-i-will-pay-them-yet',
    title: 'I will pay them yet',
    region: 'irish',
    kind: 'slip-jig',
    key: 'A', mode: 'major', meter: '9/8',
    origin: 'Irish air in nine-eight; No. 141, marked Author and date unknown, With Spirit. Two strains of four bars, each repeated',
    tags: ['jig', 'slip-jig', 'dance', 'irish'],
    abc: "X:11\nT:I will pay them yet\nM:9/8\nL:1/8\nK:A\nA | ccc dBA GE A/B/ | ccc dBG A2 z | ccc dBA GEC | DEF GEG A2 :|\n|: A | GEE FED CB,A, | CDE EFG A2 A | GEE FED CB,A, | ccc dBG A2 :|",
    source: { ...SOURCE, where: 'No. 141, p. 103 (PDF page 233)' },
    transcription: READ(233),
  },
  {
    id: 'bunting1840-p14-rose-connolly',
    title: 'Rose Connolly',
    region: 'irish',
    kind: 'song-air',
    key: 'E', mode: 'major', meter: '6/8',
    origin: 'Irish air; No. 14, marked Author and date unknown, A little Quick. Read as the top line of the right hand, so the sixteenth in bar 3 is the f sharp printed above the A, where bar 7 has the A alone; grace notes left out',
    tags: ['air', 'irish'],
    abc: "X:12\nT:Rose Connolly\nM:6/8\nL:1/8\nK:E\nE/F/ | B2 B G3/2A/B | c3 cBA | G3/2f/F E2 E | E3 E2 E/F/ |\nB2 B G3/2A/B | c3 cBA | G3/2A/F E2 E | E3 Bcd |\neBG Bcd | e3 cBA | B3/2G/F G3/2E/C | E3 G3/2A/B |\nc2 c c3/2B/A | B2 c/B/ G2 E | C3/2B,/C E2 E | E3 E2 |]",
    source: { ...SOURCE, where: 'No. 14, p. 14 (PDF page 144)' },
    transcription: READ(144),
  },
  {
    id: 'bunting1840-p28-maguires-lamentation',
    title: "Maguire's Lamentation",
    region: 'irish',
    kind: 'lament',
    key: 'Eb', mode: 'major', meter: '3/4',
    origin: 'Irish lament; No. 36, marked Very Ancient, Author and date unknown, In a mournful manner but not slow. Two strains of four bars; grace notes and turns left out',
    tags: ['air', 'slow', 'lament', 'ancient', 'irish'],
    abc: "X:13\nT:Maguire's Lamentation\nM:3/4\nL:1/8\nK:Eb\nB, B,/C/ E E/F/ G2 | GFEF F2 | E2 E3/2F/ E3/2C/ | E2 C3/2B,/ B,2 ||\nB, B,/C/ E E/F/ G2 | GFEF F2 | E2 E3/2F/ G3/2F/ | E2 E3/2F/ E2 |]",
    source: { ...SOURCE, where: 'No. 36, p. 28 (PDF page 158)' },
    transcription: READ(158),
  },
  {
    id: 'bunting1840-p46-give-me-your-hand',
    title: 'Give Me Your Hand',
    region: 'irish',
    kind: 'air',
    key: 'G', mode: 'major', meter: '6/8',
    origin: 'Irish harp tune, Irish title Tabhair dom do lamh; No. 63, marked "By Rory Dall O\'Caghan about 1603", Moderately Quick. Read as the top line of the right hand, so the octave doublings Bunting writes above the melody in bars 7 to 10 and 17 to 21 are kept as printed; the natural on f in bar 23 is printed; staccato marks and slurs left out',
    tags: ['air', 'ancient', 'irish'],
    abc: "X:14\nT:Give Me Your Hand\nM:6/8\nL:1/8\nK:G\nD | EGG G2D | EGG G2D | EGG GAB | Bed B2 A/G/ |\nAAe BBd | A A/B/A/G/ E2D | EGG g2D | EGG g2D |\nEGG gab | d d/b/a/b/ g2G | EGG GAB | Bed B2 A/G/ |\nAAe BBd | AA B/d/ e2 d/B/ | dde g2 e/d/ | eeg a2 g/e/ |\ngg d/e/ gg d/e/ | gga b3 | bbb b2 a/g/ | a/g/a/b/a/b/ a2 g/f/ | ee g/e/ dd e/d/ |\nBB d/B/ A2G | GG B/d/ =f2 e/d/ | eeg e2 d/B/ | ddg BBd | A c/B/A/G/ G2 |]",
    source: { ...SOURCE, where: 'No. 63, pp. 46 and 47 (PDF pages 176 and 177)' },
    transcription: READ('176 and 177'),
  },
  {
    id: 'bunting1840-p58-odonnells-march',
    title: "O'Donnell's March",
    region: 'irish',
    kind: 'march',
    key: 'Bb', mode: 'major', meter: '3/8',
    origin: 'Irish march; No. 80, marked Very Ancient, Author and date unknown, Lively and Spirited. Three strains of eight bars; read as the top line of the right hand, so where the inner voice and the melody share a note (bar 22) the shared note is kept. The A flat in bar 5 is printed. Staccato marks and slurs left out',
    tags: ['march', 'dance', 'ancient', 'irish'],
    abc: "X:15\nT:O'Donnell's March\nM:3/8\nL:1/8\nK:Bb\nBBF | BBF | B B/c/d/e/ | f2 z | g_a g/f/ | gfe | dB c/d/ | c2 z ||\nAcc | cde | dcB | def | fed | dcB | c B/c/ d | F2 z ||\ne c/d/e/c/ | dcB | e c/d/e/c/ | dcB | dff | Fed | c c/B/c/d/ | B2 z |]",
    source: { ...SOURCE, where: 'No. 80, p. 58 (PDF page 188)' },
    transcription: READ(188),
  },
  {
    id: 'bunting1840-p67-patricks-day',
    title: "Patrick's Day",
    region: 'irish',
    kind: 'march',
    key: 'A', mode: 'major', meter: '6/8',
    origin: "Irish tune; No. 91, marked Author and date unknown, Quick. Bunting gives no kind; the tune is the one known as St Patrick's Day, played as a march and a set dance. A strain of eight bars and a strain of fourteen, each ending with a double bar; staccato marks and slurs left out",
    tags: ['march', 'dance', 'irish'],
    abc: "X:16\nT:Patrick's Day\nM:6/8\nL:1/8\nK:A\nABA Acd | efe ecA | cBc AFE | FGF F2E | ABA Acd | efe ecA | cBc AFE | F2G A2z ||\nefg a2f | g2e f2d | efg a2f | g2e f3 | efg agf | gfe fga | ecA Acd |\neaf ecA | cBc AFE | FGF F2E | ABA Acd | eaf ecA | cBc AFE | F2G A2z |]",
    source: { ...SOURCE, where: 'No. 91, p. 67 (PDF page 197)' },
    transcription: READ(197),
  },
  {
    id: 'bunting1840-p76-the-miners-of-wicklow',
    title: 'The Miners of Wicklow',
    region: 'irish',
    kind: 'jig',
    key: 'F', mode: 'major', meter: '6/8',
    origin: 'Irish tune; No. 102, marked Author and date unknown, Very Quick and Animated. Two strains of eight bars, each with a pickup and repeated; staccato marks and slurs left out',
    tags: ['jig', 'dance', 'irish'],
    abc: "X:17\nT:The Miners of Wicklow\nM:6/8\nL:1/8\nK:F\nF | ABc cde | dBd cAc | dBG GBG | cAF FAF | ABc cde | dBd cAc | def gec | f3 f2 :|\n|: b | afa afa | geg geg | afa afa | bgb bgb | afa afa | gec cfe | def gec | f3 f2 :|",
    source: { ...SOURCE, where: 'No. 102, p. 76 (PDF page 206)' },
    transcription: READ(206),
  },
  {
    id: 'bunting1840-p86-is-it-the-priest-you-want',
    title: 'Is it the Priest you want?',
    region: 'irish',
    kind: 'jig',
    key: 'G', mode: 'major', meter: '6/8',
    origin: 'Irish air; No. 116, marked Very Ancient, Author and date unknown, Lively and Quick; Bunting had it at Ballinrobe in 1792. Two strains, each with a pickup and repeated. The small grace notes are left out; the two thirty-second notes before the dotted a in bars 9 and 13 are printed full size in the beam and are kept',
    tags: ['jig', 'dance', 'ancient', 'irish'],
    abc: "X:18\nT:Is it the Priest you want?\nM:6/8\nL:1/8\nK:G\ne | edB d2B | d2B B2e | edB d2B | c2A A2e | edB d2B | d2B B2e | edB gfg | B2G G2 :|\n|: f | g2g f/4g/4a3/2f | g2e e2e | a2a a3/2g/a | b2e e2f | g2g f/4g/4a3/2f | g2e e2e | edB gfg | B2G G2 :|",
    source: { ...SOURCE, where: 'No. 116, p. 86 (PDF page 216)' },
    transcription: READ(216),
  },
];

export default TUNES;
