// settle-hear · tunes/fraser1816 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
//
// Book: Simon Fraser of Knockie, The Airs and Melodies Peculiar to the Highlands of Scotland and the Isles,
// Edinburgh 1816. Voice or violin over a figured bass: the top staff only is read, and the top note of any
// double stop. Grace notes, trills, slurs and dynamics are left out. Printed page = PDF page - 8.

export const SOURCE = {
  kind: 'print',
  book: 'The Airs and Melodies Peculiar to the Highlands of Scotland and the Isles',
  compiler: 'Captain Simon Fraser of Knockie',
  year: 1816,
  scan: 'https://archive.org/details/airsmelodiespecu00fras',
};

const READ = 'proofed bar by bar by lane MELODIES200 reader fraser1816, 2026-10-02';

export const TUNES = [
  {
    id: 'fraser-104-the-boat-of-my-lover',
    title: 'The Boat of my Lover',
    region: 'scottish',
    kind: 'song-air',
    key: 'Bb', mode: 'major', meter: '3/4',
    origin: 'Gaelic song air, printed title Fhir a bhata; marked Slow & Plaintive. The treble has a stray bar line inside bar 11 that the bass does not share; bar 11 is written as one bar, as the bass counts it',
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: 'X:1\nT:The Boat of my Lover\nM:3/4\nL:1/8\nK:Bb\nF3/2G/ | B2 g2 f3/2F/ | G2 B2 B3/2F/ | G2 B2 B3/2F/ | G2 B2 f3/2=e/ |\nf2 g2 fe | d2 g2 f3/2e/ | d2 f3/2d/ c2 | B4 :: d3/2c/ |\nB4 d3/2F/ | G2 B2 g3/2f/ | f4 f3/2c/ | d2 f2 b3/2a/ |\ng2 f3/2d/ B3/2F/ | G2 B2 d3/2c/ | d2 f3/2d/ c2 | B6 |]',
    source: { ...SOURCE, where: 'No. 104, p. 50 (PDF page 58)' },
    transcription: 'read from the scan (PDF page 58, each staff in halves at 300 dpi, doubtful notes at 600 to 900 dpi) and ' + READ,
  },
  {
    id: 'fraser-039-short-apron',
    title: 'Short Apron',
    region: 'scottish',
    kind: 'song-air',
    key: 'C', mode: 'major', meter: '3/4',
    origin: "Gaelic air, printed title N't aparan goirid; marked Slow and headed Antient Simple Sett. The lower notes of the violin double stops and the grace notes are left out; the lead-in after the pause in bar 28 is printed as two demisemiquavers and a semiquaver",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:Short Apron\nM:3/4\nL:1/8\nK:C\nG/A/B | c3 d e d | c2 G2 GA | _B3 d c B | A4 G/A/=B | c3 d e3/2d/ | c2 G2 B2 | c B c d e f | g4 c'2 |\ng2 f2 e2 | d2 c2 B2 | c2 B2 A2 | G4 z g/f/ | e f g a b c' | g2 e2 c/d/e/f/ | e3 f d2 | c4 :: c3/2d/ |\ne2 c2 d2 | c2 G2 GA | _B3 d c B | A4 c3/2d/ | e2 c2 d2 | c2 G2 B2 | c B c d e f | g4 a/b/c' |\ng2 f2 e2 | d2 c2 B2 | c2 B2 A2 | G4 z c/4B/4A/ | G2 F3/2E/ F A | G3 g a f | e3 f d2 | c4 |]",
    source: { ...SOURCE, where: 'No. 39, p. 24 (PDF page 32)' },
    transcription: 'read from the scan (PDF page 32, each staff in fifths at 700 dpi, doubtful bars at 1000 dpi) and ' + READ,
  },
  {
    id: 'fraser-101-the-poets-grave',
    title: "The Poet's Grave",
    region: 'scottish',
    kind: 'lament',
    key: 'A', mode: 'major', meter: '3/4',
    origin: 'Gaelic air, printed title Uaigh a Bhaird; marked Solemnly Slow. The violin part is set in double and triple stops: the top note of each is read, and the grace notes are left out',
    tags: ['highlands', 'air', 'slow', 'lament', 'scottish'],
    abc: "X:1\nT:The Poet's Grave\nM:3/4\nL:1/8\nK:A\nE6 | A6 | F3 E F G | A4 F E | E6 | c4 e2 | B3 A B c | A6 ::\ne4 d2 | c4 B2 | A3 B c ^d | e4 F E | E6 | c4 e2 | B3 A B c | A6 |]",
    source: { ...SOURCE, where: 'No. 101, p. 49 (PDF page 57)' },
    transcription: 'read from the scan (PDF page 57, each staff in quarters at 650 dpi, chords at 1000 dpi) and ' + READ,
  },
  {
    id: 'fraser-027-air-to-which-ossian-is-recited',
    title: 'Air to which Ossian is recited',
    region: 'scottish',
    kind: 'air',
    key: 'D', mode: 'minor', meter: '2/4',
    origin: 'Gaelic title Dan Ossian, headed Fingalian Air; marked Very Slow; communicated by Sir John Sinclair, Bart. The lower notes of the violin double stops and the grace notes are left out. The print notes that the high octave may be introduced with good effect in the second strain',
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:Air to which Ossian is recited\nM:2/4\nL:1/8\nK:Dm\nF F F3/2G/ | A G F2 | G G d3/2^c/ | d =c/B/ B2 | B B d3/2c/ | c A A2 | F F G3/2A/ | F3/2E/ D2 :|\n|: A d d3/2^c/ | A =c d2 | F F d3/2c/ | B3/2c/4B/4 A2 | F F d3/2c/ | c A A2 | F F G3/2A/ | F3/2E/ D2 :|",
    source: { ...SOURCE, where: 'No. 27, p. 19 (PDF page 27)' },
    transcription: 'read from the scan (PDF page 27, each staff in fifths at 750 dpi with the staff lines named, doubtful bars at 1200 dpi) and ' + READ,
  },
  {
    id: 'fraser-046-maiden-fond-of-mirth',
    title: 'Maiden fond of Mirth',
    region: 'scottish',
    kind: 'song-air',
    key: 'A', mode: 'minor', meter: '4/4',
    origin: "Gaelic song air, printed title Nian doun an t' Sugridh; marked Moderately Slow. Printed with no key signature. The lower notes of the violin double stops, the grace notes and the small turn figures between E and G are left out",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:Maiden fond of Mirth\nM:C\nL:1/8\nK:Am\nB | c2 B3/2A/ A2 Bd | e2 d3/2B/ A2 d3/2c/ | B2 AG E2 G3/2E/ | D2 EG A2 AB |\nc2 d3/2c/ B2 AB | e2 d3/2B/ A2 d3/2c/ | B2 AG E2 G3/2E/ | D2 EG A2 A ||\nB | c2 d3/2c/ B2 g3/2f/ | ef g3/2B/ A2 d3/2c/ | B2 dD E2 G3/2E/ | D2 EG A2 AG |\nG3/2B/ c3/2c/ c2 c3/2d/ | e3/2c/ d3/2B/ G2 AB | g2 e3/2G/ E2 G3/2E/ | D2 EG A2 A |]",
    source: { ...SOURCE, where: 'No. 46, p. 26 (PDF page 34)' },
    transcription: 'read from the scan (PDF page 34, each staff in fifths at 750 dpi with the staff lines named, doubtful notes at 1100 to 1200 dpi) and ' + READ,
  },
  {
    id: 'fraser-075-small-is-my-inclination-to-sleep',
    title: 'Small is my Inclination to Sleep',
    region: 'scottish',
    kind: 'song-air',
    key: 'G', mode: 'major', meter: '3/4',
    origin: "Gaelic song air, printed title S' beag mo shund ris a chadal; marked Slow & Plaintive. The lower notes of the double stops, the grace notes and the small notes closing the trills are left out. The second strain is written out in full in the print",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:Small is my Inclination to Sleep\nM:3/4\nL:1/8\nK:G\ng3/2a/ | b4 a3/2g/ | f2 d2 g3/2f/ | e2 ^d2 e2 | G2 FE d2 | g3 e dB | e2 dB A2 | G4 :|\nG3/2A/ | B4 B/A/B/c/ | B2 e2 d3/2c/ | B4 AG | F2 E2 e3/2f/ | g4 g/a/g/f/ | e2 B2 B^A | B4 G3/2A/ |\nB4 B/A/B/c/ | B2 e2 d3/2c/ | B4 AG | F2 E2 g3/2a/ | b4 a3/2g/ | b2 a3/2g/ f2 | e6 |]",
    source: { ...SOURCE, where: 'No. 75, p. 37 (PDF page 45)' },
    transcription: 'read from the scan (PDF page 45, the sharp mask layer of each staff in thirds at 2.5 to 3.2 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-086-the-minstrel-of-the-macdonalds',
    title: 'The Minstrel of the Macdonalds',
    region: 'scottish',
    kind: 'air',
    key: 'A', mode: 'minor', meter: '3/4',
    origin: 'Gaelic air, printed title Smeorach Clann Donaill; marked Solemnly Slow. Printed with no key signature. The lower notes of the violin double stops and the grace notes are left out; the slurs over repeated notes are left out with the other slurs',
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: 'X:1\nT:The Minstrel of the Macdonalds\nM:3/4\nL:1/8\nK:Am\nE2 | A6 | B2 B4 | c4 B3/2A/ | B2 ^G2 E2 | A2 A4 | B2 B4 | c4 B3/2A/ | c3/2B/ B4 |\nc4 B3/2A/ | A3 ^G e2 | A3 B c2 | B2 ^G2 E2 | A4 A^G | e4 g2 | d2 B2 A2 | A4 ||\nA2 | B3 A B2 | g6 | B3 A G2 | E2 E4 | B3 A B2 | g6 | B4 d2 | e4 g/^f/g/a/ |\nb3 a g2 | ge e4 | B3 A G2 | GE E4 | A4 A^G | e4 g2 | d2 B2 A2 | A6 ||\nBA | G2 E2 A2 | c4 B2 | e3 d c2 | B4 e2 | d2 G2 A2 | c4 B2 | A3 ^GAB | A4 BA |\nG2 E2 A2 | c4 B2 | e3 d c2 | B4 e2 | d2 G2 A2 | e4 g2 | e3 B d2 | A4 |]',
    source: { ...SOURCE, where: 'No. 86, p. 42 (PDF page 50)' },
    transcription: 'read from the scan (PDF page 50, the Internet Archive page image of each staff in quarters at 1.8 to 4 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-084-my-lover-wounded',
    title: 'My Lover Wounded',
    region: 'scottish',
    kind: 'song-air',
    key: 'G', mode: 'major', meter: '3/4',
    origin: 'Gaelic song air, printed title Mo ghradh fodh leon; marked Tender. The grace notes and the small notes closing the trills are left out; a pause sits on the E of the second strain, marked retard. dim.',
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: 'X:1\nT:My Lover Wounded\nM:3/4\nL:1/8\nK:G\nG3/2A/ | B2 c2 d3/2B/ | A2 GE G3/2A/ | B2 d3/2B/ A2 | G4 :|\nd2 | e3/2d/ d2 Bd | e3/2d/ d2 Bd | g f/e/ d2 c3/2B/ | A3/2B/4d/4 e2 f/a/g/e/ |\nd2 B3/2c/ d3/2B/ | A2 GE G3/2A/ | B2 d3/2B/ A2 | G4 |]',
    source: { ...SOURCE, where: 'No. 84, p. 41 (PDF page 49)' },
    transcription: 'read from the scan (PDF page 49, the Internet Archive page image of each staff in quarters at 1.8 to 4 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-109-the-kings-health',
    title: "The King's Health",
    region: 'scottish',
    kind: 'air',
    key: 'B', mode: 'minor', meter: '3/4',
    origin: "Gaelic air, printed title Deoch slaint an Righ; marked Slow. The lower notes of the violin double stops, the grace notes and the trills are left out. The print marks a start-repeat before the second strain but no closing repeat, so the second strain is written once",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:The King's Health\nM:3/4\nL:1/8\nK:Bm\nB3/2c/ B3 A | B3/2c/ d3 e | d3/2e/ f3 e | d3/2c/ d3 B | A3/2A/ B3 A | B3/2d/ e3 B |\nd3/2e/ d3 c | d3/2e/ f3 g | f3/2B/ B3 ^d | e3/2f/ e3 c | d3/2e/ f3 e | d3/2B/ A3 G |\nF3/2G/ A3 g | f3/2e/ d3 c | B3/2A/ F3 E | F3/2^A/ B3 B :|\nd3/2e/ d3 D | d3/2e/ f3 e | d3/2D/ f3 e | d3/2c/ d3 B | e3/2f/ e3 ^d | e3/2f/ g3 b |\na3/2g/ f3 e | d3/2e/ f3 a | f3/2B/ B3 ^d | e3/2f/ e3 c | d3/2e/ f3 e | d3/2B/ A3 G |\nF3/2G/ A3 g | f3/2e/ d3 c | B3/2A/ F3 E | F3/2^A/ B3 B |]",
    source: { ...SOURCE, where: 'No. 109, p. 52 (PDF page 60)' },
    transcription: 'read from the scan (PDF page 60, the Internet Archive page image of each staff in quarters at 1.8 to 3.2 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-129-fingalian-air',
    title: 'Fingalian Air',
    region: 'scottish',
    kind: 'air',
    key: 'A', mode: 'minor', meter: '3/4',
    origin: "Gaelic title Dan Feinne; marked Very Slow. Printed with no key signature. The lower notes of the violin double stops, the grace notes, the trills and the small notes closing them are left out. The print marks a start-repeat before the second strain but no closing repeat, so the second strain is written once",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    irregular: 'bar 16 (second strain, bar 6) is printed with no dot after the G, so it is a sixteenth short; written as printed',
    abc: "X:1\nT:Fingalian Air\nM:3/4\nL:1/8\nK:Am\nG2 | c4 G2 | c4 c/d/c/B/ | A2 d2 B2 | c4 d3/2e/ | a4 g2 |\ng3/2a/ g2 f2 | e4 d3/2e/ | a4 c3/2d/ | e4 d2 | c4 :|\ne3/2d/ | c4 B3/2A/ | G4 c3/2B/ | A2 d2 B2 | c4 d3/2e/ | a4 g2 |\nga/ g2 f2 | e4 d3/2e/ | a4 e3/2d/ | c4 B2 | A4 |]",
    source: { ...SOURCE, where: 'No. 129, p. 61 (PDF page 69)' },
    transcription: 'read from the scan (PDF page 69, the Internet Archive page image of each staff in quarters at 1.8 to 4 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-141-the-dairymaids-daughter',
    title: "The Dairymaid's Daughter",
    region: 'scottish',
    kind: 'song-air',
    key: 'E', mode: 'minor', meter: '4/4',
    origin: "Gaelic song air, printed title Horrin ho air nighean an airich; marked Moderate & Pointed. Both strains close on B, the fifth, over an E in the bass. The lower notes of the violin double stops, the slurred grace-note pairs and the trills are left out",
    tags: ['highlands', 'air', 'scottish'],
    abc: "X:1\nT:The Dairymaid's Daughter\nM:C\nL:1/8\nK:Em\n|: E/E3/2 G3/2A/ B2 D3/2F/ | E/E3/2 G3/2A/ B3/2A/ B2 | B3/2A/ G3/2A/ B2 D3/2F/ | E/E3/2 G3/2B/ e2 B2 :|\n|: G/G3/2 d3/2B/ d2 e/E3/2 | G/G3/2 d3/2B/ d2 e2 | g2 e^c d2 B3/2G/ | A/A3/2 B^d e2 B2 :|",
    source: { ...SOURCE, where: 'No. 141, p. 67 (PDF page 75)' },
    transcription: 'read from the scan (PDF page 75, the Internet Archive page image of each staff in quarters at 1.8 to 3.5 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-152-a-rowing-time-piece',
    title: 'A Rowing Time Piece',
    region: 'scottish',
    kind: 'song-air',
    key: 'D', mode: 'major', meter: '6/8',
    origin: "Gaelic boat song, printed title Iorram iomruigh; marked Moderate. The lower notes of the violin double stops, the grace notes and the trills are left out. The print marks a start-repeat before the second strain but no closing repeat, so the second strain is written once",
    tags: ['highlands', 'air', 'scottish'],
    abc: "X:1\nT:A Rowing Time Piece\nM:6/8\nL:1/8\nK:D\nA | F2 F F2 A | G2 F E2 D | DFA d2 e | f2 e d2 F | ABc d2 e | fdf e2 c | d3/2c/B A2 G | d2 F E2 D :|\nADE D2 C | F2 F ABc | d3/2c/B A2 G | F2 F ABc | d3/2e/f D2 C | F2 F ABc | dcB AGF | FdF E2 D |]",
    source: { ...SOURCE, where: 'No. 152, p. 71 (PDF page 79)' },
    transcription: 'read from the scan (PDF page 79, the Internet Archive page image of each staff in quarters at 1.8 to 3.5 times native, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-165-my-love-to-day-as-heretofore',
    title: 'My Love to day as heretofore',
    region: 'scottish',
    kind: 'song-air',
    key: 'G', mode: 'major', meter: '6/8',
    origin: "Gaelic song air, printed title Mo Run an diu mar an de u; marked Slow & Pathetic. The lower notes of the violin double stops, the grace notes, the trills and the small-note flourish before the pause in the second strain are left out",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    irregular: 'the first bar of the second ending is printed B A B with no dot after the first B, so it is a sixteenth short; written as printed',
    abc: "X:1\nT:My Love to day as heretofore\nM:6/8\nL:1/8\nK:G\nB3/2A/B d3 | G2 D E2 G | e^de g3 | d2 A B2 d | e2 d g2 B | G2 D E2 D | B2 A d2 e | d2 B G2 A :|\n|: B2 G A2 G | G2 D E2 G | e2 d d2 e | d2 A B2 d | g2 f e2 B | G2 D E2 D | B2 A d2 e |1 d2 B G2 A :|2 B A/B e3 | d3/2B/A G3 |]",
    source: { ...SOURCE, where: 'No. 165, p. 77 (PDF page 85)' },
    transcription: 'read from the scan (PDF page 85, the Internet Archive page image of each staff in quarters at 1.8 to 3.5 times native, staff positions measured, note-head areas measured to tell grace notes from real ones) and ' + READ,
  },
  {
    id: 'fraser-174-my-darling-has-deceived-me',
    title: 'My darling has deceived me',
    region: 'scottish',
    kind: 'song-air',
    key: 'G', mode: 'major', meter: '3/4',
    origin: "Gaelic song air, printed title Rinn m' eudail mo mhealladh; marked Slow & Plaintive. The violin part is set in double and triple stops: the top note of each is read. The grace notes, the trills and the small notes closing them are left out. The pause in bars 14 and 30 is on the A",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:My darling has deceived me\nM:3/4\nL:1/8\nK:G\nG2 D2 E2 | d3/2B/ A2 G2 | G2 D2 E2 | c2 e2 d2 | f/a/g/e/ d2 c2 | B/d/c/B/ A2 B2 | c3/2d/4e/4 d2 D2 | G2 F/G/A G2 |\nG2 D2 E2 | d3/2B/ A2 G2 | G2 D2 E2 | c2 e2 d2 | f/a/g/e/ d2 c2 | B/d/c/B/ A3 B | g3/2e/ d2 D2 | G2 F/G/A G2 ||\nG2 d2 c2 | B2 g3/2B/ A2 | G2 d2 B2 | c2 e2 d2 | f/a/g/e/ d2 c2 | B/d/c/B/ A2 B2 | c3/2d/4e/4 d2 D2 | G2 F/G/A G2 |\nG2 d2 c2 | B2 g3/2B/ A2 | G2 d2 B2 | c2 e2 d2 | f/a/g/e/ d2 c2 | B/d/c/B/ A3 B | g3/2e/ d2 D2 | G2 F/G/A G2 |]",
    source: { ...SOURCE, where: 'No. 174, p. 81 (PDF page 89)' },
    transcription: 'read from the scan (PDF page 89, the Internet Archive page image of each staff in quarters at 1.8 times native, beamed figures and chords at 3 to 4 times, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-170-beauty-charming-fair-and-young',
    title: 'Beauty, charming, fair and young',
    region: 'scottish',
    kind: 'song-air',
    key: 'B', mode: 'minor', meter: '4/4',
    origin: "Gaelic song air, printed title Ribhinn aluim, aoibhinn og; the English printed as Beauty, charming, fair & young; marked Slow. The lower note of the closing double stops, the grace notes and the staccato dots are left out. A pause sits on the A sharp in bar 6",
    tags: ['highlands', 'air', 'slow', 'scottish'],
    abc: "X:1\nT:Beauty, charming, fair and young\nM:C\nL:1/8\nK:Bm\nd2 cd fedc | f2 B2 ^A2 GF | E2 E2 F2 ^A2 | B2 B^A B4 | d2 cd fedc | f2 B2 ^A2 GF | E2 E2 F2 ^A2 | B2 B^A B4 ||\nd2 dd e2 ee | f2 f^e f2 F2 | Fdcd fedc | f2 B2 ^A2 ^GF | f3/2e/ df e3/2d/ ce | f2 B2 ^A2 GF | E2 E2 F2 ^A2 | B2 B^A B4 |]",
    source: { ...SOURCE, where: 'No. 170, p. 79 (PDF page 87)' },
    transcription: 'read from the scan (PDF page 87, the Internet Archive page image of each staff in quarters at 1.8 times native, accidentals and dotted figures in colour at 1.5 to 4 times, staff positions measured) and ' + READ,
  },
  {
    id: 'fraser-199-the-dirge-of-mull',
    title: 'The Dirge of Mull',
    region: 'scottish',
    kind: 'lament',
    key: 'A', mode: 'minor', meter: '4/4',
    origin: "Gaelic air, printed title An cronan Muillach; marked Slow & Plaintive. The grace notes are left out, and in bar 12 the lower G sharp of the double stop under the pause is left out",
    tags: ['highlands', 'air', 'slow', 'lament', 'scottish'],
    irregular: 'bar 12 (second strain, bar 4) is printed as a dotted crotchet, two semiquavers, a crotchet under a pause and a quaver rest, one quaver short of the bar; written as printed',
    abc: "X:1\nT:The Dirge of Mull\nM:C\nL:1/8\nK:Am\nA4 ^G2 E2 | c4 d2 B2 | c3 d e4 | e2 d2 d2 c2 | c3 d e3 g | e2 A2 ^G2 E2 | A4 ^G3 B | c3 d/c/ B2 A2 :|\n|: A3 B e4 | A4 ^G2 E2 | A3 B e3 g | c3 d/c/ B2 z | A3 B e4 | A4 ^G2 E2 | e3 ^d e2 ^G2 | A3 (3^G/A/B/ A4 :|",
    source: { ...SOURCE, where: 'No. 199, p. 93 (PDF page 101)' },
    transcription: 'read from the scan (PDF page 101, the Internet Archive page image of each staff in thirds at 2.2 times native, staff positions measured, the rest shapes compared with the bass staff) and ' + READ,
  },
];

export default TUNES;
