// settle-hear · tunes/harpclaymore1903 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book page: wikis/WIKI_OLD_MELODIES/books/BOOK_HARPCLAYMORE1903.md. PDF page = printed page + 18.

export const SOURCE = {
  kind: 'print',
  book: 'The Harp and Claymore (1981 Moxon facsimile of the 1903 print; the 1903 music only)',
  compiler: 'J. Scott Skinner (1843-1927), edited by Gavin Greig (1856-1914); London and Glasgow: Bayley & Ferguson',
  year: 1903,
  scan: 'https://archive.org/details/j-scott-skinner-harp-and-claymore',
};

const T = 'read from the scan (each staff in parts at 500 to 1000 dpi) and proofed bar by bar by lane MELODIES200 reader harpclaymore1903, 2026-10-02';

export const TUNES = [
  {
    id: 'hc-p152-hector-the-hero',
    title: 'Hector the Hero',
    region: 'scottish',
    kind: 'lament',
    key: 'A', mode: 'major', meter: '6/8',
    origin: 'Lament by J. Scott Skinner for Major-General Sir Hector Macdonald, arranged by Gavin Greig; marked Lament, Slow; the print adds "1st time 8ve lower ad lib."; violin line of the violin and piano score',
    tags: ['air', 'slow', 'lament', 'highlands', 'scottish'],
    abc: 'X:1\nT:Hector the Hero\nM:6/8\nL:1/8\nK:A\nA | c3/2B/A fec | e3-e2A | c3/2B/A fec | B3-B2A |\nc3/2B/A fec | e2A a2f | eAc B2A | A3-A2 :|\nc | fgf agf | e3-e2c | fec eAc | B3-B2c |\nfgf agf | eAB c/a3/2f | eAc B2A | A3-A2 |]',
    source: { ...SOURCE, where: 'p. 152 (PDF page 170)' },
    transcription: T,
  },
  {
    id: 'hc-p148-cluny-macphersons-lament',
    title: "Cluny Macpherson's Lament",
    region: 'scottish',
    kind: 'lament',
    key: 'D', mode: 'major', meter: 'C',
    origin: 'Lament by J. Scott Skinner, marked Waefully; violin line of the violin and piano score, its many pipe-style grace notes and the trill left out; in bar 4 the violin plays a double stop (D over A) on the sixteenth after the dotted F, and the top note is taken',
    tags: ['air', 'slow', 'lament', 'highlands', 'scottish'],
    abc: 'X:1\nT:Cluny Macpherson\'s Lament\nM:C\nL:1/8\nK:D\nA3/2F/ A2 B3/2A/ d2 | e3/2d/ f3/2e/ e3/2d/ B2 | A3/2F/ A2 B3/2A/ d3/2f/ | e3/2d/ f3/2d/ e2 d z |\nf3/2d/ a2 f3/2A/ d2 | e3/2d/ f3/2e/ e3/2d/ B2 | A3/2F/ A2 B3/2A/ d2 | e3/2A/ f3/2A/ e2 d z |]',
    source: { ...SOURCE, where: 'p. 148 (PDF page 166), upper tune' },
    transcription: T,
  },
  {
    id: 'hc-p148-colonel-smiths-lament',
    title: "Colonel Smith's Lament",
    region: 'scottish',
    kind: 'lament',
    key: 'D', mode: 'major', meter: 'C',
    origin: 'Lament by J. Scott Skinner; footnote in the print: Minmore Glenlivet; violin line of the violin and piano score, grace notes left out',
    tags: ['air', 'slow', 'lament', 'highlands', 'scottish'],
    abc: 'X:1\nT:Colonel Smith\'s Lament\nM:C\nL:1/8\nK:D\nA/A3/2 d2 ed f2 | e3/2d/ f3/2e/ ed B2 | A/A3/2 d2 ed f2 | edBd BA A2 |\nA/A3/2 d2 ed f2 | ed f3/2e/ ed B2 | AA d2 ed f2 | edBd BA A2 ||\nA/A3/2 f2 A/A3/2 d2 | A/A3/2 f3/2d/ ed B2 | A/A3/2 f2 A/A3/2 d2 | ef af ed d2 |\nA/A3/2 f2 A/A3/2 d2 | A/A3/2 a3/2f/ ed B2 | A/A3/2 d2 ed f2 | a3/2f/ ed BA A2 |]',
    source: { ...SOURCE, where: 'p. 148 (PDF page 166), lower tune' },
    transcription: T,
  },
  {
    id: 'hc-p54-the-barren-rocks-of-aden',
    title: 'The Barren Rocks of Aden',
    region: 'scottish',
    kind: 'quickstep',
    key: 'D', mode: 'major', meter: 'C',
    origin: 'Pipe quickstep credited in the print to A. MacKellar, 78th Highlanders; crotchet = 112; the theme only, without the variation on the first strain by J. Scott Skinner printed after it; grace notes and the second voice of the double stops left out',
    tags: ['march', 'highlands', 'scottish'],
    abc: 'X:1\nT:The Barren Rocks of Aden\nM:C\nL:1/8\nK:D\nd/e/ | f3/2g/fe df A/4A3/4d | ce A/4A3/4e fAde | f3/2g/fe df A/4A3/4d | ce A/4A3/4f d2-d :|\nf/g/ | a3/2f/df ef A/4A3/4e/f/ | g3/2e/ce df A/4A3/4f/g/ | a3/2f/df ef A/4A3/4e/f/ | g3/2e/ca d2-d :|',
    source: { ...SOURCE, where: 'p. 54 (PDF page 72), first two staves' },
    transcription: T,
  },
  {
    id: 'hc-p93-the-laird-o-drumblair',
    title: "The Laird o' Drumblair",
    region: 'scottish',
    kind: 'strathspey',
    key: 'A', mode: 'major', meter: 'C',
    origin: 'Strathspey or schottische by J. Scott Skinner; violin line of the violin and piano score; the triplet sign is printed on the first group of each triplet bar only; the drone notes under the second strain, the double stops and the grace notes are left out (top note kept)',
    tags: ['strathspey', 'dance', 'highlands', 'scottish'],
    abc: 'X:1\nT:The Laird o\' Drumblair\nM:C\nL:1/8\nK:A\nE | A2 c3/2A/ E3/2A/ c3/2A/ | a2 g3/2a/ f3/2a/ e3/2c/ | (3def (3efg (3aed (3cBA | (3Bcd (3cBA (3GFE (3dcB |\nA2 c3/2A/ E/A3/2 c3/2A/ | a2 g3/2a/ f3/2a/ e3/2c/ | (3def (3efg (3aed (3cBA | (3GFE (3dcB A2 A ||\ng | a2 e3/2a/ c3/2a/ A3/2a/ | c/B/A e3/2g/ a3/2A/ c/a3/2 | a2 f3/2a/ d3/2a/ B3/2a/ | d/c/B f3/2^a/ b3/2B/ d/b3/2 |\na2 e3/2a/ c3/2a/ A3/2a/ | c/B/A e3/2g/ a3/2A/ c3/2A/ | (3def (3efg (3aed (3cBA | (3GFE (3dcB A2 A |]',
    source: { ...SOURCE, where: 'p. 93 (PDF page 111)' },
    transcription: T,
  },
  {
    id: 'hc-p71-the-miller-o-hirn',
    title: "The Miller o' Hirn",
    region: 'scottish',
    kind: 'strathspey',
    key: 'D', mode: 'major', meter: 'C',
    origin: 'Highland schottische or strathspey by J. Scott Skinner; violin line of the violin and piano score, grace notes, turns and the lower notes of double stops left out; the print ends the second strain with D.C. and a final chord marked Fine, written out here as the first strain once more and the top note of the Fine chord',
    tags: ['strathspey', 'dance', 'highlands', 'scottish'],
    abc: 'X:1\nT:The Miller o\' Hirn\nM:C\nL:1/8\nK:D\nD3/2E/ F/B3/2 A/F3/2 D2 | B,3/2E/ G/F/E/D/ C/A,3/2 A,3/2C/ | D3/2E/ F/B3/2 A/F3/2 D2 | B,3/2D/ C/A3/2 F/D3/2 D2 :|\nA3/2G/ F/d3/2 B/G3/2 G2 | B3/2A/ ^G/e3/2 c/A3/2 A3/2B/ | A3/2G/ F/d3/2 B3/2A/ G/B3/2 | c3/2B/ A/a3/2 f/d3/2 d3/2B/ |\nA3/2G/ F/d3/2 B/G3/2 G2 | B3/2A/ ^G/e3/2 c/A3/2 A3/2c/ | (3dAB (3cde (3fde (3fga | (3bag (3fed (3cBA (3GFE ||\nD3/2E/ F/B3/2 A/F3/2 D2 | B,3/2E/ G/F/E/D/ C/A,3/2 A,3/2C/ | D3/2E/ F/B3/2 A/F3/2 D2 | B,3/2D/ C/A3/2 F/D3/2 D2 | d8 |]',
    source: { ...SOURCE, where: 'p. 71 (PDF page 89)' },
    transcription: T,
  },
  {
    id: 'hc-p147-glencoe',
    title: 'Glencoe',
    region: 'scottish',
    kind: 'lament',
    key: 'Eb', mode: 'major', meter: 'C',
    origin: 'Dirge by J. Scott Skinner; violin line of the violin and piano score, double stops reduced to their top note and grace notes left out; the A natural in bar 11 holds to the end of the bar as printed; the print ends with D.C. and marks an ornament in bar 15 for the last time, written here as one repeat of the whole tune',
    tags: ['air', 'slow', 'lament', 'highlands', 'scottish'],
    abc: 'X:1\nT:Glencoe\nM:C\nL:1/8\nK:Eb\n|: E3/2G/ | B4 G2 E3/2G/ | B4 G2 e3/2c/ | B2 G2 E2 DE |\nG4 F2 E3/2G/ | B4 G2 E3/2G/ | B4 e2 c2 | B2 E2 G2 F2 | E6 ||\nG3/2A/ | G4 d2 G3/2A/ | G4 e2 G2 | =A2 e2 G2 A2 | B6 E3/2G/ |\nB4 G2 E3/2G/ | B4 e2 c2 | B2 E2 G2 F2 | E6 :|',
    source: { ...SOURCE, where: 'p. 147 (PDF page 165), lower tune' },
    transcription: T,
  },
  {
    id: 'hc-p159-the-bonnie-thackit-hoosie',
    title: 'The Bonnie Thackit Hoosie',
    region: 'scottish',
    kind: 'air',
    key: 'F', mode: 'major', meter: 'C',
    origin: 'Air by J. Scott Skinner, marked Smoothly; violin line of the violin and piano score, grace notes left out and double stops reduced to their top note; the B natural in bar 10 holds to the end of the bar as printed; a pause on the last note',
    tags: ['air', 'slow', 'highlands', 'scottish'],
    abc: 'X:1\nT:The Bonnie Thackit Hoosie\nM:C\nL:1/8\nK:F\nAB | cfed cAGF | B2 d2 c2 fe | dcBA GFEF | A2 G2 G2 AB |\ncfed cAGF | BABc d2 ed | cAGF G2 FG | A2 F2 F2 ||\nzB | ABcA B d2 c | =BcdB c e2 d | ^cdef ed=cB | A2 G2 F2 |]',
    source: { ...SOURCE, where: 'p. 159 (PDF page 177), upper tune' },
    transcription: T,
  },
  {
    id: 'hc-p1-the-cradle-song',
    title: 'The Cradle Song',
    region: 'scottish',
    kind: 'air',
    key: 'A', mode: 'major', meter: 'C',
    origin: 'Instrumental cradle song by J. Scott Skinner, the first piece in the book, marked Muted Violin; the melody is the top note of the upper staff of the piano score, grace notes left out; the book also prints a vocal Cradle Song later, which is a different piece',
    tags: ['air', 'slow', 'highlands', 'scottish'],
    abc: 'X:1\nT:The Cradle Song\nM:C\nL:1/8\nK:A\nAcBA e2 f2 | e4 c2 z2 | AcBA e2 c2 | B6 c2 |\nAcBA e2 f2 | e4 c2 A2 | FEAB c2 B2 | A6 z2 ||\nfdAd f2 a2 | e4 c2 z2 | AcBA e2 c2 | B6 z2 |\nAcBA efga | e4 c2 A2 | FEAB c2 B2 | A6 z2 |]',
    source: { ...SOURCE, where: 'p. 1 (PDF page 19)' },
    transcription: T,
  },
  {
    id: 'hc-p70-forbess-sneeshin-mull',
    title: "Forbes's Sneeshin Mull",
    region: 'scottish',
    kind: 'air',
    key: 'G', mode: 'major', meter: 'C',
    origin: 'By J. Scott Skinner, headed "Slow Air, Strathspey, or Reel"; violin line of the violin and piano score, grace notes, turns and the lower notes of double stops left out; in bar 6 the natural sign stands on a grace note before the F and holds for the bar as printed; bar 15 is printed with a 3 over its first group for the strathspey and a second stemming for the slow air and reel, the same notes in both',
    tags: ['air', 'slow', 'strathspey', 'highlands', 'scottish'],
    abc: 'X:1\nT:Forbes\'s Sneeshin Mull\nM:C\nL:1/8\nK:G\nc | B/G3/2 B/d3/2 g2 d3/2e/ | =f2 c3/2f/ c/=F3/2 F3/2c/ | B/G3/2 B/d3/2 g2 d3/2f/ | g2 d3/2c/ B/G3/2 G3/2c/ |\nB/G3/2 B/d3/2 g2 d3/2e/ | =f2 c3/2f/ A/=F3/2 F3/2A/ | BGBd ecfd | g2 d3/2c/ B/G3/2 G ||\n^d | e2 B3/2f/ g2 e3/2^c/ | d2 A3/2d/ F/D3/2 D3/2^d/ | e2 B3/2e/ g2 e3/2c/ | B3/2G/ F/B3/2 G/E3/2 E3/2^d/ |\ne2 B3/2f/ g2 e3/2^c/ | d3/2f/ A3/2d/ F/D3/2 D3/2F/ | (3GAB (3ABc (3Bcd (3cde | (3ABc (3FGA B/G3/2 G |]',
    source: { ...SOURCE, where: 'p. 70 (PDF page 88)' },
    transcription: T,
  },
];

export default TUNES;
