// settle-hear · tunes/joyce1873 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book: P. W. Joyce, Ancient Irish Music, Dublin: McGlashan and Gill, 1873 (piano arrangements by Professor
// Glover). The melody is the top line of the right hand. Printed page N is PDF page N + 16.

export const SOURCE = {
  kind: 'print',
  book: 'Ancient Irish Music, comprising one hundred airs hitherto unpublished, many of the old popular songs, and several new songs',
  compiler: 'P. W. Joyce, harmonised by Professor Glover',
  year: 1873,
  scan: 'https://archive.org/details/ancientirishmusi00joyc',
};

const READ = (pdf) => `read from the scan (PDF page ${pdf}, each staff in thirds at 400 dpi) and proofed bar by bar by lane MELODIES200 reader joyce1873, 2026-10-02`;

const READQ = (pdf) => `read from the scan (PDF page ${pdf}, each staff in quarters at 550 dpi, with the staff lines located and the pitches checked line by line) and proofed bar by bar by lane MELODIES200 reader joyce1873, 2026-10-02`;

export const TUNES = [
  {
    id: 'joyce-001-the-fairy-kings-courtship',
    title: "The Fairy King's Courtship",
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '3/4',
    origin: 'Munster ballad air; Joyce learned air and words from his father as a child and never heard the air from anyone else; marked Slow and with expression',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:1\nT:The Fairy King\'s Courtship\nM:3/4\nL:1/8\nK:Eb\nE2 | E2 E2 EF | A4 BA | F2 E2 E2 | E4 GA | B2 B2 c2 |\n_d2 B2 A2 | B2 e2 e2 | e4 =de | f2 e2 d2 | e4 dc |\nB2 G2 E2 | F4 AB | cd e2 dB | A2 F2 F2 | E4 E2 | E4 |]',
    source: { ...SOURCE, where: 'No. 1, p. 2 (PDF page 18)' },
    transcription: READ(18),
  },
  {
    id: 'joyce-008-the-dawning-of-the-day',
    title: 'The Dawning of the Day',
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'major', meter: '2/4',
    origin: 'Irish song air, Gaelic title Fainne geal an lae; the song was still well known in the southern counties (Joyce); marked Andante',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:8\nT:The Dawning of the Day\nM:2/4\nL:1/8\nK:F\nF/G/ | AA AG/A/ | cc dc/A/ | FG FF | F3 c |\ndc df | A3/2G/ FA | c3/2A/ fA | G3 c |\ndc df | A3/2G/ FA | c3/2A/ fA | G3 F/G/ |\nAA AG/A/ | cc dc/A/ | FG FF | F3 |]',
    source: { ...SOURCE, where: 'No. 8, p. 8 (PDF page 24)' },
    transcription: READ(24),
  },
  {
    id: "joyce-002-the-barley-grain",
    title: "The Barley Grain",
    region: 'irish',
    kind: "jig",
    key: "G", mode: "major", meter: "6/8",
    origin: "Munster double jig; Joyce noted it from the whistling of James Quain, a farmer of Coolfree on the Cork and Limerick border, who called it a very old tune known to few; marked Jig time",
    tags: ["jig", "dance", "irish"],
    abc: "X:2\nT:The Barley Grain\nM:6/8\nL:1/8\nK:G\nBAB G2D | GAG GAB | BAB GFG | A2B c2A | BAB G2D |\nGAG GAB | ded dcB | A2B c2A ||\nB2d ded | ded ded | B2d ded | e2f g3 | B2d ded |\nded def | gfe dcB | A2B c2A |]",
    source: { ...SOURCE, where: "No. 2, p. 4 (PDF page 20)" },
    transcription: READ(20),
  },
  {
    id: "joyce-003-slan-beo-farewell",
    title: "Slan Beo (Farewell)",
    region: 'irish',
    kind: "song-air",
    key: "F", mode: "major", meter: "3/4",
    origin: "Irish song air, Gaelic title Slan beo; Joyce noted it in 1853 from the singing of a national schoolmaster, a native of Kerry; marked Slow and with expression",
    tags: ["air", "slow", "irish"],
    abc: "X:3\nT:Slan Beo (Farewell)\nM:3/4\nL:1/8\nK:F\nFG | A2 D2 E2 | F4 AB | c4 AF | G2 F2 F2 | F4 FG | A2 F2 G2 |\nf4 ef | d4 dc | A2 F2 G2 | A4 AG | A2 F2 G2 | f4 ef | d4 dc |\nA2 F2 G2 | A4 AG | A2 D2 E2 | F3 GAB | c4 AF | G2 F2 F2 | F4 |]",
    source: { ...SOURCE, where: "No. 3, pp. 4-5 (PDF pages 20 and 21)" },
    transcription: READ(20),
  },
  {
    id: 'joyce-010-crabs-in-the-skillet',
    title: 'Crabs in the Skillet',
    region: 'irish',
    kind: 'jig',
    key: 'F', mode: 'major', meter: '6/8',
    origin: 'Irish jig in three parts; Joyce noted it down in 1854 from James Buckley, a Limerick piper, who believed the tune belonged to County Clare; marked A little slower than jig time',
    tags: ['jig', 'dance', 'irish'],
    abc: 'X:10\nT:Crabs in the Skillet\nM:6/8\nL:1/8\nK:F\nG3 d2^F | G2A B2c | ded cBA | dcB AGF | G3 d2^F | G2A B2d | cAc fed |1 cAF FEF :|2 cAF F3 ||\n|: gag gfe | fgf fed | cde fed | cAG G3 | gag gfe | fgf fed | cde fef |1 cAF F3 :|2 cAF FEF ||\n|: G3 A3 | B3 c3 | ded cBA | dcB AGF | G3 A3 | B3 d3 | cAc fed |1 cAF FEF :|2 cAF F3 |]',
    source: { ...SOURCE, where: 'No. 10, p. 11 (PDF page 27)' },
    transcription: READQ(27),
  },
  {
    id: 'joyce-011-och-ochone',
    title: 'Och Ochone',
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'major', meter: '4/4',
    origin: 'Irish song air; Joyce had known it and heard it sung as long as he could remember; the Irish song was a sort of lament, though not a death song, every stanza ending with Och-ochone; marked Andantino; grace notes left out',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:11\nT:Och Ochone\nM:4/4\nL:1/8\nK:F\nA2 G2 F3 G | Ac c2 d2 cA | AG G2 G2 GG | Ac c2 d2 c2 |\nB2 AB c2 de | f3/2e/ fd e2 c3/2B/ | A2 G2 F3 G | f2 g2 f2 c3/2B/ | A2 G2 F4 |]',
    source: { ...SOURCE, where: 'No. 11, p. 12 (PDF page 28)' },
    transcription: READQ(28),
  },
  {
    id: 'joyce-012-when-i-rose-on-a-misty-morning',
    title: 'When I Rose on a Misty Morning',
    region: 'irish',
    kind: 'song-air',
    key: 'D', mode: 'dorian', meter: '4/4',
    origin: "Irish song air, Gaelic title Maidin cheodhach nuair d'eirigheas; Joyce took it with its Irish song from the singing of Nora Dwane of Glenosheen, County Limerick, and later found the song published and translated by Edward Walsh in Irish Popular Songs; marked Moderate time",
    tags: ['air', 'slow', 'irish'],
    abc: 'X:12\nT:When I Rose on a Misty Morning\nM:4/4\nL:1/8\nK:Ddor\nCD | E2 E2 DEGA | c4 d2 fe | d3/2c/ AG E2 E2 | D4 D2 cd | e2 e2 dcAB |\nc3 d e2 fe | dc A2 c2 d2 | d6 cd | e2 e2 dcAB | c3 d e2 fe |\nd3/2c/ AG E2 E2 | D4 D2 (3GEC | D2 EC DEGA | c3 e dc AG | D4 D2 D2 | D6 |]',
    source: { ...SOURCE, where: 'No. 12, pp. 12-13 (PDF pages 28 and 29)' },
    transcription: READQ('28 and 29'),
  },
  {
    id: 'joyce-040-the-magic-mist',
    title: 'The Magic Mist',
    region: 'irish',
    kind: 'song-air',
    key: 'E', mode: 'minor', meter: '3/4',
    origin: 'Irish song air, Gaelic title An ceo draoigheachta; Joyce noted it in the summer of 1853 from the singing of Alice Kenny, an old woman of the parish of Glenroe, County Limerick, whose Irish song is a Jacobite allegorical piece; marked Andante; headed No. 41 on the page, No. 40 in the contents',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:40\nT:The Magic Mist\nM:3/4\nL:1/8\nK:Em\nGA | B2 cA B3/2A/ | A2 GE D^C | D2 E2 GA | B2 cA B3/2A/ | A3/2G/ E2 E2 | E4 :|\nEF | GA B^c d2 | e2 BA GA | B2 B2 B^c | d2 d2 d2 | e2 B3/2A/ GE | G4 (3B^cd |\ne2 d3/2B/ AG | A2 GE D^C | D2 E2 GA | B2 cA B3/2A/ | A3/2G/ E2 E2 | E4 |]',
    source: { ...SOURCE, where: 'No. 40, pp. 42-43 (PDF pages 58 and 59)' },
    transcription: READQ('58 and 59'),
  },
  {
    id: 'joyce-053-the-eagles-whistle',
    title: "The Eagle's Whistle",
    region: 'irish',
    kind: 'march',
    key: 'G', mode: 'major', meter: '3/4',
    origin: "Irish march, Gaelic title Fead an iolair; Joyce took it down from the whistling of James Quain and of Michael Dinneen, both of Coolfree; it was the marching tune of the O'Donovans, anciently chiefs of the territory of Hy Fidhgheinte, west of the river Maigue in County Limerick; marked Marching time",
    tags: ['march', 'dance', 'irish'],
    abc: "X:53\nT:The Eagle's Whistle\nM:3/4\nL:1/8\nK:G\nB2 dB AG | B2 dB AG | A2 AB AG | A2 AB AG | B2 dB AG | B2 dB AB | G2 GB AF | G2 GB AG ||\ne2 dB gd | e2 dB AG | A2 AB AG | A2 AB AG | e2 dB gd | e2 dB AB | G2 GB AF | G2 GB AG |]",
    source: { ...SOURCE, where: 'No. 53, p. 53 (PDF page 69)' },
    transcription: READQ(69),
  },
  {
    id: 'joyce-066-lullaby',
    title: 'Lullaby',
    region: 'irish',
    kind: 'air',
    key: 'C', mode: 'minor', meter: '4/4',
    origin: 'Irish lullaby, Gaelic title Suantraidhe (Soontree), sung to the words Sho-ho, baby; Joyce had been familiar with it from his childhood; marked Gently',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:66\nT:Lullaby\nM:4/4\nL:1/8\nK:Cm\ne2 e2 e2 f/e/d/c/ | d2 ec d2 B2 | c2 c2 c3/2B/ GF | G2 G2 G4 |\ne2 e2 e2 f/e/d/c/ | d2 ec d2 B2 | c2 c2 c3/2B/ GF | D3 C C4 ||\n|: B2 B3/2G/ c3/2B/ GF | D2 EC D4 | B2 B3/2G/ c3/2B/ GF | D3 C C4 :|',
    source: { ...SOURCE, where: 'No. 66, p. 67 (PDF page 83)' },
    transcription: READQ(83),
  },
  {
    id: 'joyce-041-the-bag-of-meal',
    title: 'The Bag of Meal',
    region: 'irish',
    kind: 'jig',
    key: 'D', mode: 'major', meter: '6/8',
    origin: 'Irish double jig; Joyce learned it from his father; marked Jig',
    tags: ['jig', 'dance', 'irish'],
    abc: 'X:41\nT:The Bag of Meal\nM:6/8\nL:1/8\nK:D\nd/e/ | f2 d cAG | A2 d cAG | F2 D DED | F3 GED | ABA cAG | ABA A2 d | fed cAc | d3 d2 :|\n|: e | f2 d ded | fga afd | e2 =c =cd=c | efg gfe | fga agf | gfg efg | fed cAc | d3 d2 :|',
    source: { ...SOURCE, where: 'No. 41, p. 43 (PDF page 59)' },
    transcription: READQ(59),
  },
  {
    id: 'joyce-030-the-shanavest-and-caravat',
    title: 'The Shanavest and Caravat',
    region: 'irish',
    kind: 'march',
    key: 'F', mode: 'major', meter: '4/4',
    origin: 'Irish faction tune; Joyce took it down in 1854 from the singing of his grandmother, then over ninety, who had learned it in her childhood and had forgotten the Irish song to it; he thought it likely it was used as a march; named for two hostile factions of the south and south-east of Ireland; marked Bold; grace notes left out',
    tags: ['march', 'dance', 'irish'],
    abc: 'X:30\nT:The Shanavest and Caravat\nM:4/4\nL:1/8\nK:F\nFG | ABGA FGA=B | c=Bcd f2 ef | dfed cAGE | D2 D2 D2 :|\nFG | d2 d3/2e/ f2 ed | dc A3/2A/ A3 G | d2 de f2 ed | d^c e3/2d/ d3 A |\nd2 dc defg | fdcA cdef | dfed cAGE | D2 D2 D2 |]',
    source: { ...SOURCE, where: 'No. 30, p. 32 (PDF page 48)' },
    transcription: READQ(48),
  },
  {
    id: 'joyce-019-kennedys-jig',
    title: "Kennedy's Jig",
    region: 'irish',
    kind: 'jig',
    key: 'E', mode: 'minor', meter: '6/8',
    origin: 'Irish double jig; Joyce took it down in 1847 from the whistling of William Sheedy of Fanningstown, County Limerick',
    tags: ['jig', 'dance', 'irish'],
    abc: "X:19\nT:Kennedy's Jig\nM:6/8\nL:1/8\nK:Em\nB | BEE BEE | BAG FEF | DED FDF | AB^c dfd | BEE def | gfe fdB | AFA AdF | FEE E2 :|\n|: e | e/f/ge fed | e/f/ge fed | d/e/fe dAF | DFA def | edB def | gbg edB | AFA AdF | FEE E2 :|",
    source: { ...SOURCE, where: 'No. 19, pp. 20-21 (PDF pages 36 and 37)' },
    transcription: READQ('36 and 37'),
  },
  {
    id: 'joyce-034-astoreen-machree',
    title: 'Astoreen Machree',
    region: 'irish',
    kind: 'air',
    key: 'F', mode: 'major', meter: '3/4',
    origin: 'Irish air, English title O treasure of my heart; Joyce noted it in 1852 from the whistling of a native of Crossmolina, County Mayo; he observes that it lies in the minor mode but ends on the relative major; marked Slow and sad; the final bar holds a half note only, as printed',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:34\nT:Astoreen Machree\nM:3/4\nL:1/8\nK:F\nD2 DEFG | A2 d3 c | B2 A2 GF | D2 D4 | c2 c2 d2 |\nc2 A2 G2 | A2 d2 d2 | d4 de | f2 e2 d2 | c3 edc |\nB2 A2 GF | D2 D4 | c3 edc | B2 A2 G2 | A2 F2 F3/2G/ | F4 |]',
    source: { ...SOURCE, where: 'No. 34, p. 36 (PDF page 52)' },
    transcription: READQ(52),
  },
  {
    id: 'joyce-068-the-lowlands-of-holland',
    title: 'The Lowlands of Holland',
    region: 'irish',
    kind: 'song-air',
    key: 'E', mode: 'minor', meter: '4/4',
    origin: 'Song air; the song is also known in Scotland, but Joyce says the Irish air is quite different from the Scottish one; well known in Munster, and Joyce had been familiar with it all his life; marked With expression',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:68\nT:The Lowlands of Holland\nM:4/4\nL:1/8\nK:Em\nE3/2F/ | G2 G2 A3/2F/ EF | A3 B d2 ed | B2 AF E2 E2 | D6 E2 |\nG2 G2 A3/2F/ EF | A3 B d2 ed | B2 AF E2 E2 | E6 ||\nA2 | B2 e2 e2 dB | A3 B d2 ed | B2 AF E2 E2 | D6 E3/2F/ |\nG3 B AFEF | A3 B d2 ed | B2 AF E2 E2 | E6 |]',
    source: { ...SOURCE, where: 'No. 68, p. 69 (PDF page 85)' },
    transcription: READQ(85),
  },
  {
    id: 'joyce-038-drahareen-o-machree',
    title: 'Drahareen-O-Machree',
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'major', meter: '3/4',
    origin: 'Irish song air, English title Little brother of my heart; a plaintive air well known all over the south of Ireland, and Joyce had known air and words since his childhood; an older song to it was Jemmy, Mo-veela-sthore, whose verse is printed with the music; marked Moderate time',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:38\nT:Drahareen-O-Machree\nM:3/4\nL:1/8\nK:F\nDE | F2 G2 A2 | A f3 ed | c2 d2 A2 | G4 F2 | F4 c2 |\nf2 A2 A2 | c3 d e2 | f4 (3gfe | d4 (3cAG | A4 (3cde |\nf2 A2 A2 | c2 d2 e2 | f4 (3gfe | d4 (3cAG | A4 DE |\nF2 G2 A2 | A f3 ed | c2 d2 A2 | G4 F2 | F4 |]',
    source: { ...SOURCE, where: 'No. 38, p. 40 (PDF page 56)' },
    transcription: READQ(56),
  },
  {
    id: 'joyce-029-speir-bhean-the-bright-lady',
    title: 'Speir-bhean (The Bright Lady)',
    region: 'irish',
    kind: 'air',
    key: 'D', mode: 'major', meter: '4/4',
    origin: 'Irish air, Gaelic title Speir-bhean, literally celestial woman; Joyce noted it down in 1852 from the whistling of Davy Condon, a thatcher of Ballyorgan, County Limerick; marked Slowly and tenderly; grace notes left out',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:29\nT:Speir-bhean (The Bright Lady)\nM:4/4\nL:1/8\nK:D\n|: FG | A2 B/G/F/D/ DGFD | FGAB c2 d/c/B/c/ | A2 FD DFGF | D2 D2 D2 :|\n(3ABc | d2 d3/2e/ f2 ed | e2 d/c/A/G/ A2 (3ABc | d2 dd e2 d/c/A/B/ | =c2 d3/2d/ d3 A |\nd2 d2 de=cA | A2 A/G/F/D/ =cdcA | A2 FD DFGF | D2 D2 D2 |]',
    source: { ...SOURCE, where: 'No. 29, p. 31 (PDF page 47)' },
    transcription: READQ(47),
  },
  {
    id: 'joyce-058-king-charless-jig',
    title: "King Charles's Jig",
    region: 'irish',
    kind: 'set-dance',
    key: 'D', mode: 'major', meter: '6/8',
    origin: 'Irish set dance in jig time; Joyce noted it down in 1852 from James Buckley, a Limerick piper; two strains of six bars, as printed; marked Jig time',
    tags: ['jig', 'dance', 'irish'],
    abc: "X:58\nT:King Charles's Jig\nM:6/8\nL:1/8\nK:D\nG | FDF AFA | BGB AFD | E3 D2 G | FDF AFA | Bcd edc | d3 D3 ||\nc | def efg | fed faf | e3 E2 G | FDF AFA | Bcd edc | d3 D2 |]",
    source: { ...SOURCE, where: 'No. 58, p. 59 (PDF page 75)' },
    transcription: READQ(75),
  },
  {
    id: 'joyce-047-more-of-cloyne',
    title: 'More of Cloyne',
    region: 'irish',
    kind: 'air',
    key: 'G', mode: 'major', meter: '4/4',
    origin: 'Irish air, Gaelic title Mor Chluana; Joyce took it down in 1852 from Lewis O\'Brien of Coolfree, County Limerick, who said that More was the guardian fairy of Cloyne in Cork; marked With spirit',
    tags: ['air', 'irish'],
    abc: 'X:47\nT:More of Cloyne\nM:4/4\nL:1/8\nK:G\nG2 G2 F2 D2 | G2 G2 G4 | c2 B2 c2 d2 | e2 d2 d4 |\ndggf f2 ed | dedc B2 AG | ABcA d2 cA | G2 A2 B2 d2 |\ndggf f2 ed | dedc B2 AG | ABcA d2 cA | G2 G2 G4 |]',
    source: { ...SOURCE, where: 'No. 47, p. 48 (PDF page 64)' },
    transcription: READQ(64),
  },
  {
    id: 'joyce-046-whoeer-she-be',
    title: "Whoe'er She Be",
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'major', meter: '4/4',
    origin: 'Irish song air, Gaelic title Be n-Eirinn I; Joyce noted it down in 1853 from the singing of Michael Dinneen of Coolfree, County Limerick; the burden Be n-Eirinn i is common to several love songs, and the verse printed with it is from Edward Walsh\'s translation; marked With expression; one pause left out',
    tags: ['air', 'slow', 'irish'],
    abc: "X:46\nT:Whoe'er She Be\nM:4/4\nL:1/8\nK:F\nC | F2 F3/2G/ A2 c3/2B/ | A2 G2 F2 c3/2d/ | _e2 d/c/A G2 Ac |\n_e2 d2 c3 c | c2 A2 f2 ef | d2 c/A/G A2 AG |\nF2 F2 F3 G | A2 F/D/C D2 c (3d/c/B/ | A3 G F3 |]",
    source: { ...SOURCE, where: 'No. 46, p. 47 (PDF page 63)' },
    transcription: READQ(63),
  },
  {
    id: 'joyce-006-the-flannel-jacket',
    title: 'The Flannel Jacket',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: '4/4',
    origin: "Irish reel; a favourite dance tune in County Limerick twenty-five or thirty years before 1873, where Joyce learned it from constantly hearing it played by fiddlers and pipers; also called The Peeler's Jacket",
    tags: ['reel', 'dance', 'irish'],
    irregular: 'the opening bar holds a half rest only and the last bar three beats, as printed',
    abc: 'X:6\nT:The Flannel Jacket\nM:4/4\nL:1/8\nK:G\nz4 | D2 BG DGBG | FGAB c2 Bc | dggf d2 g2 | fdcA BGAF |\nD2 BG DGBG | FGAB c2 Bc | dggf d2 g2 | fdcA G2 |]',
    source: { ...SOURCE, where: 'No. 6, p. 6 (PDF page 22)' },
    transcription: READQ(22),
  },
  {
    id: 'joyce-037-the-job-of-journeywork',
    title: 'The Job of Journeywork',
    region: 'irish',
    kind: 'set-dance',
    key: 'D', mode: 'major', meter: '4/4',
    origin: 'Irish set dance in hornpipe time; a great favourite twenty or thirty years before 1873 in some of the Munster counties, and Joyce learned it from hearing it constantly played by pipers and fiddlers; an eight-bar first strain and a fourteen-bar second strain, each repeated, as printed; grace notes left out',
    tags: ['dance', 'hornpipe', 'irish'],
    abc: 'X:37\nT:The Job of Journeywork\nM:4/4\nL:1/8\nK:D\nfe | dcAG FGAB | =cB=cA cdef | dB=cA BGAF | GBAF DEFG |\nABAF GFEF | D2 DE F2 G2 | A2 d2 cdef | d2 dd d2 ::\nde | f2 ef gfef | d2 dc A2 de | f2 ef gfef | d2 dd d2 cd |\neaag f2 ed | dcde f2 ed | dcAG FGAB | =cB=cA cdef |\ndB=cA BGAF | GBAF DEFG | ABAF GFEF | D2 DE F2 G2 | A2 d2 cdef | d2 dd d2 :|',
    source: { ...SOURCE, where: 'No. 37, pp. 38-39 (PDF pages 54 and 55)' },
    transcription: READQ('54 and 55'),
  },
  {
    id: 'joyce-085-the-blooming-meadows',
    title: 'The Blooming Meadows',
    region: 'irish',
    kind: 'jig',
    key: 'G', mode: 'major', meter: '6/8',
    origin: 'Irish double jig, printed without a note of its source; headed No. 87 on the page and No. 85 in the contents',
    tags: ['jig', 'dance', 'irish'],
    irregular: 'the last bar of each strain holds five eighths (a dotted quarter and a quarter) before the repeat, as printed',
    abc: 'X:85\nT:The Blooming Meadows\nM:6/8\nL:1/8\nK:G\nD2G G2A | B2d cAG | F2D DED | F3 FED | DGG G2A | BAG ABc | d2B cAF | G3 G2 ::\ng2d def | g2a bag | f2d ded | f2g afd | g2d def | g2a bag | fed cAF | G3 G2 :|',
    source: { ...SOURCE, where: 'No. 85, p. 87 (PDF page 103)' },
    transcription: READQ(103),
  },
  {
    id: 'joyce-091-the-boys-of-the-town',
    title: 'The Boys of the Town',
    region: 'irish',
    kind: 'jig',
    key: 'D', mode: 'mixolydian', meter: '6/8',
    origin: 'Irish double jig, printed without a note of its source; one sharp, each strain ending on D',
    tags: ['jig', 'dance', 'irish'],
    abc: 'X:91\nT:The Boys of the Town\nM:6/8\nL:1/8\nK:Dmix\nd | d3/2c/B/A/ G2A | EDE G2B | AGA ABc | BGE E2D | d3/2c/B/A/ G2A | EDE G2B | AGE G2A | GED D2 ::\nc | BAB dBG | BAB dBG | AGA ABc | BGE E2c | BAB def | gfe dBG | AGE G2A | GED D2 :|',
    source: { ...SOURCE, where: 'No. 91, p. 93 (PDF page 109)' },
    transcription: READQ(109),
  },
  {
    id: 'joyce-094-strop-the-razor',
    title: 'Strop the Razor',
    region: 'irish',
    kind: 'jig',
    key: 'Bb', mode: 'major', meter: '6/8',
    origin: 'Irish double jig; Joyce had it from James Buckley, a Limerick piper; the A flats are printed in the music; grace notes left out',
    tags: ['jig', 'dance', 'irish'],
    abc: 'X:94\nT:Strop the Razor\nM:6/8\nL:1/8\nK:Bb\nFBB dBB | cAF _A2F | FBB dBB | dfd ecA | FBB dBB | cAF _A2B | _AGF A2B | cff ecB ::\nFBB B2c | F_AA A2B | FBB B2e | dff ecA | FBB B2c | F_AA A2B | _AGF A2B | cff ecB :|',
    source: { ...SOURCE, where: 'No. 94, p. 96 (PDF page 112)' },
    transcription: READQ(112),
  },
  {
    id: 'joyce-097-una',
    title: 'Una',
    region: 'irish',
    kind: 'song-air',
    key: 'A', mode: 'minor', meter: '4/4',
    origin: "Irish song air; Joyce learned this fine old melody from his father, and the Irish song to it was still current among the people of Cork and Limerick; he warns that it is a different melody from Oonagh, to which Moore wrote While gazing on the moon's light; printed with no key signature and ending on A; marked Slow and with expression",
    tags: ['air', 'slow', 'irish'],
    abc: 'X:97\nT:Una\nM:4/4\nL:1/8\nK:Am\nDE | G2 G3/2A/ G3/2E/ DE | G2 GA G3/2E/ DE | A2 A3/2B/ c2 E3/2F/ | G3 E D2 EG |\nA2 AB c2 A2 | d2 de f2 ed | cAGE D2 EG | A4 A2 ||\ncd | e2 ef e3/2d/ cA | d2 de f2 e3/2d/ | d3/2c/ AG E2 DE | G3 E D2 EG |\nA2 AB c2 cA | d2 d3/2e/ f2 ed | cAGE D2 EG | A4 A2 |]',
    source: { ...SOURCE, where: 'No. 97, p. 99 (PDF page 115)' },
    transcription: READQ(115),
  },
  {
    id: 'joyce-033-farewell-to-the-troubles-of-the-world',
    title: 'Farewell to the Troubles of the World',
    region: 'irish',
    kind: 'air',
    key: 'D', mode: 'major', meter: '6/8',
    origin: "Irish air, Gaelic title Slan agus beannacht le buairidhibh a' tsaoghail; Joyce took it down in 1853 from the whistling of Joseph Martin, a native of County Limerick; marked Gaily, but not so fast as jig time; one grace note left out",
    tags: ['air', 'irish'],
    abc: "X:33\nT:Farewell to the Troubles of the World\nM:6/8\nL:1/8\nK:D\nA | dec dcA | GFG AFD | FEF GFD | F3/2G/A/B/ c2 A |\ndec dcA | GFG AFD | F3 G2 A/G/ | FDD D2 ||\nG | FED FGA/B/ | =cdB cAG | Afe de^c | AB^c d2 =c |\nBBB d=cA | GFG AFD | F3 G2 A/G/ | FDD D2 |]",
    source: { ...SOURCE, where: 'No. 33, p. 35 (PDF page 51)' },
    transcription: READQ(51),
  },
  {
    id: 'joyce-099-my-fair-love-leaving-me',
    title: 'My Fair Love Leaving Me',
    region: 'irish',
    kind: 'air',
    key: 'E', mode: 'minor', meter: '3/4',
    origin: "Irish air, Gaelic title Mo ghradh ban am threigan; Joyce took it down from Lewis O'Brien of Coolfree, County Limerick; marked Slow and with feeling; one grace note left out",
    tags: ['air', 'slow', 'irish'],
    abc: "X:99\nT:My Fair Love Leaving Me\nM:3/4\nL:1/8\nK:Em\nGA | B2 B2 AG | df e3/2d/ BA | G2 EG F3/2E/ | E4 Bd |\ne2 egfe | e2 d2 ef | g2 fedB | d2 e2 Bd |\ne2 e3/2g/ fe | e2 d2 ef | g2 fedB | d2 e2 GA |\nB2 B3/2A/ GE | d2 e3/2d/ BA | G2 E3/2G/ F3/2E/ | E4 |]",
    source: { ...SOURCE, where: 'No. 99, p. 102 (PDF page 118)' },
    transcription: READQ(118),
  },
  {
    id: 'joyce-100-the-lake-of-coolfin',
    title: 'The Lake of Coolfin, or Willy Leonard',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '3/4',
    origin: 'Irish ballad air; Joyce took down the air and one verse of the song from Peggy Cudmore, and the ballad tells of the accidental drowning of young Willy Leonard; marked Andante; voice line read',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:100\nT:The Lake of Coolfin\nM:3/4\nL:1/8\nK:Eb\nGA | B2 E2 e3/2d/ | c2 A2 G/A/F | F2 E2 E2 | E4 de |\nf2 B2 e3/2d/ | c2 B2 AG | A2 B3/2G/ EG | F4 d3/2e/ |\nf2 B2 e3/2d/ | c2 B2 AG | A2 BG E3/2G/ | F4 GA |\nB2 e2 de | c2 A2 (3GAF | F2 E2 E2 | E4 |]',
    source: { ...SOURCE, where: 'No. 100, p. 103 (PDF page 119)' },
    transcription: READQ(119),
  },
];

export default TUNES;
