// settle-hear · tunes/mckay1878 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book: wikis/WIKI_OLD_MELODIES/books/BOOK_MCKAY1878.md. Pipe music prints no key signature, so every tune is
// K:HP (the pipe scale: F sharp and C sharp). The gracings (grace notes, doublings, grips) are left out; the
// melody is the line of large notes with their stems down. PDF page = printed page + 10.

export const SOURCE = {
  kind: 'print',
  book: 'The Tutor for the Highland Bagpipe, with a selection of marches, quicksteps, strathspeys, reels and jigs',
  compiler: 'William McKay (1841), corrected and improved by Angus McKay (1843), 7th edition',
  year: 1878,
  scan: 'https://archive.org/details/nd317340746',
};

const T = (n) => `read from the scan (PDF page ${n}, each staff in quarters at 600 dpi) and proofed bar by bar by lane MELODIES200 reader mckay1878, 2026-10-03`;

export const TUNES = [
  {
    id: 'mckay-p8-the-haughs-of-cromdale',
    title: 'The Haughs of Cromdale',
    region: 'scottish',
    kind: 'march',
    key: 'A', mode: 'mixolydian', meter: 'C',
    origin: 'Highland pipe tune, Gaelic title as printed Sud mar chaidh an cal a dholaidh; printed in common time with no type label, two strains each repeated',
    tags: ['highlands', 'march', 'scottish'],
    abc: 'X:1\nT:The Haughs of Cromdale\nM:C\nL:1/8\nK:HP\na | e A3/2A/ A e3/2d/ B3/2d/ | e3/2A/ AB/ G3/2A/ B3/2d/ | e A3/2A/ A e3/2d/ B3/2d/ | e3/2B/ g3/2B/ A3/2A/ A :|\n|: a | e3/2d/ e3/2f/ g3/2a/ g3/2e/ | d3/2e/ d3/2B/ d3/2e/ d3/2B/ | e3/2d/ e3/2f/ g3/2a/ g3/2e/ | d3/2B/ g3/2B/ A3/2A/ A :|',
    source: { ...SOURCE, where: 'p. 8 (PDF page 18)' },
    irregular: 'bar 2 prints a dotted e, a sixteenth A, an undotted A and a sixteenth B in its first half, a sixteenth short of the bar; the A probably wants a dot, kept as printed',
    transcription: T(18),
  },
  {
    id: 'mckay-p8-the-campbells-are-coming',
    title: 'The Campbells are coming',
    region: 'scottish',
    kind: 'march',
    key: 'A', mode: 'mixolydian', meter: '6/8',
    origin: 'Highland pipe tune, Gaelic title as printed Bail\' Inbheraora (the town of Inveraray); printed in 6/8 with no type label, two strains each repeated',
    tags: ['highlands', 'march', 'scottish'],
    abc: 'X:1\nT:The Campbells are coming\nM:6/8\nL:1/8\nK:HP\nG |: B3/2d/ e dBG | B3/2B/ B B2A | B3/2d/ e dBG | A3/2A/ A A/A3/2G |\nB3/2d/ e dBd | GAB g2a | geg dBG | A3/2B/ A A/A3/2G :|\n|: g2e g2a | d2e dBd | g2e agf | eae g2B |\nd2e dBd | GAB g2a | geg dBG | A3/2B/ A A2G :|',
    source: { ...SOURCE, where: 'p. 8 (PDF page 18)' },
    transcription: T(18),
  },
  {
    id: "mckay-p7-king-robert-bruces-march",
    title: "King Robt. Bruce's March",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "C|",
    origin: "Highland pipe march, Gaelic title as printed Titi Taiti; printed in cut common time, two strains each repeated",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:King Robt. Bruce's March\nM:C|\nL:1/8\nK:HP\n|: A3/2A/ A3/2B/ A B/c/ d3/2c/ | B3/2c/ B3/2A/ B3/2c/ d3/2e/ | f3/2g/ e3/2f/ d3/2e/ f3/2e/ | d3/2B/ B3/2A/ A3 e :|\n|: fg f3/2e/ f3/2g/ a3/2f/ | e3/2f/ e3/2d/ e3/2f/ g2 | a3/2f/ e3/2f/ d3/2e/ f3/2e/ | d3/2B/ B3/2A/ A3 e :|",
    source: { ...SOURCE, where: "p. 7 (PDF page 17)" },
    transcription: T(17),
  },
  {
    id: "mckay-p27-sir-iain-cope",
    title: "Sir Iain Cope",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "Highland pipe tune, the air of Johnny Cope; printed with the line Sir John Cope's challenge to Prince Charles in 1745 (the print spells it Prine); two strains, each opening with a quarter-note pickup",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:Sir Iain Cope\nM:2/4\nL:1/8\nK:HP\ne2 | A2 AB/d/ | eA BA/B/ | G2 GA/B/ | dG/g/ e/d/B/G/ | A2 GA/B/ |\neA BA/G/ | Ag e/d/c/B/ | AA/A3/2 ||\ne2 | A2 AB/d/ | e/d/c/B/ A2 | BA/B/ GA/B/ | cB/A/ G2 | cB/c/ dB/d/ |\neg BA/G/ | Ag e/d/c/B/ | AA/A3/2 |]",
    source: { ...SOURCE, where: "p. 27 (PDF page 37)" },
    irregular: "the last bar of each strain prints A, A and a dotted A under one beam, three eighths in a 2/4 bar, as printed",
    transcription: T(37),
  },
  {
    id: "mckay-p48-lochaber-no-more",
    title: "Lochaber no more",
    region: 'scottish',
    kind: "air",
    key: "A", mode: "mixolydian", meter: "3/4",
    origin: "Scottish slow air, set for the Highland pipe; Gaelic title as printed Gleann Gallaidh nan Craobh; three strains, the first repeated, the third a variant of the second",
    tags: ["highlands", "air", "slow", "lament", "scottish"],
    abc: "X:1\nT:Lochaber no more\nM:3/4\nL:1/8\nK:HP\nAB c2 c2 | e2 c2 B2 | ce f2 B2 | Bc B4 | AB c2 c2 | ec B2 AG | AB c2 A2 | B2 A4 :|\nAc e2 e2 | ef e2 dc | Bc f2 B2 | Bc B4 | AB c2 a2 | ec B3 AG | AB c2 A2 | B2 A4 ||\nAc e2 e2 | ef e2 dc | Bc f2 B2 | cA a4 | AB c2 a2 | ec B2 AG | AB c2 A2 | B2 A4 |]",
    source: { ...SOURCE, where: "p. 48 (PDF page 58)" },
    irregular: 'second strain, bar 6 prints a dot after the B, which makes the bar seven eighths long; the same bar in the first and third strains has no dot; kept as printed',
    transcription: T(58),
  },
  {
    id: "mckay-p35-kenmures-on-and-awa",
    title: "Kenmure's on and awa",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Scottish Jacobite air set for the Highland pipe; Gaelic title as printed Alasdair Garbh; printed in 6/8 with no type label, two strains each repeated",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:Kenmure's on and awa\nM:6/8\nL:1/8\nK:HP\ne |: Ace aec | efe e2c | Ace aec | BGB B/B3/2e | Ace aec | efg agf | edc dcB | A3/2A/A A2 :|\ng |: a2e fec | efe efg | a2e fec | BGB B/B3/2g | a2e fec | efg agf | edc dcB | A3/2A/A A2 :|",
    source: { ...SOURCE, where: "p. 35 (PDF page 45)" },
    transcription: T(45),
  },
  {
    id: "mckay-p11-duncan-gray",
    title: "Duncan Gray",
    region: 'scottish',
    kind: "quickstep",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "Scottish song air set for the Highland pipe in 2/4; Gaelic title as printed Rob Ruadh Mac Ghriogair; no type label; the first strain repeated",
    tags: ["highlands", "march", "dance", "scottish"],
    abc: "X:1\nT:Duncan Gray\nM:2/4\nL:1/8\nK:HP\ne |: Adcd | ef c2 | d2 e/f/g/e/ | fd d2 :|\nfa a g/f/ | g g/a/ g2 | gf ed | c/d/e/c/ A2 |\na g/f/ g f/e/ | f/g/a/g/ f/e/d/c/ | d2 e/f/g/e/ | fd d2 |]",
    source: { ...SOURCE, where: "p. 11 (PDF page 21)" },
    transcription: T(21),
  },
  {
    id: "mckay-p17-drops-of-brandy",
    title: "Drops of Brandy",
    region: 'scottish',
    kind: "slip-jig",
    key: "A", mode: "mixolydian", meter: "9/8",
    origin: "Scottish dance tune set for the Highland pipe in 9/8; Gaelic title as printed Dideag Chunna' mi Sgoireiceag; two strains each repeated",
    tags: ["highlands", "jig", "slip-jig", "dance", "scottish"],
    abc: "X:1\nT:Drops of Brandy\nM:9/8\nL:1/8\nK:HP\nf |: e2d cAc cAc | e2d cAc d2B | e2d cAc cAc | d2c BGB d2B :|\n|: Ace aec aec | Ace bec d2B | Ace aec aec | d2c BGB d2B :|",
    source: { ...SOURCE, where: "p. 17 (PDF page 27)" },
    transcription: T(27),
  },
  {
    id: "mckay-p17-the-isle-of-skye-local-militias-march",
    title: "The Isle of Skye Local Militia's March",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "Highland pipe march; Gaelic title as printed Na Bi goid na Coille orm; the first strain is repeated, and the second strain opens with a repeat sign but closes with a plain double bar, as printed",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:The Isle of Skye Local Militia's March\nM:2/4\nL:1/8\nK:HP\nf/e/ |: dB B A/B/ | dA A f/e/ | dB B A/B/ | f2 e/g/f/e/ |\ndB B A/B/ | dA A f/e/ | dB B A/B/ | f2 f e/d/ :|\n|: de f e/f/ | ae e f/e/ | de f e/f/ | a2 b d/e/ |\nf2 f e/f/ | be e f/e/ | dB B A/B/ | f2 e/g/f/e/ |]",
    source: { ...SOURCE, where: "p. 17 (PDF page 27)" },
    transcription: T(27),
  },
  {
    id: "mckay-p15-blythe-blythe-and-merry-was-she",
    title: "Blythe Blythe and merry was she",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "Scottish song air set for the Highland pipe in 2/4; Gaelic title as printed Maireared Mhin, Mholach; no type label; the first strain repeated, the second written out",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:Blythe Blythe and merry was she\nM:2/4\nL:1/8\nK:HP\na/f/ |: e2 A B/c/ | dA BG | e2 dg | e d/B/ A2 :|\nGB ga | ge gd | ed eg | ag e2 |\ndega | ge dg | ed Bg | e d/B/ A2 |]",
    source: { ...SOURCE, where: "p. 15 (PDF page 25)" },
    transcription: T(25),
  },
  {
    id: "mckay-p15-the-duke-of-atholls-march",
    title: "Duke of Atholl's March",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Highland pipe march; Gaelic title as printed Rachainn a' mhire ri Nighinn ghlain oig; the first strain repeated; the second strain opens with a repeat sign but closes with a plain double bar, as printed",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:Duke of Atholl's March\nM:6/8\nL:1/8\nK:HP\nd |: c2e e3/2c/e | f3/2d/f ecA | c2e efg | BGB B2d |\nc2e e3/2c/e | f3/2d/f ecA | cec dBG | A3/2B/A A2 :|\n|: g | a2f g2e | f3/2d/f ecA | a2e g2d | BGB B2g |\nb2f g2e | f2d ecA | cec dBG | A3/2B/A A2 |]",
    source: { ...SOURCE, where: "p. 15 (PDF page 25)" },
    transcription: T(25),
  },
  {
    id: "mckay-p32-mary-gray",
    title: "Mary Gray",
    region: 'scottish',
    kind: "quickstep",
    key: "A", mode: "mixolydian", meter: "C|",
    origin: "Scottish tune set for the Highland pipe in cut common time; Gaelic title as printed Dubh a' Chailleach, dubh a breid; no type label; two strains each repeated",
    tags: ["highlands", "march", "dance", "scottish"],
    abc: "X:1\nT:Mary Gray\nM:C|\nL:1/8\nK:HP\na |: eAcA dG B2 | eAce ae c2 | eAcA dGBd | ecdB A3/2A/A :|\n|: e | G3/2G/GB dG B2 | A3/2A/Ae ae c2 | G3/2G/GB dGBd | ecdB A3/2A/A :|",
    source: { ...SOURCE, where: "p. 32 (PDF page 42)" },
    transcription: T(42),
  },
  {
    id: "mckay-p33-johnnie-lad",
    title: "Johnnie Lad",
    region: 'scottish',
    kind: "reel",
    key: "A", mode: "mixolydian", meter: "C|",
    origin: "Scottish tune set for the Highland pipe in cut common time; Gaelic title as printed Domhnull a bh'air a' Ghille; no type label; a four-bar first strain repeated, then an eight-bar second strain",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Johnnie Lad\nM:C|\nL:1/8\nK:HP\ne/d/ |: B2 GB A3/2A/ AB | dBAB efgd | B2 GB A3/2A/ Ad | BcdB e2 ef :|\nefge f d/d3/2 f | efge f2 ed |\nefge f d/d3/2 f | edBd e2 ef | efge f d/d3/2 f | efge f2 ed |\nefge aefd | edBd efgd |]",
    source: { ...SOURCE, where: "p. 33 (PDF page 43)" },
    transcription: T(43),
  },
  {
    id: "mckay-p42-the-new-rigged-ship",
    title: "The New Rigged Ship",
    region: 'scottish',
    kind: "jig",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Highland pipe jig; Gaelic title as printed Port na Luinge; no type label; two strains each repeated; the opening run before the first repeat is printed in grace-note size and is left out",
    tags: ["highlands", "jig", "dance", "scottish"],
    abc: "X:1\nT:The New Rigged Ship\nM:6/8\nL:1/8\nK:HP\n|: d3 d2f | d3 d2f | ecA Acd | ecA ABc | d3 d2f | d3 c2A | Bcd ecA | d3 A2B :|\n|: a2d a2f | d3 def | a2d a2f | e3 efg | a2d a2f | e2d c2A | Bcd ecA | d3 A2f :|",
    source: { ...SOURCE, where: "p. 42 (PDF page 52)" },
    transcription: T(52),
  },
  {
    id: "mckay-p38-lochiels-march",
    title: "Piobaireachd Dhomhnuill Duibh, or Lochiel's March",
    region: 'scottish',
    kind: "march",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Highland pipe march, the pibroch of Donald Dubh (Lochiel's March); the print gives the theme in the first staff and three variations after it; the theme alone is written here",
    tags: ["highlands", "march", "scottish"],
    abc: "X:1\nT:Piobaireachd Dhomhnuill Duibh, or Lochiel's March\nM:6/8\nL:1/8\nK:HP\ne c/c3/2 fga | e c/c3/2 c2A | e c/c3/2 fga | ecA B2A |\ne c/c3/2 fga | e c/c3/2 cBA | B2c def | ecA B2A |]",
    source: { ...SOURCE, where: "p. 38 (PDF page 48)" },
    transcription: T(48),
  },
  {
    id: "mckay-p50-marys-dream",
    title: "Mary's Dream",
    region: 'scottish',
    kind: "air",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "Scottish song air set for the Highland pipe in 2/4; Gaelic title as printed Aisling Mairi; two strains each repeated",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:Mary's Dream\nM:2/4\nL:1/8\nK:HP\nc/d/ | eA A c/d/ | e/d/e/f/ e/d/c/d/ | eA A B/c/ | d/c/B/A/ G e/d/ |\ncA A G/A/ | c/B/c/d/ e d/c/ | d/e/g/a/ g/e/d/e/ | cA A :|\n|: f/g/ | aa e d/c/ | d/c/d/e/ g f/g/ | aa e d/c/ | d/c/B/A/ G e/d/ |\ncA A G/A/ | c/B/c/d/ e d/c/ | d/e/g/a/ g/e/d/e/ | cA A :|",
    source: { ...SOURCE, where: "p. 50 (PDF page 60)" },
    transcription: T(60),
  },
  {
    id: "mckay-p54-gille-calum",
    title: "Gille Calum",
    region: 'scottish',
    kind: "set-dance",
    key: "A", mode: "mixolydian", meter: "2/4",
    origin: "The Highland sword dance tune, set for the pipe; English title as printed The Sword Dance; two strains each repeated, in Scotch snaps and dotted pairs",
    tags: ["highlands", "dance", "scottish"],
    abc: "X:1\nT:Gille Calum\nM:2/4\nL:1/8\nK:HP\na |: A/A3/2 c3/2A/ | d2 B3/2G/ | A/A3/2 c3/2A/ | d2 c3/2A/ | d2 c3/2A/ | d2 B3/2G/ | A/A3/2 c3/2A/ | d3/2B/ e2 :|\n|: A/A3/2 c3/2A/ | g2 B3/2G/ | A/A3/2 c3/2A/ | a2 af | g3/2a/ g3/2e/ | d2 B3/2G/ | A/A3/2 c3/2A/ | d3/2B/ e2 :|",
    source: { ...SOURCE, where: "p. 54 (PDF page 64)" },
    transcription: T(64),
  },
  {
    id: "mckay-p56-an-tailear-fidhleir",
    title: "An Tailear Fidhleir",
    region: 'scottish',
    kind: "jig",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Highland pipe jig; English title as printed The Forest; the first strain repeated; the second strain opens with a repeat sign and closes with a plain double bar, as printed",
    tags: ["highlands", "jig", "dance", "scottish"],
    abc: "X:1\nT:An Tailear Fidhleir\nM:6/8\nL:1/8\nK:HP\ng |: G3/2G/G BGB | d2e g2a | G3/2G/G BGe | dBA AAg | G3/2G/G BGB | d2e g2e | agf g2e | dBA AAg :|\n|: e3/2A/e edB | dGd dBd | e3/2A/e edB | dBA AAg | e3/2A/e edB | d2e g2e | agf g2e | dBA AAg |]",
    source: { ...SOURCE, where: "p. 56 (PDF page 66)" },
    transcription: T(66),
  },
  {
    id: "mckay-p56-free-and-an-accepted-mason",
    title: "Free and an Accepted Mason",
    region: 'scottish',
    kind: "jig",
    key: "A", mode: "mixolydian", meter: "6/8",
    origin: "Highland pipe jig; Gaelic title as printed Port nan Clachairean; two four-bar strains, each repeated",
    tags: ["highlands", "jig", "dance", "scottish"],
    abc: "X:1\nT:Free and an Accepted Mason\nM:6/8\nL:1/8\nK:HP\nA | d3/2e/f/g/ fed | cde e/f/e/c/B/A/ | d3/2e/f/g/ fed | faa a2 :|\n|: g | fab a2 a/g/ | fed a2f | gfg eab/a/ | fdd d2 :|",
    source: { ...SOURCE, where: "p. 56 (PDF page 66)" },
    transcription: T(66),
  },
];

export default TUNES;
