// settle-hear · tunes/oneill1903-reels - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.

export const SOURCE = {
  kind: 'print',
  book: "O'Neill's Music of Ireland: Eighteen Hundred and Fifty Melodies",
  compiler: "Capt. Francis O'Neill, arranged by James O'Neill",
  year: 1903,
  scan: 'https://archive.org/details/oneills-1850',
};

const READ = (pdf) => `read from the scan (PDF page ${pdf}, each staff in short windows at about 450 to 900 dpi equivalent, ledger notes checked on the native pixels) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-02`;

export const TUNES = [
  {
    id: 'oneill-1199-the-bucks-of-oranmore',
    title: 'The Bucks of Oranmore',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel in four strains, printed without repeats; the print credits McFadden. A segno printed over the first bar has no matching D.S. on the page and is left out',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Bucks of Oranmore\nM:C|\nL:1/8\nK:D\ndB|A2FA A2dB|(3ABA FA BEE z|A2FA A2Bd|(3efg fd ecdB|\nA2FA A2dB|(3ABA FA BEEF|DEFG AFAB|defd ecdB||\nAD (3FED A2dB|ADFA BEE z|AD (3FED A2Bd|(3efg fd ecdB|\nAD (3FED A2dB|AD (3FED BEE z|DEFG AFAB|defd efge||\n(3aba fd eddf|(3aba fd eBB z|(3aba fd eddf|(3efg fd eBB z|\n(3aba fd eddf|(3aba fd eBB z|(3aba fd eddf|(3gfe fd eBBd||\n(3fgf df (3efe de|(3fgf df eBB z|(3fgf df (3efe df|(3efg fd eBBd|\n(3fgf df (3efe de|(3fgf df eBB z|faaf bfaf|(3efg fd ecdB|]',
    source: { ...SOURCE, where: 'No. 1199, p. 226 (PDF page 237)' },
    transcription: READ(237),
  },
  {
    id: 'oneill-1186-the-bank-of-ireland',
    title: 'The Bank of Ireland',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Teac-inmhuis n-Eirinn; the print credits J. O\'Neill. The second strain is printed once, without a repeat; a segno over the first bar and another at the final bar line have no D.S. on the page and are left out',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Bank of Ireland\nM:C|\nL:1/8\nK:D\ned|:cAAB cABG|EGDG EGDB|cAAB cABG|1 Addc defd:|2 Addc d2||de|\nf2fd e2ec|dfed cAAg|f2fe e2ed|eaag eddz|\nfgaf efge|dfed cAAG|Addc defg|afge dfed|]',
    source: { ...SOURCE, where: 'No. 1186, p. 224 (PDF page 235)' },
    transcription: READ(235),
  },
  {
    id: 'oneill-1229-the-ewe-reel',
    title: 'The Ewe Reel',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Seisd an Aisg; the print credits Kennedy. The second strain is printed once, without a repeat',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Ewe Reel\nM:C|\nL:1/8\nK:G\n|:DGGF DGGF|F2AF cFAF|DGGF DGGg|1 fdcA BGAF:|2 fdcA BG G2||\ng2bg dgbg|f2af dfaf|g2bg dgbg|agfa g2ga|\nbgaf gdde|fefd cAGF|dggf (3gab ag|fdcA BGAF|]',
    source: { ...SOURCE, where: 'No. 1229, p. 231 (PDF page 242)' },
    transcription: READ(242),
  },
  {
    id: 'oneill-1243-the-mountain-lark',
    title: 'The Mountain Lark',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Fuiseog on Sliabh; printed as No. 1 of two settings, the print credits Kennedy. Both strains are printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Mountain Lark\nM:C|\nL:1/8\nK:G\nD2BA Bdef|deBd AFDF|E2BA Bdef|dBAF BEEz|\nD2BA Bdef|deBd AFDF|E2BA Bdef|gefd Beez||\neBB2 efge|fdad bdad|eBB2 efge|fe^df e2ef|\neBBB efge|fdad bdad|gafg egfe|dBAF BEEz|]',
    source: { ...SOURCE, where: 'No. 1243, p. 234 (PDF page 245)' },
    transcription: READ(245),
  },
  {
    id: 'oneill-1239-the-jolly-journeyman',
    title: 'The Jolly Journeyman',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Fear-aonlae Sugach. The second strain is printed once, without a repeat',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Jolly Journeyman\nM:C|\nL:1/8\nK:G\nG2BG ABcA|eBcA eBcA|G2BG ABcA|eBcA BGG2:|\ng2fg agfd|eBcA eBcA|g2fg agfd|eBcA BGG2|\ng2fg agfd|eBcA eBcA|G2BG ABcA|eBcA BGG2|]',
    source: { ...SOURCE, where: 'No. 1239, p. 233 (PDF page 244)' },
    transcription: READ(244),
  },
  {
    id: 'oneill-1238-the-flower-of-the-flock',
    title: 'The Flower of the Flock',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Blath na Treada. The second strain is printed once, without a repeat',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Flower of the Flock\nM:C|\nL:1/8\nK:G\nGE|DEGA BGGB|cABG AGEG|DEGA BABc|dBAB G2:|\n(3def|g2ge d2dB|AcBG AGEG|g2ge d2d2|eaab agef|\ngfge dedB|cABG AGEG|DEGA BABc|dBAB G2|]',
    source: { ...SOURCE, where: 'No. 1238, p. 233 (PDF page 244)' },
    transcription: READ(244),
  },
  {
    id: 'oneill-1240-the-green-fields-of-america',
    title: 'The Green Fields of America',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Na Paircibh Glais America; the index of the book gives a second title, Charming Mollie Brallaghan; the print credits F. O\'Neill. Both strains are printed once, without repeats; a pair of dots before the time signature has no matching repeat sign and is left out',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Green Fields of America\nM:C|\nL:1/8\nK:G\nc2ec B2dB|AGAB AGEF|GAGE DEGB|AGAB AGEG|\nc2ec B2dB|AGAB AGEF|GAGE DEGA|BGAF G2z2||\nGABc d2ef|gage dBGB|c2ec B2dB|AGAB AGE2|\ngfgd efge|dcBG AGEF|GAGE DEGA|BGAF G2z2|]',
    source: { ...SOURCE, where: 'No. 1240, p. 233 (PDF page 244)' },
    transcription: READ(244),
  },
  {
    id: 'oneill-1232-the-day-we-paid-the-rent',
    title: 'The Day We Paid the Rent',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title An La\'do Dhiolamar an Cios. The second strain is printed once, without a repeat',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Day We Paid the Rent\nM:C|\nL:1/8\nK:G\nge|:dGBG dGBe|dGBG FGAe|dGBG dGBd|1 efga bage:|2 efga bg g2||\nbagf gdBd|egdB BAA2|bagf gdBd|egea g2ga|\nbagf gdBd|egdB BAAc|BGdG eGdG|egfa g2|]',
    source: { ...SOURCE, where: 'No. 1232, p. 232 (PDF page 243)' },
    transcription: READ(243),
  },
  {
    id: 'oneill-1306-the-snow-on-the-hills',
    title: 'The Snow on the Hills',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Sneachd air na Chnuichibh; the print credits Lawson. Printed with one sharp and ending on A, so read as A dorian by the rule of the final note, though each strain opens on G. Both strains are printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Snow on the Hills\nM:C|\nL:1/8\nK:Ador\nG2dG BGdG|GABd cAFA|G2dG Bcde|fdcB cAFA|\nG2dG BGdG|GABd cAFA|GABc dfeg|fdcA GABc||\ndgga bgaf|dggf d2cA|dgga bgag|fdcA GABc|\ndgga bgag|dggf defg|abag fgfe|defd cAFA|]',
    source: { ...SOURCE, where: 'No. 1306, p. 245 (PDF page 256)' },
    transcription: READ(256),
  },
  {
    id: 'oneill-1224-toss-the-feathers',
    title: 'Toss the Feathers',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Umpuig na Clumac; printed as the 1st setting of two, the print credits J. O\'Neill. The print ends the second strain with D.C. and marks a pause on the last note of the second ending, written out here as the first strain once more to that pause. Octave double stops are given by their top note',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Toss the Feathers\nM:C|\nL:1/8\nK:D\n|:D2AD EDA>d|D2AG EGG>e|D2AD EDEG|1 AddB cAGE:|2 AcGE AD D2||\nAd2d d2cd|edcd edcd|edad fdad|edce edce|\nea2^g e=g2e|dfed cAGE|D2ED EAAB|cded cAGE||\nD2AD EDA>d|D2AG EGG>e|D2AD EDEG|AcGE AD D2|]',
    source: { ...SOURCE, where: 'No. 1224, p. 231 (PDF page 242)' },
    transcription: READ(242),
  },
  {
    id: 'oneill-1284-the-musical-priest',
    title: 'The Musical Priest',
    region: 'irish',
    kind: 'reel',
    key: 'B', mode: 'minor', meter: 'C|',
    origin: 'Irish reel in three strains, Gaelic title An t-Sagart Ceolmhar; the print credits McFadden. The first strain is repeated and marked with a pause on its last note; the third strain ends with D.C., written out here as the first strain once more to that pause',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Musical Priest\nM:C|\nL:1/8\nK:Bm\nBA|FBBA BABd|cBAf ecBA|FBBA B2Bd|cBAc B2:|\nBc|d2dc dfed|cAeg faec|d2dc defb|afec B2Bc|\ndcdc dfed|cAeg faec|dcBc defb|afec B2||\nBc|d>B (3BBB bafb|afec ABce|d>B (3BBB bafb|afec B2de|\nfbbc\' bafb|afec ABce|dcBc defb|afec dBcA||\nBA|FBBA BABd|cBAf ecBA|FBBA B2Bd|cBAc B2|]',
    source: { ...SOURCE, where: 'No. 1284, p. 241 (PDF page 252)' },
    transcription: READ(252),
  },
  {
    id: 'oneill-1267-the-merry-sisters',
    title: 'The Merry Sisters',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel in three strains, Gaelic title Na Dearbhsiuire Sugach; the print credits Mrs. Cantwell. Printed with one sharp; the first strain closes on E with a rest and the last strain ends on A, so read as A dorian by the rule of the final note. The second and third strains are printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Merry Sisters\nM:C|\nL:1/8\nK:Ador\n|:B>E (3FED BdcA|B>E (3FED dAFA|B>E (3FED BdcA|1 d>D (3DDD ADFA:|2 dAFB E2 z2||\nBee^c d2cA|Bee^c dAFA|Bee^c d2cA|BAB^c dAFA|\nBee^c d2cA|Bee^c defg|(3agf (3gfe fdec|BABc dAFA||\nBdcA BFAF|B>E (3EEE BEFA|BdcA BFAF|d>D (3DDD ADFA|\nBdcA BFAF|B>E (3EEE BEFA|DFA^c d2eg|fde^c dAFA|]',
    source: { ...SOURCE, where: 'No. 1267, p. 238 (PDF page 249)' },
    transcription: READ(249),
  },
  {
    id: 'oneill-1268-the-swallows-tail',
    title: 'The Swallow\'s Tail',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Earbuill Ainleog; the print credits F. O\'Neill. Printed with three sharps and naturals on many G\'s; both strains are written out in full, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Swallow\'s Tail\nM:C|\nL:1/8\nK:A\ngf|eA (3cBA eAcA|cdef gedB|=G2BG dGBG|cdef =g2fg|\neA (3cBA eAcA|cdef =g2fg|af=ge dB=GB|AcBG A2||\ncd|eaag abag|e^def gedB|=G2BG dGBG|cdef =g2f^g|\neaag abag|e^def =g2f^g|af=ge dB^GB|AcBG A2|]',
    source: { ...SOURCE, where: 'No. 1268, p. 238 (PDF page 249)' },
    transcription: READ(249),
  },
  {
    id: 'oneill-1300-the-woman-of-the-house',
    title: 'The Woman of the House',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Bean a Tighe Air Lar; the print credits F. O\'Neill. The first and second endings of the first strain are each two bars long; the second strain is written out twice in full, the second time with variations',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Woman of the House\nM:C|\nL:1/8\nK:G\n|:G>B (3BAB cBAB|GBdg e2d2|1 G>B (3BAB cBAB|e>A (3AGA e>A (3AGA:|2 G2BG A2GA|BcAc BG G2||\nf2fd e2ed|gfge dBGB|f2fd e2ed|e>A (3AAA e>A (3AAA|\nf2fd e2ed|gfge dBGB|G2BG A2GA|BcAc BG G2||\nf2fd e2ed|gfge dBGB|f2fd e2ed|eA (3AAA eA (3AAA|\ngaba gfed|efge dBAB|G2BG A2GA|BcAc BG G2|]',
    source: { ...SOURCE, where: 'No. 1300, p. 244 (PDF page 255)' },
    transcription: READ(255),
  },
  {
    id: 'oneill-1425-drowsy-maggie',
    title: 'Drowsy Maggie',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Mairgreadin Taimeac; the print credits J. O\'Neill. The first strain is printed with one sharp and the second with two; every C in the first strain carries a sharp, so the tune is written here with two sharps throughout, which changes no note. Both strains are written out twice in full',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Drowsy Maggie\nM:C|\nL:1/8\nK:D\nE2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFD|\nE2BE dEBE|E2BE AFDF|E2BE dEBE|BABc dAFA||\nd2fd c2ec|defg afge|d2fd c2ec|BABc dAFA|\nd2fd c2ec|defg afge|afge fdec|BABc dAFD|]',
    source: { ...SOURCE, where: 'No. 1425, p. 264 (PDF page 275)' },
    transcription: READ(275),
  },
  {
    id: 'oneill-1424-sleepy-maggie',
    title: 'Sleepy Maggie',
    region: 'irish',
    kind: 'reel',
    key: 'E', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel in three strains, Gaelic title Mairgreadin Codluigteac; the print credits J. O\'Neill. Printed with two sharps and every strain closes on E, so read as E dorian by the rule of the final note. The first two strains are written out in full; the short third strain is repeated',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Sleepy Maggie\nM:C|\nL:1/8\nK:Edor\nf2de fBde|f2df eAce|f2de fBde|fgaf eAce|\nf2de fBde|f2df eAce|f2de fBde|fgaf eAce||\nfBdB fBde|fBdB eAce|fBdB eBde|f^gaf eAce|\nfBdB fBde|fBdB eAce|dcBc defg|abaf eAce||\n|:fBbB fBde|fBbB aAce|fBbB aB^gB|fB^gB aAce:|',
    source: { ...SOURCE, where: 'No. 1424, p. 264 (PDF page 275)' },
    transcription: READ(275),
  },
  {
    id: 'oneill-1418-miss-mcleods-reel',
    title: 'Miss McLeod\'s Reel',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'dorian', meter: 'C|',
    origin: 'Reel printed as the Irish version, Gaelic title Seisd Ingean ui Mic Leod; no player is named. Printed with one sharp; both strains close on A, so read as A dorian by the rule of the final note. Both strains are printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Miss McLeod\'s Reel\nM:C|\nL:1/8\nK:Ador\nBA|G2BG DGBG|B2BA BcBA|G2BG DGBG|A2AG AcBA|\nG2BG DGBG|B2BA B2d2|e3f edef|gedB AcBA||\nG2gf edeg|B2BA BcBA|G2gf edeg|a2ag ac\'ba|\ng2gf edeg|BcBA B2d2|efed cdef|gedB A2|]',
    source: { ...SOURCE, where: 'No. 1418, p. 263 (PDF page 274)' },
    transcription: READ(274),
  },
  {
    id: 'oneill-1305-the-pure-drop',
    title: 'The Pure Drop',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Braon Glan; the print credits Cronin. Both strains are printed once, without repeats, and each closes on C sharp leading back to the opening D',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Pure Drop\nM:C|\nL:1/8\nK:D\nd3/2D/ (3DDD FDFA|d2ef gfge|d3/2D/ (3DDD FDFA|BEEF GABc|\nd3/2D/ (3DDD FDFA|d2ef g2fg|afge fdec|BEEF GABc||\nd2fd adfd|d2ef g2fe|d2fd adfd|BEEF GABc|\nd2fd adfd|d2ef g2fg|afge fdec|BEEF GABc|]',
    source: { ...SOURCE, where: 'No. 1305, p. 245 (PDF page 256)' },
    transcription: READ(256),
  },
  {
    id: 'oneill-1406-the-pigeon-on-the-gate',
    title: 'The Pigeon on the Gate',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Colm air an Gata; the print credits F. O\'Neill. Printed with one sharp; the first strain repeats with first and second endings of two bars each, and the tune ends on A, so read as A dorian by the rule of the final note. The second strain begins with a two-note pickup that completes the short last bar of the second ending, and is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Pigeon on the Gate\nM:C|\nL:1/8\nK:Ador\ngf|e3/2A/ (3AAA egfg|e3/2A/ (3AAA e2dB|1 G2BG dGBG|GBdf g2fg:|2 GBdf g2ga|bagb a2||\nag|eaag abag|eaab c\'bag|eggf gage|dega bgag|\neaag abag|eaab c\'bag||edef gage|dBGB A2|]',
    source: { ...SOURCE, where: 'No. 1406, p. 261 (PDF page 272)' },
    transcription: READ(272),
  },
  {
    id: 'oneill-1401-julia-delaney',
    title: 'Julia Delaney',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Sighile ni Dhelanaigh; the print credits F. O\'Neill. The first strain repeats with first and second endings; the second strain is printed once, without repeats, and closes on E leading back to the opening D',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Julia Delaney\nM:C|\nL:1/8\nK:D\ndcAG (3EFG DE|G2AG EGG2|dcAG (3EFG DG|1 Addc defe:|2 Addc d2d2||\ncdef g2fg|agef g2ed|cdef g2AG|Addc dfed|\ncdef g2fg|(3agf ef g2fg|(3agf (3gfe (3fed (3edc|d2dc defe|]',
    source: { ...SOURCE, where: 'No. 1401, p. 260 (PDF page 271)' },
    transcription: READ(271),
  },
  {
    id: 'oneill-1295-the-blackberry-blossom',
    title: 'The Blackberry Blossom',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel, Gaelic title Blath na Smeur; the print credits F. O\'Neill. Printed with one sharp and a sharpened G before the high A at each strain end; both strains close on A, so read as A dorian by the rule of the final note. The four-bar first strain repeats; the second strain is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Blackberry Blossom\nM:C|\nL:1/8\nK:Ador\nge|dBAc BAGA|BcBA B2ge|dBAc BGGB|Aaa^g a2:|\nef|gfge gbaf|gfga beef|gfga bagf|eaa^g a2ef|\ngfge gbaf|gfga beeg|(3bag af gfed|eaa^g a2|]',
    source: { ...SOURCE, where: 'No. 1295, p. 243 (PDF page 254)' },
    transcription: READ(254),
  },
  {
    id: 'oneill-1217-the-youngest-daughter',
    title: 'The Youngest Daughter',
    region: 'irish',
    kind: 'reel',
    key: 'E', mode: 'minor', meter: 'C|',
    origin: 'Irish reel, Gaelic title Ingean is Oige; the print credits F. O\'Neill. Printed with one sharp; both strains close on E, so read as E minor by the rule of the final note. The four-bar first strain repeats; the second strain is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Youngest Daughter\nM:C|\nL:1/8\nK:Em\nE2BE dEBe|dBAF DEFD|E2BE dEBe|dBAF BE E2:|\nEeef gfed|BdAF DEFD|Eeef gfed|BdAF BE E2|\nEeef gfed|BdAF DEFA|afge fde^c|dBAF BE E2|]',
    source: { ...SOURCE, where: 'No. 1217, p. 229 (PDF page 240)' },
    transcription: READ(240),
  },
  {
    id: 'oneill-1262-the-green-linnet',
    title: 'The Green Linnet',
    region: 'irish',
    kind: 'reel',
    key: 'B', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel, Gaelic title An Gealban-lion Glas; the print credits J. O\'Neill. Printed with three sharps; both strains close on B after a run through A, so read as B dorian by the rule of the final note. The four-bar first strain repeats; the second strain is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Green Linnet\nM:C|\nL:1/8\nK:Bdor\nA2ae cBAc|BAGB gdBG|A2ae cBAc|BGdB cAAB:|\nABcd ecBA|BGBd gdBG|ABcd ecBA|BGdB cAAB|\nABcd ecBA|BGBd gdBG|AcBd cedf|edcB cAAB|]',
    source: { ...SOURCE, where: 'No. 1262, p. 237 (PDF page 248)' },
    transcription: READ(248),
  },
  {
    id: 'oneill-1253-annie-oneill',
    title: 'Annie O\'Neill',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Anna ni Neill; the print credits Cronin. Both strains are printed in full, without repeats; the tune opens on a one-beat pickup and the closing bar is short to match it',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Annie O\'Neill\nM:C|\nL:1/8\nK:G\nD2|GABd cAFB|AGGF GABc|dcAG FGAc|BGAF GFED|\nGABd cAFB|AGGF G2g2|fdcA FGAB|AGGF G2d2||\ngage fgfd|cBcA dcdf|gage fgfd|cBcA defa|\ngage fgfd|efed cdeg|fdcA FGAB|AGGF G2|]',
    source: { ...SOURCE, where: 'No. 1253, p. 236 (PDF page 247)' },
    transcription: READ(247),
  },
  {
    id: 'oneill-1254-bridget-mcbride',
    title: 'Bridget McBride',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Brighid ni Mhic Bhrighde; the print credits Cronin. Both strains are printed in full, without repeats; the tune opens on a one-note pickup and closes on a dotted G that matches it',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Bridget McBride\nM:C|\nL:1/8\nK:G\nd|gedc BGBd|cBcA ABcA|B3/2G/ (3GGG GBdB|cBAG FGBd||\ngedc BGBd|cBcB ABcA|BcdB Bdeg|fdcA G2de||\nfefg fedB|cBAG FGAd|g2ga gfdg|fgaf g2de|\nf2fg fedB|cBAG FGAc|BcdB cdeg|fdef g3|]',
    source: { ...SOURCE, where: 'No. 1254, p. 236 (PDF page 247)' },
    transcription: READ(247),
  },
  {
    id: 'oneill-1348-salamanca-reel',
    title: 'Salamanca Reel',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Seisd Salamanca; the print credits J. O\'Neill. Both strains are printed in full, without repeats; each opens on a two-note pickup and its closing bar is short to match it',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Salamanca Reel\nM:C|\nL:1/8\nK:D\ndB|A3/2D/ (3FED A3/2D/ (3FED|Adcd fdcd|B3/2E/ (3GFE B3/2E/ (3GFE|Beed cdeg|\nfddg fdcA|Bdce dfag|fdec dBAG|FGEF D2||\nfg|afdg bgeg|fdec dcBA|Bdce dfeg|fagb a2fg|\nabaf gfeg|fdec dfag|fdec dBAG|FGEF D2|]',
    source: { ...SOURCE, where: 'No. 1348, p. 252 (PDF page 263)' },
    transcription: READ(263),
  },
  {
    id: 'oneill-1351-tie-the-bonnet',
    title: 'Tie the Bonnet',
    region: 'irish',
    kind: 'reel',
    key: 'B', mode: 'dorian', meter: 'C|',
    origin: 'Irish reel, Gaelic title Neasg an Bireadh; the print credits Beamish. Printed with three sharps; the tune leans on A throughout, but both strains close on B leading back to the opening A, so read as B dorian by the rule of the final note. The four-bar first strain repeats; the second strain is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Tie the Bonnet\nM:C|\nL:1/8\nK:Bdor\nA2Ag fdec|A2Ac BGGB|A2Ag fdef|gfge dBGB:|\na2af gfed|cAeA cAce|a2af gfef|gfge dBGB|\na2af gfed|cAeA cAce|afge fdef|gfge dBGB|]',
    source: { ...SOURCE, where: 'No. 1351, p. 252 (PDF page 263)' },
    transcription: READ(263),
  },
  {
    id: 'oneill-1350-the-sporting-boys',
    title: 'The Sporting Boys',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Na Buachaillidhe Greannmhar; the print credits O\'Reilly. Both strains are printed in full, without repeats; each opens on a two-note pickup and closes on C, short, leading back through the pickup to the opening G',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Sporting Boys\nM:C|\nL:1/8\nK:G\nBA|G2BG AcBA|G2BG GEDE|G2BG ABce|dBgB c2BA|\nG2BG AcBA|G2BG GEDE|DEGB cBAe|dBgB c2||\nBA|Bdgd edgd|Bdgd e2dc|Bdgd edef|gedB c2BA|\nBdgd edgd|Bdgd e2dc|Bdgd egfa|gedB c2|]',
    source: { ...SOURCE, where: 'No. 1350, p. 252 (PDF page 263)' },
    transcription: READ(263),
  },
  {
    id: 'oneill-1383-jerry-hayes',
    title: 'Jerry Hayes',
    region: 'irish',
    kind: 'reel',
    key: 'D', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Diarmaid ua Aodha; the print credits F. O\'Neill. The four-bar first strain, opening on a quarter-note A pickup, repeats; the second strain opens on a two-note pickup, is printed once, without repeats, and closes on a quarter-note D',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Jerry Hayes\nM:C|\nL:1/8\nK:D\nA2|d2fd ceAc|dAfd egce|d2fd ceAg|fdec d2:|\nAG|FDAF dABG|FDAF EcAG|FDAF dABG|FDEC A2AG|\nFDAF dABG|FDAF EcAG|FDAF dAAg|fdec d2|]',
    source: { ...SOURCE, where: 'No. 1383, p. 257 (PDF page 268)' },
    transcription: READ(268),
  },
  {
    id: 'oneill-1311-the-happy-days-of-youth',
    title: 'The Happy Days of Youth',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: 'C',
    origin: 'Irish reel printed in common time, Gaelic title Laetha Aoibhinn na n-Oige; the print credits F. O\'Neill. The four-bar first strain repeats and its closing G carries a pause over the double bar, which marks it as the true end of the tune; the second strain is printed once and stops on B. Read as G major from the signature and that closing G',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Happy Days of Youth\nM:C\nL:1/8\nK:G\nG2Bd e2dB|GABG AGEF|G2Bd e2dB|cABG EG G2:|\nf/a3/2ag fdde|fdag fd d2|f/a3/2ag fddf|edef gfed|\nf/a3/2ag fdde|fdag fd d2|bgaf gfef|dfaf gedB|]',
    source: { ...SOURCE, where: 'No. 1311, p. 246 (PDF page 257)' },
    transcription: READ(257),
  },
  {
    id: 'oneill-1183-music-in-the-glen',
    title: 'Music in the Glen',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Ceol Annsa Ghleanna; the print credits Cronin. The first strain ends on a pause over its double bar and the second strain is marked D.C., so the first strain is written out again after the second and the tune ends at the pause',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Music in the Glen\nM:C|\nL:1/8\nK:A\nA2cA FAED|CEAc BABc|d2fd ceAc|dBcA BAFE|\nA2cA FAED|CEAc BABc|defg agaf|edcB A2z2||\ncAeA fAed|cAec dBGB|cAeA fA(3efg|aecA BAFE|\ncAeA fAeg|aega bgeg|afge fdec|dBcA BAFG||\nA2cA FAED|CEAc BABc|d2fd ceAc|dBcA BAFE|\nA2cA FAED|CEAc BABc|defg agaf|edcB A2z2|]',
    source: { ...SOURCE, where: 'No. 1183, p. 223 (PDF page 234)' },
    transcription: READ(234),
  },
  {
    id: 'oneill-1363-molly-put-the-kettle-on',
    title: 'Molly Put the Kettle On',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'minor', meter: 'C|',
    origin: 'Irish reel, Gaelic title A Mhaire Cuir Sios an Coire; the print credits McNamara. Printed with no signature, a sharpened G before every closing A, and naturals on F in the second strain; both strains end on A, so read as A minor by the rule of the final note. Each strain is printed once, without repeats. A natural printed before G in the fourth bar of the second strain is a courtesy sign and changes nothing',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:Molly Put the Kettle On\nM:C|\nL:1/8\nK:Am\nBded cAAc|BcdcBG G2|ceed cBAG|EDE^G A2A2|\nBded cAAc|BcdcBG G2|cBcA B2AG|EDE^G A2A2||\nBde=f g2=fg|aged cA A2|Bde=f g2=fg|age=g a2a2|\nBde=f g2=fg|aged cA A2|ceed cAAG|EDE^G A2A2|]',
    source: { ...SOURCE, where: 'No. 1363, p. 254 (PDF page 265)' },
    transcription: READ(265),
  },
  {
    id: 'oneill-1319-the-ministers-daughter',
    title: 'The Minister\'s Daughter',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'major', meter: 'C|',
    origin: 'Irish reel, Gaelic title Ingean an Ministeir; the print credits Cronin. The first strain opens on a two-note pickup and repeats with first and second endings of two bars each; the second strain is printed once, without repeats',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:1\nT:The Minister\'s Daughter\nM:C|\nL:1/8\nK:A\ned|cAce cAAe|cAce f2ea|1 AceA cAec|Bcde f2:|2 afge gdec|Afed cA A2||\na2af ecAc|aecf e2(3efg|a2af ecAc|Bcde f2(3efg|\nabaf ecAc|aecf e2(3efg|afge fdec|Bfed cA A2|]',
    source: { ...SOURCE, where: 'No. 1319, p. 247 (PDF page 258)' },
    transcription: READ(258),
  },
];

export default TUNES;
