// settle-hear · tunes/oneill1903-airs-a - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.

export const SOURCE = {
  kind: 'print',
  book: "O'Neill's Music of Ireland: Eighteen Hundred and Fifty Melodies",
  compiler: "Capt. Francis O'Neill, arranged by James O'Neill",
  year: 1903,
  scan: 'https://archive.org/details/oneills-1850',
};

const READ = (pdf) => `read from the scan (PDF page ${pdf}; the scan is 96 ppi, so each staff was read in quarters from the native pixels enlarged six to twelve times) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs-a, 2026-10-02`;

export const TUNES = [
  {
    id: 'oneill-70-the-little-black-rose',
    title: 'The Little Black Rose (1st setting)',
    region: 'irish',
    kind: 'air',
    key: 'C',
    mode: 'minor',
    meter: '3/4',
    origin: 'Irish air, Gaelic title An Roisin Dubh; 1st setting; marked Tenderly',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:70\nT:The Little Black Rose\nM:3/4\nL:1/8\nK:Cm\nG=A|B2 G2 e3/2c/|d3/2c/ BG FD|D2 C2 C2|C4 cd|\ne2 e2 dc|e2 dc BG|c3 B GF|G4 cd||\ne2 ef dc|e2 dc BG|c3 B GF|D4 G=A|\nB2 c3/2d/ ec|d3/2c/ BG FD|C4 C2|C4|]',
    source: { ...SOURCE, where: 'No. 70, p. 12 (PDF page 24)' },
    transcription: READ(24),
  },
  {
    id: 'oneill-61-margaret-sheehan',
    title: 'Margaret Sheehan',
    region: 'irish',
    kind: 'air',
    key: 'G',
    mode: 'major',
    meter: '3/4',
    origin: 'Irish air, Gaelic title printed above it (Mairgread ni Seadhachain); marked Very slow; setting credited in the print to J. O\'Neill; one pair of grace notes left out',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:61\nT:Margaret Sheehan\nM:3/4\nL:1/4\nK:G\nz B A|G2 E|D2 E|G3|G2 B|d2 B|G2 B|d3|\nd2 e|d2 B|B A G|A3|A2 B|c2 A|B2 G|E3||\nA|B2 d|d2 e|d3|g2 e|d2 B|B A G|A2 c|\nB2 A|G2 E|D2 E|G2 A|B2 G|A2 B|G2 G|G3|]',
    source: { ...SOURCE, where: 'No. 61, p. 11 (PDF page 23)' },
    transcription: READ(23),
  },
  {
    id: "oneill-59-shule-aroon",
    title: "Shule Aroon (1st setting)",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "minor",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Siubhal a Ruin; 1st setting; marked Plaintively; setting credited in the print to F. O'Neill; two fermatas left out",
    tags: ["air", "slow", "irish"],
    abc: "X:59\nT:Shule Aroon\nM:C\nL:1/8\nK:Dm\nfe | d2 dc ABGA | c2 dc A2 FG | A2 A2 f2 ec | dcA^F G2 AG |\n=F2 EF D2 (3A=B^c | d3/2c/ AG A2 a3/2g/ | f2 ed ^cdec | d4 d2 z2 ||\nf4 e4 | d2 dc A2 AB | c2 d2 f2 e2 | dcA^F G2 AG |\nF2 EF D2 (3A=B^c | d3/2c/ AG A2 a3/2g/ | f2 ed ^cdec | d4 d2 |]",
    source: { ...SOURCE, where: "No. 59, p. 11 (PDF page 23)" },
    transcription: "read from the scan (PDF page 23; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-185-the-foggy-dew",
    title: "The Foggy Dew (1st setting)",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "mixolydian",
    meter: "2/4",
    origin: "Irish song air, Gaelic title Drucht an Cheo; 1st setting; marked Moderate; setting credited in the print to F. O'Neill; printed with a D.C. to the pause at the end of the first strain, written out here in full",
    tags: ["air", "slow", "irish"],
    abc: "X:185\nT:The Foggy Dew\nM:2/4\nL:1/8\nK:Dmix\ngf | efed | B2 GB | ABAF | D2 EF | G2 AG | E2 E2 | E4 | D2 ||\n|: B2 | E2 E2 | GA Bc | d2 BA | G2 A2 | B2 e2 | d2 f2 | e4- | e2 :|\ngf | efed | B2 GB | ABAF | D2 EF | G2 AG | E2 E2 | E4 | D2 |]",
    source: { ...SOURCE, where: "No. 185, p. 33 (PDF page 45)" },
    transcription: "read from the scan (PDF page 45; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-173-the-pretty-cuckoo",
    title: "The Pretty Cuckoo",
    region: "irish",
    kind: "song-air",
    key: "Bb",
    mode: "major",
    meter: "6/8",
    origin: "Irish song air, Gaelic title An Cuach Deas; marked With expression",
    tags: ["air", "slow", "irish"],
    abc: "X:173\nT:The Pretty Cuckoo\nM:6/8\nL:1/8\nK:Bb\nF | B3/2c/d dcB | G2F D2F | F3/2G/B c2B/c/ | d2c B2d | G2c F2B | D3/2C/B, C2F |\nF3/2G/B c2B/c/ | d2c B2d | G2c F2B | D3/2C/B, C2F | F3/2G/B c2B/c/ | d2c B2 |]",
    source: { ...SOURCE, where: "No. 173, p. 30 (PDF page 42)" },
    transcription: "read from the scan (PDF page 42; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-158-the-rising-of-the-moon",
    title: "The Rising of the Moon",
    region: "irish",
    kind: "song-air",
    key: "A",
    mode: "major",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Eirghe na Re; marked With animation; setting credited in the print to O'Brien; two accents left out",
    tags: ["air", "irish"],
    abc: "X:158\nT:The Rising of the Moon\nM:C\nL:1/8\nK:A\nA3B c2d2 | e2a2 f e3 | c3e d2B2 | A2A2 G4 |\nA3B c2d2 | e2a2 f e3 | c3e d2B2 | B2A2 A4 ||\ne2f2 g2a2 | b2a2 g e3 | c3d e2f2 | g2a2 e4 |\ne2f2 g2a2 | b2a2 g e3 | c3e d2B2 | B2A2 A4 |]",
    source: { ...SOURCE, where: "No. 158, p. 28 (PDF page 40)" },
    transcription: "read from the scan (PDF page 40; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-58-the-parting-glass",
    title: "The Parting Glass",
    region: "irish",
    kind: "song-air",
    key: "A",
    mode: "major",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Deoch an Doruis; marked Slow; setting credited in the print to F. O'Neill; a grace note and fermatas left out",
    tags: ["air", "slow", "irish"],
    abc: "X:58\nT:The Parting Glass\nM:C\nL:1/8\nK:A\ne3/2d/ | c2B3/2c/ A2AB | cdec d2c3/2d/ | e2a3/2f/ =gfed | c2A2G2 e3/2d/ |\nc2B3/2c/ A2AB | cdec d2c3/2d/ | e2a3/2f/ =gfed | c2A2A2 ||\ne3/2f/ | =gfga gfed | e2a2 a2ba | =gfed cBde | e2=G2 G2 e3/2d/ |\nc2B3/2c/ A2AB | cdec d2c3/2d/ | e2a3/2f/ =gfed | c2A2A2 |]",
    source: { ...SOURCE, where: "No. 58, p. 10 (PDF page 22)" },
    transcription: "read from the scan (PDF page 22; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-195-bonny-laboring-boy",
    title: "Bonny Laboring Boy",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "major",
    meter: "6/8",
    irregular: "bar 7 is printed as crotchet B, crotchet B, crotchet A, quaver G, one quaver longer than 6/8; the same phrase in bar 11 has a quaver on the second B; kept as printed",
    origin: "Irish song air, Gaelic title Spailpin Og Maiseach; marked Tenderly; setting credited in the print to F. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:195\nT:Bonny Laboring Boy\nM:6/8\nL:1/8\nK:D\nD | G2F G2A | d2c AGF | G2F D2D | D3-D2A |\nd2e =f2e | d2B cdc | B2B2 A2G | A3 ABc |\nd2e =f2e | d2B cdc | B2B A2G | A3 AGF |\nG2F G2A | d2c AGF | G2F D2D | D3-D2 |]",
    source: { ...SOURCE, where: "No. 195, p. 34 (PDF page 46)" },
    transcription: "read from the scan (PDF page 46; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-198-the-croppy-boy",
    title: "The Croppy Boy",
    region: "irish",
    kind: "song-air",
    key: "G",
    mode: "major",
    meter: "4/4",
    origin: "Irish song air, Gaelic title printed above it (An Buachaill Bearta); marked Slow; setting credited in the print to Hartnett; the last bar ends with a crotchet rest as printed",
    tags: ["air", "slow", "irish"],
    abc: "X:198\nT:The Croppy Boy\nM:C\nL:1/8\nK:G\nD | G2A3/2G/ AB2G | A2G3/2G/ G2 G/A/B/d/ | g4 fdfe | d4 z D G/A/B/d/ |\ng4 fdfe | d3d e/d/B/A/ G3/2A/ | B3G A2G3/2G/ | G4 z2 |]",
    source: { ...SOURCE, where: "No. 198, p. 34 (PDF page 46)" },
    transcription: "read from the scan (PDF page 46; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-153-crossing-the-stream",
    title: "Crossing the Stream",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    irregular: "bar 10 (the second bar of the second strain) is printed as dotted crotchet E, crotchet F, crotchet G, one quaver longer than 3/4; the same figure in bars 9 and 13 has a quaver on the F; kept as printed",
    origin: "Irish air, Gaelic title Ag Tarsnad an Srutan; marked Playfully; setting credited in the print to J. O'Neill; staccato dots left out",
    tags: ["air", "irish"],
    abc: "X:153\nT:Crossing the Stream\nM:3/4\nL:1/8\nK:G\nG2 | G3B d2 | d2B2e2 | d2B2g2 | B2A2G2 | G3B d2 | d2B2 GE | D2B2A2 | G4 :|\nd2 | g3f g2 | e3 f2g2 | e2a3g | f2d2d2 | g3f g2 | e2d2c2 | B2A2G2 | d4B2 |\nc3d c2 | B2d2g2 | edcBAG | B2A2d2 | g3f e2 | d2g2e2 | d2g2f2 | g4 |]",
    source: { ...SOURCE, where: "No. 153, p. 27 (PDF page 39)" },
    transcription: "read from the scan (PDF page 39; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-138-luggelaw",
    title: "Luggelaw",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Lug na Leaca; marked Moderate; two grace notes and a fermata left out",
    tags: ["air", "slow", "irish"],
    abc: "X:138\nT:Luggelaw\nM:3/4\nL:1/8\nK:G\nG/A/BB | A3/2B/ cd ee | d3/2B/ GA Bd | d2 BG A3/2G/ | G z GA BB |\nA3/2B/ cd ee | dB GA Bd | ed BG A3/2G/ | G2 z ||\ndde | e2g2 e3/2d/ | Bd d2 ef/g/ | B2 cB AG | A2 z B cB |\nA3/2B/ cd ee | d3/2B/ G3/2A/ Bd | ed BG A3/2G/ | G3 |]",
    source: { ...SOURCE, where: "No. 138, p. 24 (PDF page 36)" },
    transcription: "read from the scan (PDF page 36; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-152-kitty-of-coleraine",
    title: "Kitty of Coleraine",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish song air, Gaelic title Caitilin Ua Cuilrathain; marked Gaily; staccato dots and a fermata left out",
    tags: ["air", "irish"],
    abc: "X:152\nT:Kitty of Coleraine\nM:6/8\nL:1/8\nK:D\nA/G/ | FAd dfa | eg/f/e/d/ ceA | dfa dgb | b/a/g/f/e/d/ fe A/G/ |\nFAd dfa | eg/f/e/d/ ceA | dfa dgb | A3/2B/c d2 ||\nf/g/ | afd ecA | afd ecA | afd f/e/d/c/B/A/ | Ba^g a2 A/G/ |\nFAd dfa | eg/f/e/d/ ceA | dfa dgb | A3/2B/c d2 |]",
    source: { ...SOURCE, where: "No. 152, p. 27 (PDF page 39)" },
    transcription: "read from the scan (PDF page 39; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-19-the-protestant-boys",
    title: "The Protestant Boys",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish air, Gaelic title printed above it in Irish type; marked With spirit; setting credited in the print to J. O'Neill",
    tags: ["air", "irish"],
    abc: "X:19\nT:The Protestant Boys\nM:6/8\nL:1/8\nK:G\nD | GAG BcB | AFA c2e | dBG GcB | AGF G2D |\nGAG BcB | AFA c2e | dBG c2B | AGF G2 ||\nd | g2d e2d | g2d e2d | def gfe | dcB A2g |\nedc Bcd | dcB ABc | dBG c2B | AGF G2 |]",
    source: { ...SOURCE, where: "No. 19, p. 4 (PDF page 16)" },
    transcription: "read from the scan (PDF page 16; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-21-the-groves-of-blackpool",
    title: "The Groves of Blackpool",
    region: "irish",
    kind: "air",
    key: "C",
    mode: "minor",
    meter: "6/8",
    origin: "Irish air, Gaelic title Coillte Dubh-Linn; marked Moderate; setting credited in the print to F. O'Neill; a grace note left out",
    tags: ["air", "irish"],
    abc: "X:21\nT:The Groves of Blackpool\nM:6/8\nL:1/8\nK:Cm\nc | B3/2A/G GAF | E C3 z D | EFG G=A=B | c3-c2c |\nB3/2A/G GAF | E C3 z D | EFG FED | C3-C2 ||\nc/d/ | e3/2d/e fdc | B G3 z G | c3/2d/e fde | f3-f2f |\nefg fed | e c3 z c | BAG FG=B | c3-c2 |]",
    source: { ...SOURCE, where: "No. 21, p. 4 (PDF page 16)" },
    transcription: "read from the scan (PDF page 16; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-22-the-woods-of-kilmurry",
    title: "The Woods of Kilmurry",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "minor",
    meter: "6/8",
    origin: "Irish air, Gaelic title Coillte Cill-Muire; marked Slow; setting credited in the print to F. O'Neill; grace notes left out",
    tags: ["air", "slow", "irish"],
    abc: "X:22\nT:The Woods of Kilmurry\nM:6/8\nL:1/8\nK:Gm\nd/c/ | BAG FDC | D G2 G2 G/A/ | BAG dcA | F3 F2 d/c/ |\nBAG FDC | D G2 G2 G/A/ | B/d3/2c A/B3/2A | G3-G2 ||\nG/A/ | B3/2c/d/=e/ fdc | d g2 g z g/a/ | bag dcA | G3 G z a/g/ |\nfed cAG | G D2 D2 G/A/ | B/d3/2c A/B3/2A | G3-G2 |]",
    source: { ...SOURCE, where: "No. 22, p. 4 (PDF page 16)" },
    transcription: "read from the scan (PDF page 16; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
];

export default TUNES;
