// settle-hear · tunes/oneill1903-airs-c - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.

export const SOURCE = {
  kind: 'print',
  book: "O'Neill's Music of Ireland: Eighteen Hundred and Fifty Melodies",
  compiler: "Capt. Francis O'Neill, arranged by James O'Neill",
  year: 1903,
  scan: 'https://archive.org/details/oneills-1850',
};

export const TUNES = [  {
    id: "oneill-507-the-groves-of-blarney",
    title: "The Groves of Blarney",
    region: "irish",
    kind: "song-air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish song air, Gaelic title Coillte Blarnaigh; marked Slow with expression; grace notes, a turn and a fermata left out",
    tags: ["air", "slow", "irish"],
    abc: "X:507\nT:The Groves of Blarney\nM:3/4\nL:1/8\nK:G\nG3/2A/ | B2 g2 e3/2d/ | d B3 G3/2A/ | B2 cB A3/2G/ | G4 G3/2A/ |\nB2 g2 e3/2d/ | d B3 G3/2A/ | B2 c3/2B/ A3/2G/ | G4 ||\nd3/2B/ | g2 g3/2f/ e3/2d/ | d B3 d3/2B/ | g2 gfe^d | e2 g2 G3/2A/ |\nB2 g2 e3/2d/ | d B3 G3/2A/ | B2 c3/2B/ A3/2G/ | G4 |]",
    source: { ...SOURCE, where: "No. 507, p. 89 (PDF page 101)" },
    transcription: "read from the scan (PDF page 101; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-512-the-snowy-breasted-pearl",
    title: "The Snowy Breasted Pearl",
    region: "irish",
    kind: "song-air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish song air, Gaelic title Pearla na m-Brollach Bane; marked Moderate; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:512\nT:The Snowy Breasted Pearl\nM:3/4\nL:1/8\nK:G\nd/e/f | g4 ge | d3 cBA | G4 BG | A2 EDEG | G4 cA |\nc2 d2 ea | g4 f/g/a | g2 fe d2 | e2 BABd | e4 ||\nd/e/f | g4 f/g/a | g2 gfed | e2 G2 B/c/d | d4 d/e/f |\ng2 f/g/a ge | d3 cBA | G4 BG | A2 EDEG | G4 |]",
    source: { ...SOURCE, where: "No. 512, p. 89 (PDF page 101)" },
    transcription: "read from the scan (PDF page 101; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-467-the-wearing-of-the-green",
    title: "The Wearing of the Green",
    region: "irish",
    kind: "song-air",
    key: "G",
    mode: "major",
    meter: "4/4",
    origin: "Irish song air; Gaelic title printed above it in Irish type; marked Moderate; a grace note and two fermatas in each strain left out",
    tags: ["air", "irish"],
    abc: "X:467\nT:The Wearing of the Green\nM:C\nL:1/8\nK:G\nG3/2A/ | BBB3/2A/ B/d3/2d3/2B/ | BAA3/2G/ A2 Bd | ecg3/2f/ edB3/2G/ | AGG3/2G/ G2 :|\ng3/2f/ | eedB ddGA | BcB3/2A/ B2 g3/2f/ | eedB ddGB | AGFE D2 GA |\nBBB3/2A/ B/d3/2d3/2B/ | BAAG A2 Bd | ecg3/2f/ edB3/2G/ | AGG3/2G/ G2 |]",
    source: { ...SOURCE, where: "No. 467, p. 81 (PDF page 93)" },
    transcription: "read from the scan (PDF page 93; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-521-mcfarlanes-lament",
    title: "McFarlane's Lament",
    region: "irish",
    kind: "lament",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Lament air, Gaelic title Caoine Mhic Farlain; marked Mournful; slurs and two staccato dots left out",
    tags: ["air", "slow", "lament", "irish"],
    abc: "X:521\nT:McFarlane's Lament\nM:3/4\nL:1/8\nK:G\nB3/2A/ | G4 d3/2B/ | A2 G z d3/2B/ | A2G2G2 | G4 Bd ||\ne2e2 g3/2e/ | d4 e3/2d/ | B2e2 d3/2B/ | A4 G3/2A/4B/4 |\nA2 G z G3/2A/4B/4 | A2 G z B3/2d/ | e2 ef g3/2e/ | d4 ed |\nB2B2 d3/2B/ | A2 G z GA/B/ | A2G2G2 | G4 |]",
    source: { ...SOURCE, where: "No. 521, p. 91 (PDF page 103)" },
    transcription: "read from the scan (PDF page 103; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-539-the-fenian-stronghold",
    title: "The Fenian Stronghold",
    region: "irish",
    kind: "air",
    key: "Bb",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Cruachan na Feine; marked With feeling; the second strain is printed under a one-flat signature (a natural cancels the E flat) and ends on D, so its Es are written here as naturals; a grace note left out",
    tags: ["air", "slow", "irish"],
    abc: "X:539\nT:The Fenian Stronghold\nM:3/4\nL:1/8\nK:Bb\nF2 | B2 Bc dB | c2 f3e | d2B2B2 | A2F2F2 | B2 Bc dB | c2 f3e | d2B2c2 | B4 ||\nc2 | d2 d=e fd | c2A2F2 | G2 GB AG | F2D2A2 | d2 d=e fd | c2A2F2 | G2 GF =EF | D4 |]",
    source: { ...SOURCE, where: "No. 539, p. 94 (PDF page 106)" },
    transcription: "read from the scan (PDF page 106; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-540-the-mountains-of-pomeroy",
    title: "The Mountains of Pomeroy",
    region: "irish",
    kind: "song-air",
    key: "G",
    mode: "major",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Sleibhte Pomeroig; marked With spirit; slurs and two fermatas left out; the crotchet rests are as printed",
    tags: ["air", "irish"],
    abc: "X:540\nT:The Mountains of Pomeroy\nM:C\nL:1/8\nK:G\nd2 | d2B2 dcBA | G3A E2GE | D2EG G2AB | c2 z2 z2 Bc |\nd2B2 dcBA | G2A2 E2GE | D2EG G3A | G2 z2 z2 ||\nGA | B3A G2AB | c2d2 d2ge | d2B2 G2AB | c2 z2 z2 Bc |\nd2BB dcBA | G2A2 E2GE | D2EG G3A | G2 z2 z2 GA |\nB2A2 G2AB | c2d2 d2ge | d3B G2AB | c2 z2 z2 Bc |\nd2B2 dcBA | G2A2 E2GE | D3E G2G2 | G2 z2 z2 |]",
    source: { ...SOURCE, where: "No. 540, p. 94 (PDF page 106)" },
    transcription: "read from the scan (PDF page 106; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-592-have-you-seen-my-valentine",
    title: "Have You Seen My Valentine?",
    region: "irish",
    kind: "song-air",
    key: "E",
    mode: "minor",
    meter: "3/4",
    origin: "Irish song air, Gaelic title printed above it in Irish type; marked Slow; two pairs of grace notes and a fermata left out; each strain ends on a two-crotchet bar, as printed",
    tags: ["air", "slow", "irish"],
    abc: "X:592\nT:Have You Seen My Valentine?\nM:3/4\nL:1/8\nK:Em\nB2B2 ^c^d | e4 ef | g4 fe | ed B2B2 | g4 ag | f4 b2 | e3/2d/ B2 ^de | f2e2 ||\nfe | d2B2^c2 | d4 gf | e2 dcBA | B2G2 E3/2F/ | G2G2 BG | F2F2 AF | E2E2 ^DE | F2E2 |]",
    source: { ...SOURCE, where: "No. 592, p. 104 (PDF page 116)" },
    transcription: "read from the scan (PDF page 116; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-430-the-banks-of-claudy",
    title: "The Banks of Claudy",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "minor",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Bruacha na g-Claudiagh; marked Slow with feeling; setting credited in the print to J. O'Neill; printed with a one-flat signature and ending on D; the small grace notes and the turns are left out",
    tags: ["air", "slow", "irish"],
    abc: "X:430\nT:The Banks of Claudy\nM:C\nL:1/8\nK:Dm\nfe|d3 c d2 DE|F2 FA c2 dc|A2 G F/E/ D2 D2|D6 FG|AB/A/ GA d2 e2|\nf3 d e2 dc|A2 B/A/G A2 ^c2|d6 FG|AB/A/ GA d2 e2|f3 d fe dc|\nA2 G2 Ad ^ce|d6 fe|d3 c d2 DE|F2 FA c2 dc|A2 G F/E/ D2 D2|D6|]",
    source: { ...SOURCE, where: "No. 430, p. 75 (PDF page 87)" },
    transcription: "read from the scan (PDF page 87; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-445-mary-with-the-amber-locks",
    title: "Mary with the Amber Locks",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Maire an Chuil Omraigh; marked With feeling; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:445\nT:Mary with the Amber Locks\nM:3/4\nL:1/8\nK:G\nD3/2F/|G2 G3/2A/ B3/2A/|G4 G3/2A/|B3/2c/ d2 d3/2c/|B4 e3/2f/|g2 g2 f3/2e/|d2 d3/2c/ B3/2c/|d2 g2 g3/2a/|g4||\ng2|=f2 e2 d3/2c/|B4 d2|e3/2f/ g3/2a/ b3/2a/|g4 (3edc|B2 A2 G2|F2 G3/2A/ B3/2c/|d2 c3/2B/ A3/2G/|G4|]",
    source: { ...SOURCE, where: "No. 445, p. 78 (PDF page 90)" },
    transcription: "read from the scan (PDF page 90; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-446-within-this-village-dwells-a-maid",
    title: "Within This Village Dwells a Maid (No. 1)",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Annsa Baile seo Comhnaidheann Ainnear; the first of two settings (No. 1); marked Slow; no contributor named; a turn and a grace note are left out",
    tags: ["air", "slow", "irish"],
    abc: "X:446\nT:Within This Village Dwells a Maid\nM:3/4\nL:1/8\nK:G\nB3/2c/|d2 g2 g3/2a/|b2 d2 B3/2c/|d2 d3/2e/ d3/2c/|B2 G2 B3/2c/|d2 g2 g3/2a/|b2 d2 d2|e2 e3/2g/ f3/2e/|d4||\nB3/2c/|d2 d2 d3/2f/|g2 d g/a/ bg|d2 B3/2c/ d3/2c/|B2 G2 B3/2c/|d2 b2 a2|g3/2a/ b2 d2|Bd cB A3/2B/|G4|]",
    source: { ...SOURCE, where: "No. 446, p. 78 (PDF page 90)" },
    transcription: "read from the scan (PDF page 90; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-456-the-grave-of-wolfe-tone",
    title: "The Grave of Wolfe Tone",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "minor",
    meter: "3/4",
    origin: "Irish air, Gaelic title Uaigh Wolfe Tone; marked Plaintive; setting credited in the print to J. O'Neill; printed with a two-flat signature and ending on G",
    tags: ["air", "slow", "irish"],
    abc: "X:456\nT:The Grave of Wolfe Tone\nM:3/4\nL:1/8\nK:Gm\nd=e|f2 g2 f2|d2 c2 F2|A2 G2 G2|G4 AG|F2 G2 A2|c2 d2 c2|c2 A2 G2|F4 GA|\nB2 A2 G2|A2 G2 GA|B2 c2 d2|g4 fg|a2 g2 f2|d2 c2 FG|A2 G2 G2|G4|]",
    source: { ...SOURCE, where: "No. 456, p. 80 (PDF page 92)" },
    transcription: "read from the scan (PDF page 92; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-455-tyrone-castle",
    title: "Tyrone Castle",
    region: "irish",
    kind: "air",
    key: "C",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Caislean Tir-Eoghain; marked Slow; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:455\nT:Tyrone Castle\nM:3/4\nL:1/8\nK:C\nG3/2A/|c3 d ed|c3 A GF|E2 G2 Ac|c4 G3/2A/|c3 d ed|c2 B2 A3/2G/|G2 E2 D3/2C/|C4||\nC3/2D/|E2 G2 A3/2B/|A3/2G/ E2 C3/2D/|E2 G2 A_B|A3 z G3/2A/|c3 d ed|c2 B2 A2|G E3 D3/2C/|C4|]",
    source: { ...SOURCE, where: "No. 455, p. 79 (PDF page 91)" },
    transcription: "read from the scan (PDF page 91; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-483-sweet-molly-malone",
    title: "Sweet Molly Malone",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Maire Mhaiseach Ni Maeleoin; marked Moderate; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:483\nT:Sweet Molly Malone\nM:3/4\nL:1/8\nK:G\nD2|G2 G2 G2|G B3 G2|A2 A2 A2|A c3 c2|B2 d2 d2|d2 B2 G2|F2 A2 A2|A4 D2|\nG3 G G2|G B3 G2|A2 A2 A2|A c3 A2|B d3 G2|B d3 F2|A3 G G2|G4|]",
    source: { ...SOURCE, where: "No. 483, p. 84 (PDF page 96)" },
    transcription: "read from the scan (PDF page 96; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-476-johnny-doyle",
    title: "Johnny Doyle",
    region: "irish",
    kind: "song-air",
    key: "A",
    mode: "minor",
    meter: "2/4",
    origin: "Irish song air, Gaelic title Seanin Ua Dobhail; marked Moderate; no contributor named; printed with no signature and ending on A; grace notes in bars 7 and 11 are left out",
    tags: ["air", "irish"],
    abc: "X:476\nT:Johnny Doyle\nM:2/4\nL:1/8\nK:Am\ned|cA AG|E2 DF|EA AA|A2 AE|AB cd|ed ce|dB cA|G3 E|\nAB cd|ed ce|dB cA|G2 ed|cA AG|AG ED|EA AA|A2|]",
    source: { ...SOURCE, where: "No. 476, p. 83 (PDF page 95)" },
    transcription: "read from the scan (PDF page 95; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-475-the-bird-alone",
    title: "The Bird Alone",
    region: "irish",
    kind: "air",
    key: "A",
    mode: "minor",
    meter: "4/4",
    origin: "Irish air, Gaelic title An Ean Aonar; marked Moderate; setting credited in the print to J. O'Neill; printed with no signature and ending on A, with sharpened G",
    tags: ["air", "slow", "irish"],
    abc: "X:475\nT:The Bird Alone\nM:C\nL:1/8\nK:Am\nEG|A2 A3/2c/ BAGE|c2 c3/2A/ BAGE|A^GAB GE G3/2E/|D2 D2 D2 E^G|\nA2 AB c2 d2|e2 eg f2 d2|edcA G2 E^G|A6||\nAG|E2 AB c3/2d/ ec|d2 eg f2 d2|edcA G2 ED|E6 E^G|A2 A3/2B/ cAGE|c2 d3/2c/ BAGE|A^GAB GEDB,|A,2 A,2 A,2|]",
    source: { ...SOURCE, where: "No. 475, p. 83 (PDF page 95)" },
    transcription: "read from the scan (PDF page 95; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-487-as-through-the-woods-i-roamed",
    title: "As Through the Woods I Roamed",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "minor",
    meter: "4/4",
    origin: "Irish air, Gaelic title Mar Chuaidh Me Trid na Coilltibh; marked Moderate; setting credited in the print to J. O'Neill; printed with a two-flat signature and ending on G, with E naturals in the second strain",
    tags: ["air", "slow", "irish"],
    abc: "X:487\nT:As Through the Woods I Roamed\nM:C\nL:1/8\nK:Gm\nGF|D2 G2 G2 FG|A2 A2 f2 dc|B2 B2 B2 G2|c3 A F3 A|G2 G2 G2 FG|A2 A2 f3 d|d3/2c/ AG A3 G|G4 G2||\ndc|d2 g2 g2 fg|a2 g2 g2 fg|a2 gf d2 cd|=e3 f d3 e|g2 dc A2 G2|Ac d=e f3 a|gf dc A3 G|G4 G2|]",
    source: { ...SOURCE, where: "No. 487, p. 85 (PDF page 97)" },
    transcription: "read from the scan (PDF page 97; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-485-grace-omalley",
    title: "Grace O'Malley",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "minor",
    meter: "4/4",
    origin: "Irish air, Gaelic title Graine Ua Maille; marked Moderate; no contributor named; printed with a two-flat signature and ending on G, with E naturals in the second strain; a grace note in bar 13 is left out",
    tags: ["air", "slow", "irish"],
    abc: "X:485\nT:Grace O'Malley\nM:C\nL:1/8\nK:Gm\nG/A/B/c/|dedc B2 fd|c2 d2 F2 GA|BGcB G2 G2|G6 G/A/B/c/|dedc B2 fd|c2 d2 F2 GA|BGcB G2 G2|G6||\nGA|Bcd=e f2 ef|g2 d2 c2 Bc|d2 c2 d=efd|g6 g=e|f2 g2 d2 cB|c2 d2 F2 GA|BGcB G2 G2|G6|]",
    source: { ...SOURCE, where: "No. 485, p. 85 (PDF page 97)" },
    transcription: "read from the scan (PDF page 97; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-501-the-emblem-of-faith",
    title: "The Emblem of Faith",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Comhartha na Chriedeamha; marked Slow; setting credited in the print to Dunlap",
    tags: ["air", "slow", "irish"],
    abc: "X:501\nT:The Emblem of Faith\nM:3/4\nL:1/8\nK:D\nA2 A2 de|f2 A2 A2|f2 gf ed|c2 B2 Bc|d2 de fe|d2 cA GF|G2 c2 B2|A4||\nFG|A2 B2 AG|c2 BA GF|G3 B AG|F3/2E/ D2 FG|A2 f2 e2|d2 A2 F2|GB AG FE|F2 D4|]",
    source: { ...SOURCE, where: "No. 501, p. 88 (PDF page 100)" },
    transcription: "read from the scan (PDF page 100; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-492-the-lovers-discourse",
    title: "The Lovers' Discourse",
    region: "irish",
    kind: "air",
    key: "A",
    mode: "minor",
    meter: "4/4",
    origin: "Irish air, Gaelic title Comhradh na Graidheoir; marked Moderate; setting credited in the print to J. O'Neill; printed with no signature and ending on A, with sharpened G",
    tags: ["air", "slow", "irish"],
    abc: "X:492\nT:The Lovers' Discourse\nM:C\nL:1/8\nK:Am\ncB|ABAG E2 E^G|A2 A2 A2 cd|e2 dc d2 ec|G4 E2 cd|e2 dc d2 ec|\nA3/2B/AG E2 E^G|A2 A2 BcdB|c3 B A2 cB|ABAG ED E^G|A4 A2|]",
    source: { ...SOURCE, where: "No. 492, p. 86 (PDF page 98)" },
    transcription: "read from the scan (PDF page 98; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-517-the-banks-of-the-suir",
    title: "The Banks of the Suir",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Bruacha na Siuire; marked Slow; setting credited in the print to F. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:517\nT:The Banks of the Suir\nM:3/4\nL:1/8\nK:G\nGA|B2 e2 ed|e2 d2 BA|G2 E2 GA|B2 d2 BA|B2 G2 A2|B4 GA|B2 e2 ed|e2 d2 BA|G2 E2 GA|B2 d2 BA|B2 G2 A2|G4||\nGA|B2 d2 ef|g2 f2 e2|f2 d2 ef|g2 f2 ed|B2 e2 f2|e4 ef|g2 f2 ed|e2 d2 BA|G2 E2 GA|B2 d2 BA|B2 G2 A2|G4|]",
    source: { ...SOURCE, where: "No. 517, p. 90 (PDF page 102)" },
    transcription: "read from the scan (PDF page 102; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-528-charles-oreilly",
    title: "Charles O'Reilly",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Cathal Ua Raghallaigh; marked Mournful; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:528\nT:Charles O'Reilly\nM:3/4\nL:1/8\nK:G\nEF|GG G2 BG|EE E2 FG|AA A2 FA|DD D2 Bc|dd d2 gd|ec B2 GA|BB c2 AF|GG G2||\nBG|EE E2 BG|DD D2 Bc|dd d2 gB|cB A2 BG|EE E2 BG|DD D2 Bc|dd c2 AF|GG G2|]",
    source: { ...SOURCE, where: "No. 528, p. 92 (PDF page 104)" },
    transcription: "read from the scan (PDF page 104; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-518-ill-make-my-love-a-breast-of-glass",
    title: "I'll Make My Love a Breast of Glass",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Dheanfaim Brollach Gloine Dom Ghradh; marked Moderate; setting credited in the print to F. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:518\nT:I'll Make My Love a Breast of Glass\nM:3/4\nL:1/8\nK:G\nDGA|B2 AG Bc|d3 d ed|c2 dc Bc|A3 DGA|B2 AG Bc|d3 c Bc|A2 BAGF|G3||\nG/A/BB|B2 df gf|e2 dc BB|B2 cd cB|A3 DGA|B2 AG Bc|d2 ge dB|A2 BAGF|G3|]",
    source: { ...SOURCE, where: "No. 518, p. 90 (PDF page 102)" },
    transcription: "read from the scan (PDF page 102; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
];

export default TUNES;
