// settle-hear · tunes/oneill1903-jigs - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book page: wikis/WIKI_OLD_MELODIES/books/BOOK_ONEILL1903_JIGS.md (double jigs Nos. 701 to 1065, slip jigs from No. 1066).

export const SOURCE = {
  kind: 'print',
  book: "O'Neill's Music of Ireland: Eighteen Hundred and Fifty Melodies",
  compiler: "Capt. Francis O'Neill, arranged by James O'Neill",
  year: 1903,
  scan: 'https://archive.org/details/oneills-1850',
};

export const TUNES = [
  {
    id: "oneill-717-saddle-the-pony",
    title: "Saddle the Pony",
    region: "irish",
    kind: "jig",
    key: "A",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, 1st setting; Gaelic title printed above it, Cuir diallaid air an clibin; setting credited in the print to F. O'Neill",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Saddle the Pony\nM:6/8\nL:1/8\nK:A\nA/B/|:cAA eAA|cBc eAA|cAA eAA|dBG Bcd|\ncAA eAA|cBc efg|agf gfe|dBG Bcd:|\n|:e/a3/2f gee|fdd gee|e/a3/2f gfe|dBG Bcd|\ne/a3/2f gee|fdd gee|def gfe|dBG Bcd:|",
    source: { ...SOURCE, where: "No. 717, p. 134 (PDF page 145)" },
    transcription: "read from the scan (PDF page 145, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-847-the-rakes-of-kildare",
    title: "The Rakes of Kildare",
    region: "irish",
    kind: "jig",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, Na racairaide na Cill-dara; no collector named in the print",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Rakes of Kildare\nM:6/8\nL:1/8\nK:G\nD|:D2G GFG|ABc d2e|=fef ded|cAG F3|\nDGG GFG|ABc d2e|=fed cA^F|G3 G2:|\nd|:gfg def|gfg a2g|=fef ded|cAG F2d|\ngfg def|gfg a2g|=fed cA^F|G3 G2:|",
    source: { ...SOURCE, where: "No. 847, p. 157 (PDF page 168)" },
    transcription: "read from the scan (PDF page 168, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-858-lannigans-ball",
    title: "Lannigan's Ball",
    region: "irish",
    kind: "jig",
    key: "Em",
    mode: "minor",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, Feis-rince ui Lannagain; setting credited in the print to F. O'Neill; the print sharpens C in bars 2 and 6 and D in bars 10 and 14",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Lannigan's Ball\nM:6/8\nL:1/8\nK:Em\n|:EFE G2A|B2A B^cd|D2E F2G|ABA AFD|\nEFE G2A|B2A B^cd|edB cBA|BGE E2:|\nd|:e2f gfg|eag fe^d|e2f gfg|fdB B3|\ne2f gfg|eag fe^d|edB cBA|BGE E2:|",
    source: { ...SOURCE, where: "No. 858, p. 159 (PDF page 170)" },
    transcription: "read from the scan (PDF page 170, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-776-banish-misfortune",
    title: "Banish Misfortune",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig in three parts; Gaelic title printed above it, Dibir an mio-ad; setting credited in the print to Cronin; printed with a two-sharp signature",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Banish Misfortune\nM:6/8\nL:1/8\nK:D\nA/G/|F2D DED|DEF GFG|A3 cAG|ABc d/c/AG|\nF2D DED|DEF GFG|AdB cde|d3 d2:|\n|:d/e/|f2 d/d/ dcd|dfa agf|e2 c/c/ cBc|e/d/ef gfe|\n|1 f2 d/d/ dcd|dfa agf|g/f/ed cde|d3 d2:|2 fga gab|afd ecA|fed cde|d3 d2||\n|:d/e/|f/e/df e/d/ce|d/c/AB cAG|F2D DED|DEF GFG|\nA/G/AB cAG|AdB cde|fed cde|d3 d2:|",
    source: { ...SOURCE, where: "No. 776, p. 145 (PDF page 156)" },
    transcription: "read from the scan (PDF page 156, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-987-haste-to-the-wedding",
    title: "Haste to the Wedding",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, Deun deifir go de an posga; no collector named in the print; the second strain's seventh bar has a sixteenth F where the first strain has G",
    irregular: "bar 15 (second strain, seventh bar) is printed A2 g f/ a g with no dot after the a, five and a half eighths; the matching bar 7 carries the dot",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Haste to the Wedding\nM:6/8\nL:1/8\nK:D\nA|AFA Agf|ede fdB|AFA AdF|EFE E2A|\nAFA Agf|ede fdB|A2g g/a3/2g|ded d2:|\n|:a|afa afa|bgb bgb|afa agf|efe efg|\na3 f3|ede fdB|A2g f/ag|ded d2:|",
    source: { ...SOURCE, where: "No. 987, p. 184 (PDF page 195)" },
    transcription: "read from the scan (PDF page 195, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-914-off-she-goes",
    title: "Off She Goes",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig; printed as Off She Goes!, Gaelic title printed above it, Ta si ag imtheacht; no collector named in the print",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Off She Goes\nM:6/8\nL:1/8\nK:D\nF2A G2B|ABc d3|F2A G2B|AFD E2D|\nF2A G2B|ABc d2e|f2d g2f|edc d2:|\n|:e|faf def|gbg efg|faf def|ecA A2g|\nfaf def|gbg efg|f2d g2f|edc d2:|",
    source: { ...SOURCE, where: "No. 914, p. 170 (PDF page 181)" },
    transcription: "read from the scan (PDF page 181, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-965-smash-the-windows",
    title: "Smash the Windows",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, a repeated first strain and a sixteen-bar second strain; Gaelic title printed above it, Bris na fuinneogaide; setting credited in the print to J. O'Neill",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Smash the Windows\nM:6/8\nL:1/8\nK:D\nA,|DED F2A|d2f ecA|G2B F2A|E2F GFE|\nDED F2A|d2f ecA|Bgf edc|d3 d2:|\na|a2f d2e|f2g agf|g2e c2d|e2f gfe|\nf2d g2e|a2f bag|fed cde|d3 dza|\nagf fed|Adf afd|gfe ecA|Ace gfe|\nfed gfe|agf bag|fed cde|d3 d2|]",
    source: { ...SOURCE, where: "No. 965, p. 179 (PDF page 190)" },
    transcription: "read from the scan (PDF page 190, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1031-the-top-of-cork-road",
    title: "The Top of Cork Road",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, Mullach bothair Corcaigh; no collector named in the print",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Top of Cork Road\nM:6/8\nL:1/8\nK:D\nf/e/|dAF DFA|Bed cBA|dcd efg|aed cBA|\ndAF DFA|Bed cBA|dcd efg|fdd d2:|\n|:g|fdf fga|ecd efg|dcd fed|cAA A2c|\nBGB Bcd|AFA DFA|dcd efg|fdd d2:|",
    source: { ...SOURCE, where: "No. 1031, p. 192 (PDF page 203)" },
    transcription: "read from the scan (PDF page 203, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1116-the-rocky-road-to-dublin",
    title: "The Rocky Road to Dublin",
    region: "irish",
    kind: "slip-jig",
    key: "A",
    mode: "major",
    meter: "9/8",
    origin: "Irish slip jig in three strains, the first slip jig in the book; Gaelic title printed above it, An bothar sgreagach go Baile-atha-cliath; setting credited in the print to McFadden; printed with a three-sharp signature, so every G is G sharp, and the print ends on D",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:The Rocky Road to Dublin\nM:9/8\nL:1/8\nK:A\nefe d2B A2A|E2A A2A Bcd|efe d2B A2c|B2A G2A Bcd:|\ne2a a2f g2b|e2a a2A Bcd|e2a a2f g2e|d2B G2A Bcd|\ne2a a2f g2d|e2a a2A Bcd|efg fga gfe|d2B G2A Bcd||\necA ecA A2a|ecA ecA Bcd|ecA ecA a2c|d2B G2A Bcd|\necA ecA A2a|ecA ecA Bcd|efg fga gfe|d2B G2A Bcd|]",
    source: { ...SOURCE, where: "No. 1116, p. 211 (PDF page 222)" },
    transcription: "read from the scan (PDF page 222, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1155-the-kid-on-the-mountain",
    title: "The Kid on the Mountain",
    region: "irish",
    kind: "slip-jig",
    key: "Em",
    mode: "minor",
    meter: "9/8",
    origin: "Irish slip jig in six strains, each repeated; Gaelic title printed above it, An mionnan air an sliabh; no collector named in the print; every strain ends on D",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:The Kid on the Mountain\nM:9/8\nL:1/8\nK:Em\nEFE FED G2F|EFE cBA BGE|EFE FED G2G/A/|BAG FAG FED:|\n|:BGB AFA G2D|GAB dfe dcA|BGB AFA G2A|BAG FAG FED:|\n|:gfe efe e2e/f/|gfg efg afd|gfe efe e2g/a/|bag fag fed:|\n|:eBB e2f g2f|eBB efg afd|eBB e2f g2g/a/|bag fag fed:|\n|:eBe dBA G2A|Bee dBA BGE|eBe dBA G2A|BAG FAG FED:|\n|:B,EE eBG E2E|B,EE EFG AFD|B,EE eBG E2G/A/|BAG FAG FED:|",
    source: { ...SOURCE, where: "No. 1155, p. 218 (PDF page 229)" },
    transcription: "read from the scan (PDF page 229, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1003-the-connachtmans-rambles",
    title: "The Connachtman's Rambles",
    region: "irish",
    kind: "jig",
    key: "Bm",
    mode: "minor",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, Triallta an Connachtaigh; no collector named in the print; the pickup is a triplet of sixteenths",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Connachtman's Rambles\nM:6/8\nL:1/8\nK:Bm\n(3B/A/G/|FAA dAA|BAA dAG|FAA dfe|dBB BAG|\nFAA dAA|BAB def|gfe dfe|dBB B2:|\n|:f|fbb faa|fef def|fbb faa|fed e2e|\nfbb afe|dBc def|gfe dfe|dBB B2:|",
    source: { ...SOURCE, where: "No. 1003, p. 187 (PDF page 198)" },
    transcription: "read from the scan (PDF page 198, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-963-the-thief-of-lough-erne",
    title: "The Thief of Lough Erne",
    region: "irish",
    kind: "jig",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, An gadaidhe Locha-Ernaigh; setting credited in the print to F. O'Neill; the second strain has first and second endings",
    irregular: "the third bar of the first ending is printed B/ d c B2 A with no dot after the d, five and a half eighths; the same bar in the second ending carries the dot",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Thief of Lough Erne\nM:6/8\nL:1/8\nK:G\nG/A/|GED DCD|Adc B2A|GEE EGE|GEE E2A|\nGED DCD|Adc B2A|BGG G2A|BGG G2:|\n|:A|BGG dGG|BGG dGG|AFF cFF|AFA c2A|\n|1 BGG dGG|BGG dGG|B/dc B2A|BGG G2:|2 BGG AFF|GEE d2c|B/d3/2c B2A|BGG G2|]",
    source: { ...SOURCE, where: "No. 963, p. 179 (PDF page 190)" },
    transcription: "read from the scan (PDF page 190, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-730-cherish-the-ladies",
    title: "Cherish the Ladies",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig in six strains, each repeated; Gaelic title printed above it, Altram na mna; setting credited in the print to Gillan; the print returns by D.S. to the first strain and ends at its pause, written out here as a seventh strain",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Cherish the Ladies\nM:6/8\nL:1/8\nK:D\n(3A/B/c/|dFF AFF|DFA AGF|BEE GEE|GBA GFE|\ndFF AFF|DFA AFA|Bcd efg|fdd d2:|\n|:(3A/B/c/|dfd cec|dfd AGF|BEE GEE|GBA GFE|\ndfd cec|dfd AGF|Bcd efg|fdd d2:|\n|:A|dfd cec|dfd AGF|BzE GzE|GcB/A/ GFE|\ndGd cFc|dGd A2G|A3/2B/c/d/ efg|fdd d2:|\n|:B|Add fdd|add fdd|A/B/cd gfg|ece gfe|\nagf bge|afd cBA|(3f/g/a/ B2 AGF|GEF GFE:|\n|:f2f afd|fed cde|g2g gfg|ece gfe|\nagf bge|afd cBA|fdB AGF|GEF GFE:|\n|:DFA dAF|DFA BGE|DFA dAF|GEF GFE|\nDFA DGB|DFA d2e|fdB AGF|GEF GFE:|\ndFF AFF|DFA AGF|BEE GEE|GBA GFE|\ndFF AFF|DFA AFA|Bcd efg|fdd d2|]",
    source: { ...SOURCE, where: "No. 730, p. 136 (PDF page 147)" },
    transcription: "read from the scan (PDF page 147, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1158-riding-a-mile",
    title: "Riding a Mile",
    region: "irish",
    kind: "slip-jig",
    key: "Ador",
    mode: "dorian",
    meter: "9/8",
    origin: "Irish slip jig, 2nd setting; Gaelic title printed above it, Ag marcuigheacht mile; setting credited in the print to F. O'Neill; one sharp in the signature and both strains end on A",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:Riding a Mile\nM:9/8\nL:1/8\nK:Ador\ndBG G2D G3|dBG GBd gfe|dBG G2D G3|E2A A2B cBA:|\n|:GBd gaf g3|GBd g2B cBA|GBd gaf g2B|cBc A2B cBA:|",
    source: { ...SOURCE, where: "No. 1158, p. 218 (PDF page 229)" },
    transcription: "read from the scan (PDF page 229, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1159-dont-leave-me-alone",
    title: "Don't Leave Me Alone",
    region: "irish",
    kind: "slip-jig",
    key: "G",
    mode: "major",
    meter: "9/8",
    origin: "Irish slip jig; printed as Dont Leave Me Alone, Gaelic title printed above it, Na fag me an aonar; no collector named in the print",
    irregular: "the last bar of each strain is printed c2 B A G F G2, eight eighths, with no pickup elsewhere to make up the ninth",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:Don't Leave Me Alone\nM:9/8\nL:1/8\nK:G\ng2f efg dcB|e2A ABG FED|g2f efg dcB|c2B AGF G2:|\n|:B2c dcB dcB|e2A ABG FED|B2c dcB dcB|c2B AGF G2:|",
    source: { ...SOURCE, where: "No. 1159, p. 218 (PDF page 229)" },
    transcription: "read from the scan (PDF page 229, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1025-the-northern-road",
    title: "The Northern Road",
    region: "irish",
    kind: "jig",
    key: "Bm",
    mode: "minor",
    meter: "6/8",
    origin: "Irish double jig; Gaelic title printed above it, An bothar o thuaidh; setting credited in the print to Dillon; two sharps in the signature and both strains end on B; the second strain has first and second endings",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Northern Road\nM:6/8\nL:1/8\nK:Bm\nd|AGF A2D|DED FED|AGF A2D|F3 d3|\nAGF A2D|DED AGF|EFE E2F|G3 B3:|\n|:ABc d2F|AGF d2F|ABc dAF|B3 d3|\n|1 ABc ded|cBA d2A|Bcd EFE|G3 B3:|2 faf gec|fdB AFD|EFE E2F|G3 B3|]",
    source: { ...SOURCE, where: "No. 1025, p. 191 (PDF page 202)" },
    transcription: "read from the scan (PDF page 202, a 96 dpi page image; every note head measured against the staff lines beside it and every staff checked by eye in halves at 5x and 9x for rhythm, ledger lines and accidentals) and proofed bar by bar by lane MELODIES200 reader oneill1903-jigs, 2026-10-02",
  },
  {
    id: "oneill-1174-a-fig-for-a-kiss",
    title: "A Fig for a Kiss",
    region: "irish",
    kind: "slip-jig",
    key: "E",
    mode: "minor",
    meter: "9/8",
    origin: "Irish slip jig, Gaelic title Ni Mait Liom Pog; the print credits Carey. Printed with one sharp; both strains close on E, so read as E minor by the rule of the final note. The first strain repeats; the second strain is printed once, without repeats",
    irregular: "the last bar of the first strain is printed B/ c/ d B A G F E2, eight eighths, before the repeat; the matching bar that ends the tune carries a dotted E and fills the meter",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:A Fig for a Kiss\nM:9/8\nL:1/8\nK:Em\nG2B E2B BAG|F2A D2A AGF|G2B E2B BAG|B/c/dB AGF E2:|\ng2e g2e edB|f2d ded fed|g2e g2e edB|dBG GBd e2f|\ng2e g2e edB|f2d ded fed|g2e f2^d e=dB|BdB AGF E3|]",
    source: { ...SOURCE, where: "No. 1174, p. 221 (PDF page 232)" },
    transcription: "read from the scan (PDF page 232, each staff deskewed and read in quarters at 800 dpi equivalent, accidentals and dots checked again at 1100 to 1300 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-1173-johnny-oshea",
    title: "Johnny O'Shea",
    region: "irish",
    kind: "slip-jig",
    key: "E",
    mode: "minor",
    meter: "9/8",
    origin: "Irish slip jig, Gaelic title Seanin ua Seaghdha; the print names no player. Printed with one sharp and a sharpened D before the closing E of each strain, so read as E minor by the rule of the final note. Both strains repeat, and each opens on a one-note pickup that completes its short last bar",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:Johnny O'Shea\nM:9/8\nL:1/8\nK:Em\nd|efe edB BAG|efe edB efg|e/f/ge edB BAG|dBA AB^d e2:|\n|:e|gag gdB BAG|gbg gdB gab|bag agf edB|dBA AB^d e2:|",
    source: { ...SOURCE, where: "No. 1173, p. 221 (PDF page 232)" },
    transcription: "read from the scan (PDF page 232, each staff deskewed and read in quarters at 800 dpi equivalent, ledger notes and accidentals checked again at 1300 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-1172-come-up-stairs-with-me",
    title: "Come Up Stairs With Me",
    region: "irish",
    kind: "slip-jig",
    key: "G",
    mode: "major",
    meter: "9/8",
    origin: "Irish slip jig, Gaelic title Tar Suas na Staighre Liom; the print credits Carey. The four-bar first strain, opening on a one-note pickup, repeats; the eight-bar second strain is printed once and closes on the first strain's cadence",
    tags: ["dance", "jig", "slip-jig", "irish"],
    abc: "X:1\nT:Come Up Stairs With Me\nM:9/8\nL:1/8\nK:G\nD|G2c BAG Bcd|ecA ABG FED|G2c BAG Bcd|efg faf g2:|\ng|fed d2g fed|ecA ABG FED|fed d2g fed|efg faf g2g|\nfed d2g fed|ecA ABG FED|G2c BAG Bcd|efg faf g2|]",
    source: { ...SOURCE, where: "No. 1172, p. 221 (PDF page 232)" },
    transcription: "read from the scan (PDF page 232, each staff deskewed and read in quarters at 800 dpi equivalent, ledger notes checked again at 1100 to 1200 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-778-kitty-come-over",
    title: "Kitty Come Over",
    region: "irish",
    kind: "jig",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, Gaelic title Tar a Leith a Caitilin; the print credits McNamara. Both strains repeat; each opens on a one-note pickup, and the short closing bar of each strain completes it",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Kitty Come Over\nM:6/8\nL:1/8\nK:G\nc|BcA BGE|GAG GBd|efg ded|BAA A2c|\nBcA BGE|GAG GBd|efg dec|BGG G2:|\n|:f|gfg efg|fag fed|gfg efd|eAA A2c|\nBcA BGE|GAG GBd|efg dec|BGG G2:|",
    source: { ...SOURCE, where: "No. 778, p. 145 (PDF page 156)" },
    transcription: "read from the scan (PDF page 156, each staff deskewed and read in quarters at 800 dpi equivalent, doubtful heads checked again at 1100 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-784-the-humors-of-whiskey",
    title: "The Humors of Whiskey",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, Gaelic title Sugra na Uisge-beatha; the print credits Tobin. Both strains repeat; each opens on a one-note pickup, and the short closing bar of each strain completes it",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Humors of Whiskey\nM:6/8\nL:1/8\nK:D\nA|dfd ecA|dcB AGF|GBB FAA|GFG E2A|\ndcd ecA|dcB AFA|Bcd efg|fdd d2:|\n|:B|AFA dcd|BGB ede|AFA dAF|GFG EFG|\nAFA dcd|BGB ede|faf ede|fdd d2:|",
    source: { ...SOURCE, where: "No. 784, p. 146 (PDF page 157)" },
    transcription: "read from the scan (PDF page 157, each staff deskewed and read in quarters at 800 dpi equivalent, every head placed against the measured staff lines) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-779-the-humors-of-cappa",
    title: "The Humors of Cappa",
    region: "irish",
    kind: "jig",
    key: "D",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, Gaelic title Sugra na Ceapaigh; the print credits McNamara. Both strains repeat; each opens on a one-note pickup, and the short closing bar of each strain completes it",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Humors of Cappa\nM:6/8\nL:1/8\nK:D\nA|dFF AFA|dFF AFA|BEE BEE|BdB AFA|\ndFF AFA|dFF AFA|ABd efg|fdd d2:|\n|:A|dfd cec|BdB AFA|BEE BEE|BdB AFA|\ndfd cec|BdB AFA|ABd efg|fdd d2:|",
    source: { ...SOURCE, where: "No. 779, p. 145 (PDF page 156)" },
    transcription: "read from the scan (PDF page 156, each staff deskewed and read in quarters at 800 dpi equivalent, every head placed against the measured staff lines, the signature checked at 1100 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-962-the-tongs-by-the-fire",
    title: "The Tongs by the Fire",
    region: "irish",
    kind: "jig",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish double jig, Gaelic title An T-Ursal Taobh na Teinne; the print credits F. O'Neill. Both strains repeat; each opens on a one-note pickup, and the short closing bar of each strain completes it",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:The Tongs by the Fire\nM:6/8\nL:1/8\nK:G\nD|GBd cAF|Gge dBG|c/e3/2c BdB|ABG FED|\nGBd cAF|Gge dBd|cec Bag|fef g2:|\n|:d|gdB gdB|gfa gdB|gfg eag|fdd def|\ngbg faf|ege def|gdB AGA|BGG G2:|",
    source: { ...SOURCE, where: "No. 962, p. 179 (PDF page 190)" },
    transcription: "read from the scan (PDF page 190, each staff deskewed and read in quarters at 800 dpi equivalent, the dotted figure in bar 3 checked at 1300 dpi equivalent) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
  {
    id: "oneill-785-fiddlers-heaven",
    title: "Fiddler's Heaven",
    region: "irish",
    kind: "jig",
    key: "A",
    mode: "mixolydian",
    meter: "6/8",
    origin: "Irish double jig, Gaelic title Flaitheas na bhFidileiridhe; the print credits Delaney. Printed with two sharps; both strains close on A, so read as A mixolydian by the rule of the final note. Both strains repeat; each opens on a pickup of two sixteenths, and the short closing bar of each strain completes it",
    tags: ["dance", "jig", "irish"],
    abc: "X:1\nT:Fiddler's Heaven\nM:6/8\nL:1/8\nK:Amix\nB/c/|dAF FEF|ded dfe|dAF FEF|AFE EFA|\ndAF FEF|ded def|ecA BAF|EAA A2:|\n|:c/d/|ecA AcA|ecA A2c/d/|ecA BAG|AFE E2c/d/|\necA AcA|ecA d2B|cAF EFA|BAA A2:|",
    source: { ...SOURCE, where: "No. 785, p. 146 (PDF page 157)" },
    transcription: "read from the scan (PDF page 157, each staff read in five overlapping windows at 1100 dpi equivalent, every head placed against the staff lines beside it) and proofed bar by bar by lane MELODIES200 reader oneill1903-reels, 2026-10-03",
  },
];

export default TUNES;
