// settle-hear · tunes/oneill1903-airs-b - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book page: wikis/WIKI_OLD_MELODIES/books/BOOK_ONEILL1903_AIRS_B.md (airs Nos. 211 to 420; printed page + 12 = PDF page).

export const SOURCE = {
  kind: 'print',
  book: "O'Neill's Music of Ireland: Eighteen Hundred and Fifty Melodies",
  compiler: "Capt. Francis O'Neill, arranged by James O'Neill",
  year: 1903,
  scan: 'https://archive.org/details/oneills-1850',
};

export const TUNES = [
  {
    id: 'oneill-263-kate-kearney',
    title: 'Kate Kearney',
    region: 'irish',
    kind: 'song-air',
    key: 'G',
    mode: 'major',
    meter: '3/4',
    origin: "Irish song air; Gaelic title printed above it, Cait ni Carnaig; marked Moderate; setting credited in the print to F. O'Neill",
    tags: ['air', 'slow', 'irish'],
    abc: 'X:1\nT:Kate Kearney\nM:3/4\nL:1/8\nK:G\nD2|D2 E2 G2|G2 A2 B2|A2 G2 G2|G4 D2|G2 B2 d2|edcBAG|B2 A2 A2|\nA4 Bd|e2 c2 e2|d2 B2 d2|c2 A2 c2|B4 GA|B2 A2 B2|G2 E2 D2|E2 G2 G2|G4||\nD2|D2 B,2 D2|D2 B,2 D2|G6|G4 D2|D2 B,2 D2|D2 B,2 D2|A6|A4 Bd|\ne3 c e2|d2 B2 d2|c3 A c2|B2 G2 A2|B2 A2 B2|G2 E2 D2|E6|G4|]',
    source: { ...SOURCE, where: 'No. 263, p. 46 (PDF page 58)' },
    transcription: 'read from the scan (PDF page 58, each staff in quarters at 600 dpi) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs-b, 2026-10-02',
  },
  {
    id: "oneill-392-eileen-aroon",
    title: "Eileen Aroon (1st setting)",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish song air, Gaelic title Eibhlin a Ruin; 1st setting; marked Slow; setting credited in the print to Mrs. Lavin",
    tags: ["air", "slow", "irish"],
    abc: "X:392\nT:Eileen Aroon\nM:3/4\nL:1/8\nK:D\ndB | A2 B2 dB | d2 e2 f2 | F2 A2 ed | B4 dB |\nA2 B2 dB | d2 e2 f2 | F2 A2 Bd | d4 ||\ndf | gg f2 fe | fa a2 fe | dd e2 dB | A4 f2 |\na2 fedB | de f4 | F2 A2 Bd | d4 |]",
    source: { ...SOURCE, where: "No. 392, p. 68 (PDF page 80)" },
    transcription: "read from the scan (PDF page 80; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-389-a-mothers-lamentation",
    title: "A Mother's Lamentation",
    region: "irish",
    kind: "lament",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish lament, Gaelic title Uaill-chumha na Mathar; marked Slow; two fermatas left out",
    tags: ["air", "slow", "lament", "irish"],
    abc: "X:389\nT:A Mother's Lamentation\nM:3/4\nL:1/8\nK:D\nD3/2F/ A2 B3/2A/ | Ad F2 E3/2E/ | DF A2 B3/2c/ | d4 f3/2d/ | A2 d2 d3/2c/ |\nB3c B3/2A/ | AFAB d3/2B/ | A3/2F/ E3/2D/ EE | DD D4 ||\nFD FA B2 | A3/2F/ d2 A3/2F/ | E3/2D/ FA d3/2d/ | f4 fd | e4 f3/2d/ |\ne2 c2 d3/2B/ | AFAB d3/2d/ | B3/2A/ FD E3/2F/ | DD D4 |]",
    source: { ...SOURCE, where: "No. 389, p. 68 (PDF page 80)" },
    transcription: "read from the scan (PDF page 80; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-388-the-irish-exile",
    title: "The Irish Exile",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "6/8",
    origin: "Irish air, Gaelic title An Deoraidhe Eireannach; marked Slow; accents and a fermata left out",
    tags: ["air", "slow", "irish"],
    abc: "X:388\nT:The Irish Exile\nM:6/8\nL:1/8\nK:G\nG/A/ | B3/2A/G EAA | A3 A2 G/A/ | B3/2A/G EGG | G3 G2 G/A/ | BGB d2 B/d/ | ece d2 d/c/ |\nB3/2A/G EAA | A3 A2 G/A/ | BGB d2 B/d/ | ece d2 d/c/ | B3/2A/G EGG | G3 G2 |]",
    source: { ...SOURCE, where: "No. 388, p. 68 (PDF page 80)" },
    transcription: "read from the scan (PDF page 80; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-219-oft-in-the-stilly-night",
    title: "Oft in the Stilly Night",
    region: "irish",
    kind: "song-air",
    key: "D",
    mode: "major",
    meter: "2/4",
    origin: "Irish song air, Gaelic title Is minic annsa n-oidhche chiuin; marked Moderate; setting credited in the print to J. O'Neill; printed with a D.C. to the pause at the end of the first strain, written out here in full; one grace note left out",
    tags: ["air", "slow", "irish"],
    abc: "X:219\nT:Oft in the Stilly Night\nM:2/4\nL:1/8\nK:D\nA | f2 f3/2e/ | d3/2B/ Bd | A3/2A/ FD | E4 | FAAB | AFDd | fdec | d2-d ||\nB | A3/2d/ dd | B3/2d/ dd | f3/2d/ dd | edcB | A3/2d/ dd | B3/2d/ dd | fdec | d2-d ||\nA | f2 f3/2e/ | d3/2B/ Bd | A3/2A/ FD | E4 | FAAB | AFDd | fdec | d2-d |]",
    source: { ...SOURCE, where: "No. 219, p. 38 (PDF page 50)" },
    transcription: "read from the scan (PDF page 50; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-253-the-battle-eve",
    title: "The Battle Eve",
    region: "irish",
    kind: "air",
    key: "Bb",
    mode: "major",
    meter: "4/4",
    origin: "Irish air, Gaelic title An Trathnona Roimhe an Treas; marked Animated; setting credited in the print to F. O'Neill; accents and a slur left out",
    tags: ["air", "irish"],
    abc: "X:253\nT:The Battle Eve\nM:C\nL:1/8\nK:Bb\nD2 | G3^F G2A2 | G4 B3B | AF3 F3F | F4 ^F3^F | D2G2 G2A2 | B4 A2G2 | D4 E4 | D6 f2 |\nf3d B2d2 | f4 =e2d2 | c3A F2A2 | c4 B3c | d3B c3A | D4 G3^F | G4 A4 | B4 B2c2 |\nd3d c2B2 | f4 F3F | B4 |]",
    source: { ...SOURCE, where: "No. 253, p. 44 (PDF page 56)" },
    transcription: "read from the scan (PDF page 56; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-260-the-boyne-water",
    title: "The Boyne Water",
    region: "irish",
    kind: "song-air",
    key: "A",
    mode: "dorian",
    meter: "4/4",
    origin: "Irish song air, Gaelic title Uisge na Boinne; marked Moderate; setting credited in the print to F. O'Neill; printed with a one-sharp signature and ending on A, with sharpened C and G in the second strain",
    tags: ["air", "irish"],
    abc: "X:260\nT:The Boyne Water\nM:C\nL:1/8\nK:Ador\nAG | E2e2 efge | dcBA G2AB | c2BA edcB | ABAG E3D |\nE2e2 efge | dcBA G2AB | c2BA edcB | A4 A2 ||\n^cd | e2a2 a2b2 | a^ge^c d2cd | e2a2 ^gabg | a3^g e2f2 |\n=gfga g2fe | dcBA G2AB | c2BA edcB | A4 A2 |]",
    source: { ...SOURCE, where: "No. 260, p. 45 (PDF page 57)" },
    transcription: "read from the scan (PDF page 57; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-222-a-stranger-in-cork",
    title: "A Stranger in Cork",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Coimhitheach annsa Cathair Chorcaigh; marked Moderate; setting credited in the print to M. O'Brien",
    tags: ["air", "slow", "irish"],
    abc: "X:222\nT:A Stranger in Cork\nM:3/4\nL:1/8\nK:G\ndc|B2 G2 E2|D2 B,2 D2|E2 G2 A2|G4 D2|G2 B2 d2|d2 B2 d2|e2 d2 B2|\nA4 D2|G2 B2 d2|d2 B2 d2|e2 d2 B2|A4 dc|B2 G2 E2|D2 B,2 D2|E2 G2 G2|G4|]",
    source: { ...SOURCE, where: "No. 222, p. 39 (PDF page 51)" },
    transcription: "read from the scan (PDF page 51; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-217-i-love-thee-no-more",
    title: "I Love Thee No More",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Ni is Gradh Liom Tu; marked Moderate; no name of a contributor printed",
    tags: ["air", "slow", "irish"],
    abc: "X:217\nT:I Love Thee No More\nM:3/4\nL:1/8\nK:G\nd3/2c/|B2 G2 D2|E2 A2 zG|F3 E D2|G2 B2 d2|c3 d c2|B2 c2 d2|e2 c2 AG|F2 z2 d3/2c/|\nB2 G2 D2|E2 A3 G|F3 E D2|G2 B2 D2|EFGABc|d2 B2 cA|G3 A F2|G2 z2||\nd2|F3 G E2|D2 z2 GF|EDECAG|FEFDBA|GFGEcB|AF D2 zD|E3 F GA|d2 B2 cA|G3 A F2|G2 z2|]",
    source: { ...SOURCE, where: "No. 217, p. 38 (PDF page 50)" },
    transcription: "read from the scan (PDF page 50; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-230-the-joys-of-summer",
    title: "The Joys of Summer",
    region: "irish",
    kind: "air",
    key: "Bb",
    mode: "major",
    meter: "4/4",
    origin: "Irish air, Gaelic title Taitneamh na Samhradh; marked Moderate; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:230\nT:The Joys of Summer\nM:C\nL:1/8\nK:Bb\nF2|B3A G2AB|c3B A2F2|G4 A4|B4 z2F2|B3A G2AB|c3B A2F2|G4 A4|B6||\nd2|e2 d2 e2 f2|g2 f2 e2 zd|e2 d2 c2 B2|d2 c2 B2 A2|B3A G2AB|c3B A2F2|G4 A4|B6|]",
    source: { ...SOURCE, where: "No. 230, p. 40 (PDF page 52)" },
    transcription: "read from the scan (PDF page 52; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-241-the-charming-fair-maid",
    title: "The Charming Fair Maid",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title An Cailin Deas Alainn; marked Slow; setting credited in the print to J. O'Neill; the first bar is printed as two crotchet rests and a pair of quavers",
    tags: ["air", "slow", "irish"],
    abc: "X:241\nT:The Charming Fair Maid\nM:3/4\nL:1/8\nK:D\nz2 z2 dc|A2 A2 Bc|d4 de|f4 ed|e2 d4|f4 gf|e4 a2|d2 c2 d2|e2 d4||\ned d2 cB/A/|AB c2 z2|edd cBA|AG F2 ED|C4 DE|F4 AG|E4 GE|D2 C2 D2|E2 D4|]",
    source: { ...SOURCE, where: "No. 241, p. 41 (PDF page 53)" },
    transcription: "read from the scan (PDF page 53; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-245-ill-be-a-good-boy",
    title: "I'll Be a Good Boy",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Beidh me Buachaill Macanta; marked Moderate; setting credited in the print to J. O'Neill; a grace note in the second-last bar is left out",
    tags: ["air", "slow", "irish"],
    abc: "X:245\nT:I'll Be a Good Boy\nM:3/4\nL:1/8\nK:D\nAd|f2 gf ed|c2 A2 A3/2G/|F2 D2 D3/2E/|D4 Ad|fg a2 gf|ef g2 fe|dc A2 A2|A4 de|\nfg a2 gf|ef g2 fe|d3/2c/ de fg|f4 ef/e/|d2 A2 A3/2G/|F2 D2 FG|A2 d2 de|d4|]",
    source: { ...SOURCE, where: "No. 245, p. 42 (PDF page 54)" },
    transcription: "read from the scan (PDF page 54; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-243-the-fairy-boy",
    title: "The Fairy Boy",
    region: "irish",
    kind: "air",
    key: "A",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title An Buachaill Sidhe; marked Moderate; setting credited in the print to F. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:243\nT:The Fairy Boy\nM:3/4\nL:1/8\nK:A\nE2|Ac E2 FG|Ac f2 e2|fe c3 A|BA F2 G2|Ac E2 FG|Ac f2 e2|fe c3 A|c3/2B/ A2||\ne2|ec f3 e|cA B3 A|cA f3 e|cA B3 c/B/|Ac E2 FG|Ac f2 e2|fe c3 A|c3/2B/ A2|]",
    source: { ...SOURCE, where: "No. 243, p. 42 (PDF page 54)" },
    transcription: "read from the scan (PDF page 54; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-265-finnigans-wake",
    title: "Finnigan's Wake",
    region: "irish",
    kind: "song-air",
    key: "C",
    mode: "major",
    meter: "2/4",
    origin: "Irish song air, Gaelic title Torramh Ui Finnguine; marked Lively; setting credited in the print to F. O'Neill",
    tags: ["air", "irish"],
    abc: "X:265\nT:Finnigan's Wake\nM:2/4\nL:1/8\nK:C\nG/F/|EG GA/B/|cc cd/e/|fd ed/c/|AG GG/F/|EG GA/B/|cc cd/e/|fd ed/c/|AG G||\nc/d/|egge|dcAc|egge|dc dc/d/|egge|dc cd/e/|fd ed/c/|AG G|]",
    source: { ...SOURCE, where: "No. 265, p. 46 (PDF page 58)" },
    transcription: "read from the scan (PDF page 58; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-420-the-ashtree-grove",
    title: "The Ashtree Grove",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Coillte Oinseoga; marked Slow; setting credited in the print to J. O'Neill",
    tags: ["air", "slow", "irish"],
    abc: "X:420\nT:The Ashtree Grove\nM:3/4\nL:1/8\nK:D\nDE|F2 D2 EF|G2 A2 AG|E2 D2 D2|D4 (3ABc|d2 d2 ed|=c2 B2 AG|E2 G2 B2|\nA4 (3ABc|d2 d2 ed|=c2 BA GE|G2 A2 B2|A4 AG|F2 D2 EF|G2 A2 AG|E2 D2 D2|D4|]",
    source: { ...SOURCE, where: "No. 420, p. 73 (PDF page 85)" },
    transcription: "read from the scan (PDF page 85; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-02",
  },
  {
    id: "oneill-275-the-forlorn-lover",
    title: "The Forlorn Lover",
    region: "irish",
    kind: "air",
    key: "G",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title An Gradhuightheoir Treigthe; marked Moderate; setting credited in the print to J. O'Neill; the first strain is repeated",
    tags: ["air", "slow", "irish"],
    abc: "X:275\nT:The Forlorn Lover\nM:3/4\nL:1/8\nK:G\n|:G2|B2 B2 B2|B3 A G2|e2 A2 A2|A4 GA|B2 dB AG|E2 D2 GA|B3 c BA|G4:|\nB2|d2 d2 d2|d2 cB AG|G2 g2 g2|g4 Bc|d2 d2 d2|edcBAG|G2 g2 f2|g4 de|\n=f3 g f2|e4 g2|d2 cB AG|A4 GA|B2 dB AG|E2 D2 GA|B3 c BA|G4|]",
    source: { ...SOURCE, where: "No. 275, p. 48 (PDF page 60)" },
    transcription: "read from the scan (PDF page 60; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-289-on-the-mountain-side",
    title: "On the Mountain Side",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title Air Taobh an Sleibhe; marked Slow; setting credited in the print to O'Brien",
    tags: ["air", "slow", "irish"],
    abc: "X:289\nT:On the Mountain Side\nM:3/4\nL:1/8\nK:D\nA2|d2 A2 GE|c2 B2 AG|E2 D2 D2|D4 EF|G2 A2 Bc|d2 e2 ed|BAGABG|A4 EF|\nG2 A2 Bc|d2 e2 ed|BAGABG|A4 A2|d2 A2 GE|c2 B2 AG|E2 D2 D2|D4|]",
    source: { ...SOURCE, where: "No. 289, p. 50 (PDF page 62)" },
    transcription: "read from the scan (PDF page 62; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-293-the-jug-and-it-full",
    title: "The Jug and It Full",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title An Cruisgin agus e Lan; marked Slow; setting credited in the print to F. O'Neill; the grace notes before bars 5, 11 and 23 are left out",
    tags: ["air", "slow", "irish"],
    abc: "X:293\nT:The Jug and It Full\nM:3/4\nL:1/8\nK:D\nF3/2G/|A2 f2 ef|d2 cA Bc|d3 efd|dc A2 AG|E2 D2 D2|D4 F3/2G/|A2 f2 ef|\nd2 cA AB/c/|d3 efd|dc A3/2B/ AG|E2 D2 D2|D4||\nDE|F2 G2 AB|=c2 dc AG|F2 D2 DE|FGAB cA|dc A2 A2|A3 GFG|A2 f2 ef|d2 cA Bc|d3 efd|dc A2 AG|E2 D2 D2|D4|]",
    source: { ...SOURCE, where: "No. 293, p. 51 (PDF page 63)" },
    transcription: "read from the scan (PDF page 63; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-319-one-wife-is-enough-for-me",
    title: "One Wife Is Enough for Me",
    region: "irish",
    kind: "air",
    key: "A",
    mode: "minor",
    meter: "3/4",
    origin: "Irish air, Gaelic title Is Mo Shaith Aon Cheile Amhain; marked Moderate; setting credited in the print to J. O'Neill; printed with no signature and ending on A",
    tags: ["air", "slow", "irish"],
    abc: "X:319\nT:One Wife Is Enough for Me\nM:3/4\nL:1/8\nK:Am\ncB|A3 B A2|A2 G2 E2|c6|d2 c2 d2|e3 d c2|c2 d2 e2|G6-|G2 c3 B|A3 B A2|A2 G2 E2|\nc6|d2 c2 d2|e2 f2 e2|d2 c2 B2|A6-|A4||\ne2|e2 c2 e2|g2 e2 c2|B2 G4-|G2 d2 e2|f2 e2 d2|c2 d2 e2|G6-|G2 c2 B2|A3 B A2|A2 G2 E2|c6|d2 c2 d2|e2 f2 e2|d2 c2 B2|A6-|A4|]",
    source: { ...SOURCE, where: "No. 319, p. 55 (PDF page 67)" },
    transcription: "read from the scan (PDF page 67; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
  {
    id: "oneill-320-the-romantic-kerryman",
    title: "The Romantic Kerryman",
    region: "irish",
    kind: "air",
    key: "D",
    mode: "major",
    meter: "3/4",
    origin: "Irish air, Gaelic title An Ciarraigheach Finnsgeulach; marked With spirit; setting credited in the print to F. O'Neill",
    tags: ["air", "irish"],
    abc: "X:320\nT:The Romantic Kerryman\nM:3/4\nL:1/8\nK:D\nAG|F2 E2 D2|F4 G2|A4 AG|A2 B2 c2|d2 d2 d2|c2 d2 c2|A2 B2 c2|d4 AG|F2 E2 D2|F4 G2|\nA4 AG|A2 B2 c2|d2 f2 d2|c2 A2 G2|F2 D2 D2|D4||\nAG|F2 G2 A2|A2 B2 c2|d4 e2|f2 e2 d2|c2 B2 A2|A2 B2 c2|d6-|d4 de|f2 e2 d2|c2 A2 G2|F2 D2 E2|F2 G2 A2|A2 d2 d2|c2 A2 G2|F2 D2 D2|D4|]",
    source: { ...SOURCE, where: "No. 320, p. 55 (PDF page 67)" },
    transcription: "read from the scan (PDF page 67; the scan is 96 ppi, so each staff was read from its native pixels enlarged, with a skew-fitted staff, a notehead locator and pixel-level checks of every doubtful head) and proofed bar by bar by lane MELODIES200 reader oneill1903-airs, 2026-10-03",
  },
];

export default TUNES;
