// settle-hear · tunes/petrie1855 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// The book is a piano setting: each melody is the top line of the right hand (the top note of any chord).
// PDF page = printed page + 28 (the Internet Archive page images n<printed+28>.jpg match the PDF pages).

export const SOURCE = {
  kind: 'print',
  book: 'The Petrie Collection of the Ancient Music of Ireland, arranged for the piano-forte, vol. 1',
  compiler: 'George Petrie (1790-1866), for the Society for the Preservation and Publication of the Melodies of Ireland',
  year: 1855,
  scan: 'https://archive.org/details/petriecollection01petr',
};

const READ = (pdf) => `read from the scan (PDF page ${pdf}, the original jp2 page image, each staff in halves at about 500 dpi) and proofed bar by bar by lane MELODIES200 reader petrie1855, 2026-10-02`;

export const TUNES = [
  {
    id: 'petrie-p57-name-unknown-londonderry-air',
    title: 'Name unknown (the Londonderry Air)',
    region: 'irish',
    kind: 'air',
    key: 'Eb', mode: 'major', meter: 'C',
    origin: 'Printed as "Name unknown"; the air later known as the Londonderry Air. Petrie had it from Miss Jane Ross of Newtown-Limavady, Co. Londonderry, who sent it to him with the remark that it was "very old". Marked Andante. In bar 5 the dot after the first G is not printed; the lower voice places the F on the fourth quaver, so the G is read as a dotted crotchet, as printed in bar 1',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:1\nT:Name unknown (the Londonderry Air)\nM:C\nL:1/8\nK:Eb\nDEF | G3 F GcBG | FE C2 z EGA | B3 c BGFG | F4 z DEF |\nG3 F GcBG | FEC=B, CDEF | G3 A GFEF | E4 z || Bcd |\ne3 d dcBG | BG E2 z Bcd | e3 d dcBG | F4 z BBB |\ng3 f fece | BG E2 z DEF | GcBG FECD | E4- E |]',
    source: { ...SOURCE, where: 'p. 57 (PDF page 85)' },
    transcription: READ(85),
  },
  {
    id: 'petrie-p10-the-pearl-of-the-white-breast',
    title: 'The Pearl of the White Breast',
    region: 'irish',
    kind: 'air',
    key: 'F', mode: 'major', meter: 'C',
    origin: 'Irish air, Irish title Pearla an Bhrollaigh Bhain (printed in Gaelic type); noted by Petrie from the singing of Eugene Curry of Co. Clare, who learned it from his father. Marked Andante; grace notes left out',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:2\nT:The Pearl of the White Breast\nM:C\nL:1/8\nK:F\nc d/e/ | f3/2e/ dc f3 d | cA GF G2 AB | c2 AF BA G3/2F/ | F6 c d/e/ |\nfe dc f3 d | cA GF G2 AB | c2 AF BA G3/2F/ | F6 || cB |\nAc df e3 c | fe d3/2c/ c3 c | de fa gf ec | c6 c d/e/ |\nfe dc f3 d | cA GF G2 AB | c2 AF B3/2A/ G3/2F/ | F6 |]',
    source: { ...SOURCE, where: 'p. 10 (PDF page 38)' },
    transcription: READ(38),
  },
  {
    id: 'petrie-p168-the-winter-it-is-past-curragh-of-kildare',
    title: 'The Winter it is past; or, The Curragh of Kildare',
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'mixolydian', meter: 'C',
    origin: 'Irish song air noted by Petrie in his young days from the singing of Betty Skillin; other settings came to him from Mr. Patrick Joyce and Kate Cudmore of Glenroe, Co. Limerick. Marked Andante. The signature is two flats and the melody ends on F; Petrie harmonises the close in B flat, so the air ends on its fifth. The third strain repeats the second, as printed',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:3\nT:The Winter it is past; or, The Curragh of Kildare\nM:C\nL:1/8\nK:Fmix\nF | FD FG B2 e>d | cB G>F F2 AB | c2 de f2 ed | c4- c2 cd |\nec de f2 ed | cB GF F2 FG | B2 ed cB G>F | F4- F2 cd |\nec de f2 ed | cB GF F2 FG | B2 ed cB G>F | F4- F3 |]',
    source: { ...SOURCE, where: 'p. 168 (PDF page 196)' },
    transcription: READ(196),
  },
  {
    id: 'petrie-p3-the-red-haired-girl',
    title: 'The Red-haired Girl',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '3/4',
    origin: 'Irish love-song air, Irish title An Cailin Ruadh (printed in Gaelic type), the Colleen Rue; Petrie heard it sung in parts in a tavern at Dalkey near Dublin in the summer of 1815 and learned it from the singers. Marked Andante con moto. Two small grace notes in the twelfth bar left out; the flat on the D in the fourteenth bar is as printed',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:4\nT:The Red-haired Girl\nM:3/4\nL:1/16\nK:Eb\nBA G2B2 | c3A F2E2 D2F2 | E4 FGA2 G2B2 | c3A F2D2 E2E2 |\nE6 BA G2B2 | c3A F2E2 D2F2 | E4 F2GA G2B2 | c3A F2D2 E2E2 | E6 ||\nBA G2B2 | e4 d2ef e2c2 | A2F2 G3A G2B2 | e4 d2ef g2e2 |\ne2d3/2c/2 B3A G2B2 | e4 defg e2c2 | A3F G2A2 Bc_d2 | c3A F2D2 E2E2 | E6 |]',
    source: { ...SOURCE, where: 'p. 3 (PDF page 31)' },
    transcription: READ(31),
  },
  {
    id: 'petrie-p91-black-cloaks-to-cover-bobby-lament-for-gerald',
    title: 'Black Cloaks to cover Bobby; or, The Lament for Gerald',
    region: 'irish',
    kind: 'lament',
    key: 'Eb', mode: 'major', meter: '6/8',
    origin: 'Irish lament air given to Petrie more than forty years before by a young friend named O\'Sullivan, then a medical student in Dublin, who had learned it in his boyhood in Co. Kerry. Marked Andante. The fermatas in bars 4 and 8 and one small grace note in bar 10 left out; the opening is a triplet of semiquavers, as printed',
    tags: ['air', 'slow', 'lament', 'irish'],
    abc: 'X:5\nT:Black Cloaks to cover Bobby; or, The Lament for Gerald\nM:6/8\nL:1/8\nK:Eb\n(3B/c/d/ | e2e d2B | c2c B2G | F2G E2E | E3- E2 E/F/ | G2A B2B |\nG2A B2B | c2c c2c | B3- B2 E/F/ | G2A B2B | G2A B2B | c2c c3/2d/c |\nB3 Bcd | e2e dcB | c2c BAG | F2G E2E | E3- E2 |]',
    source: { ...SOURCE, where: 'p. 91 (PDF page 119)' },
    transcription: READ(119),
  },
  {
    id: 'petrie-p73-an-irish-lullaby-seo-hu-leo',
    title: 'An Irish Lullaby (Seo hu leo)',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '2/4',
    origin: 'Irish lullaby, Irish title Seo hu leo (printed in Gaelic type); noted with its song from the singing of Mary Madden, a poor blind peasant woman from Limerick then living in Dublin. Petrie gives it as an example of the Suantraidhe, the sleep-disposing music of Irish tradition. Marked Allegretto, the close Lent. Grace notes, turns and fermatas left out; in bar 18 the second B is printed with an open head under a quaver beam and is read as a quaver, as in bar 22',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:6\nT:An Irish Lullaby (Seo hu leo)\nM:2/4\nL:1/8\nK:Eb\nD | DE F G/A/ | BG AF | GA F2 | GA F2 | DE F G/A/ | BG AF | DF E2 | DF E2 |\nDE F G/A/ | B A/G/ AF | G B/A/ F2 | G B/A/ F3/2E/ | DE F G/A/ | B A/G/ AF | DF E2 | DF G2 |\nDE F G/A/ | BB AF | GA F2 | GA F2 | DE F G/A/ | BB AF | DF E2 | DF E |]',
    source: { ...SOURCE, where: 'p. 73 (PDF page 101)' },
    transcription: READ(101),
  },
  {
    id: 'petrie-p19-melancholy-martin',
    title: 'Melancholy Martin',
    region: 'irish',
    kind: 'slip-jig',
    key: 'A', mode: 'major', meter: '9/8',
    origin: 'Irish song and dance tune in nine-eight time, Irish title Martan Dubhach (printed in Gaelic type); set by Petrie in 1837 from the singing of a peasant in the parish of Banagher, Co. Londonderry. Marked Allegro. The three small grace notes before the first bar left out',
    tags: ['dance', 'jig', 'slip-jig', 'irish'],
    abc: 'X:7\nT:Melancholy Martin\nM:9/8\nL:1/8\nK:A\nA2A BcA GFE | A2A B2B e2z | A2A BcA GFE | F2F G2E A2z ||\nAGF EDC DE F/G/ | A2E G2A B2z | A2A BcA GFE | F2F G2E A2z |]',
    source: { ...SOURCE, where: 'p. 19 (PDF page 47)' },
    transcription: READ(47),
  },
  {
    id: 'petrie-p7-the-silken-article',
    title: 'The Silken Article',
    region: 'irish',
    kind: 'slip-jig',
    key: 'Bb', mode: 'major', meter: '9/8',
    origin: 'Irish air, Irish title An Ball Siodamhail (printed in Gaelic type); a set of it was published as a jig in 1806 by Francis Holden, and this version was set by Petrie in 1837 at Rathcarrick House, Co. Sligo, from the singing of Biddy Monaghan. Marked Allegro. A circular tune: each strain ends on a rising run C D E that leads back to the F of its first bar, so the key is given as B flat from the signature and the strains rather than from the last note. A small grace note in bars 5 and 7 left out',
    tags: ['dance', 'jig', 'slip-jig', 'irish'],
    abc: 'X:8\nT:The Silken Article\nM:9/8\nL:1/8\nK:Bb\n|: f2f fgf fdB | f2f f2e cde | f2f fgf fdB | e2e ecA cde :|\n|: d2B c2B d2B | f2f f2e cde | d2B c2B d2B | e2e ecA cde :|',
    source: { ...SOURCE, where: 'p. 7 (PDF page 35)' },
    transcription: READ(35),
  },
  {
    id: 'petrie-p114-the-pipe-on-the-hob',
    title: 'The Pipe on the Hob',
    region: 'irish',
    kind: 'jig',
    key: 'D', mode: 'major', meter: '6/8',
    origin: 'Irish double jig, one of the most popular of the old Munster jigs; its Irish name was forgotten, and the name given is the one by which it was known in Co. Limerick. Petrie had the setting from Mr. Patrick Joyce. Marked Allegro. The C naturals in bars 2 and 6 are as printed; the second strain opens on a quaver rest',
    tags: ['dance', 'jig', 'irish'],
    abc: 'X:9\nT:The Pipe on the Hob\nM:6/8\nL:1/16\nK:D\nDE | F6 A2G2F2 | =c4 A2 A2G2F2 | G2G2G2 GAB2G2 | A4 d2 c2A2G2 |\nF6 A2G2F2 | =c4 AA A2G2F2 | G2G2G2 GAB2G2 | A2F2D2 D4 :|\n|: z2 | d4 e2 f2e2d2 | c2A2F2 G6 | G2g2g2 g2f2g2 | a2f2d2 d6 |\nf/g/a a2g2 f2e2d2 | c2A2A2 A2G2F2 | G2G2G2 GAB2G2 | A2F2D2 D4 :|',
    source: { ...SOURCE, where: 'p. 114 (PDF page 142)' },
    transcription: READ(142),
  },
  {
    id: 'petrie-p185-kitty-magee',
    title: 'Kitty Magee',
    region: 'irish',
    kind: 'jig',
    key: 'Bb', mode: 'major', meter: '6/8',
    origin: 'Dance tune from a manuscript book of dance music popular in Ireland about the middle of the eighteenth century; Petrie calls it Anglo-Irish and probably not much older than the manuscript. Marked Allegretto',
    tags: ['dance', 'jig', 'irish'],
    abc: 'X:10\nT:Kitty Magee\nM:6/8\nL:1/8\nK:Bb\nB | B2F FDF | B3 c3/2d/e | d2B c2B | A2F F2 G/A/ | B2F FDF |\nB3 cde | d2B c2A | B/B3/2 B B2 :|\n|: F | B2d f2d | c2d e3 | d2B c2B | A2F F3 | f/f3/2f e2d |\nc2d e2z | d2B c2A | B/B3/2 B B2 :|',
    source: { ...SOURCE, where: 'p. 185 (PDF page 213)' },
    transcription: READ(213),
  },
  {
    id: 'petrie-p65-tatter-the-road',
    title: 'Tatter the Road',
    region: 'irish',
    kind: 'single-jig',
    key: 'G', mode: 'major', meter: '6/8',
    origin: 'Irish single jig from an old manuscript volume of dance music (about 1750); Petrie gives it as his example of the Munster "single jig", whose bars run in crotchet and quaver rather than in triplets, after a note from Mr. Patrick Joyce on the dance. Marked Allegro. One trill in bar 5 left out; the arc joining the two Gs of the last bar is read as a tie',
    tags: ['dance', 'jig', 'irish'],
    abc: 'X:11\nT:Tatter the Road\nM:6/8\nL:1/8\nK:G\nd | cAG F2D | G2G G3 | ABA A2G | F2G A2d | cAG FED |\nG2G G3 | ABA B2G | AFD D2 :|\n|: d/e/ | f2d d2e | f2d cBA | B2G ABc | B2G AFD |\nf2d efg | f2d cBA | B2G cAF | G3- G2 :|',
    source: { ...SOURCE, where: 'p. 65 (PDF page 93)' },
    transcription: READ(93),
  },
  {
    id: 'petrie-p44-my-lover-has-gone-my-heart-is-sore',
    title: 'My Lover has gone, my heart is sore',
    region: 'irish',
    kind: 'air',
    key: 'Eb', mode: 'major', meter: '3/4',
    origin: 'Irish air, Irish title D\'imthigh mo ghradh, ta mo chroidhe tinn (printed in Gaelic type); one of the airs Petrie had from Co. Mayo through Mr. P. J. O\'Reilly of Westport. Marked Andante. Two small grace notes left out; the B natural in bar 11 is as printed',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:12\nT:My Lover has gone, my heart is sore\nM:3/4\nL:1/8\nK:Eb\nEF | G2 GAFG | E2 E2 GA | B2 c2 BG | F4 Bc/d/ |\ne3 fge | fe c3/2B/ GB | AG E2 E3/2F/ | E4 :|\n|: EF | GEBG FG | E2 E2 EF | GBcd c=B | c3 ded |\nc3/2B/ GB eG | F2 E2 GB | AG E2 E3/2F/ | E4 :|',
    source: { ...SOURCE, where: 'p. 44 (PDF page 72)' },
    transcription: READ(72),
  },
  {
    id: 'petrie-p159-this-time-twelve-months-i-married',
    title: 'This time twelve months I married',
    region: 'irish',
    kind: 'song-air',
    key: 'Eb', mode: 'major', meter: '6/8',
    origin: 'Irish song air, Irish title Bliadhain \'sa taca so \'pos me (printed in Gaelic type); set from the singing of the Clare peasant Teige Mac Mahon, its notation confirmed by a second setting from the singing of Mr. Curry. Petrie thinks it a very old Munster air and the parent of several others. Marked Andante. The curves printed over the dotted crotchets are ties where the next note repeats the pitch (bars 4, 8, 12 and 16, kept as ties) and slurs where it moves; the slurs and three small grace notes are left out',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:13\nT:This time twelve months I married\nM:6/8\nL:1/16\nK:Eb\nB3/2A/2 | G3F G2 E2F2G2 | A6 G4 F2 | G2A2B2 A4 G2 | F6- F4 B3/2A/2 |\nG3F G2 E2F2G2 | A6 G4 F2 | G2B2G2 F4 E2 | E6- E4 || E3/2F/2 |\nG2A2B2 B2c2d2 | e6 d4 c2 | f4 d2 c4 B2 | B6- B4 A2 |\nG2F2G2 E2F2G2 | A6 G4 F2 | G2B2G2 F4 E2 | E6- E4 |]',
    source: { ...SOURCE, where: 'p. 159 (PDF page 187)' },
    transcription: READ(187),
  },
  {
    id: 'petrie-p184-the-lament-of-richard-cantillon',
    title: 'The Lament of Richard Cantillon',
    region: 'irish',
    kind: 'lament',
    key: 'F', mode: 'major', meter: '3/4',
    origin: 'Irish song air of four phrases, noted by Petrie from the singing of Mary Madden, a blind Limerick ballad-singer; Mr. Curry supplied the Irish song, written about 1750 by Richard Mor Cantillon of Co. Kerry. Petrie believed the air very ancient and not the one the song was first written to. Marked Andante; sung twice to each stanza, so printed with a repeat. The fermata on the last note is left out',
    tags: ['air', 'slow', 'lament', 'irish'],
    abc: 'X:14\nT:The Lament of Richard Cantillon\nM:3/4\nL:1/8\nK:F\nc3/2B/ | A2 G2 FG | A4 c d/e/ | f g/f/ edcA | G4 Ac |\nd2 df d c/A/ | A2 G2 A c3/4A/4 | G2 F2 F2 | F4 :|',
    source: { ...SOURCE, where: 'p. 184 (PDF page 212)' },
    transcription: READ(212),
  },
  {
    id: 'petrie-p181-the-hour-i-prove-false',
    title: 'The hour I prove false',
    region: 'irish',
    kind: 'song-air',
    key: 'Bb', mode: 'minor', meter: '3/4',
    origin: 'Air noted by Petrie in his boyhood from the singing of the Dublin street ballad-singers; of the Anglo-Irish ballad sung to it he kept only the words of the name. Marked Andante. The signature is five flats and the air ends on B flat, so it is entered as B flat minor (no G is sounded, so the fifth flat changes no note). In bar 3 the dot of the dotted crotchet C is printed in the space above the note; the bar needs it, so the C is read as a dotted crotchet',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:15\nT:The hour I prove false\nM:3/4\nL:1/8\nK:Bbm\nF2 | F2 F2 F2 | d4 cB | c3 dcA | F2 A2 E2 | F2 F2 F2 |\nd4 cB | c4 BA | F4 de | f2 d2 f2 | e2 d2 c2 | B3 cBA |\nF2 A2 E2 | F2 d2 cB | Ac e2 fe | c2 B2 B2 | B4 |]',
    source: { ...SOURCE, where: 'p. 181 (PDF page 209)' },
    transcription: READ(209),
  },
  {
    id: 'petrie-p48-hes-gone-hes-gone',
    title: "He's gone, he's gone",
    region: 'irish',
    kind: 'song-air',
    key: 'F', mode: 'mixolydian', meter: '2/4',
    origin: 'Irish air, Irish title D\'imthigh se \'gus d\'imthigh se (printed in Gaelic type); taken down at Dungiven, Co. Londonderry, in 1837, and named from the lines of a local English peasant ballad sung to it, "He\'s gone, he\'s gone, young Jamie\'s gone". Marked Andante. The signature is two flats and the air ends on F over a B flat chord, so it is entered as F mixolydian. Grace notes and fermatas left out; the air is printed once, without a repeat, and its last note is a dotted crotchet',
    tags: ['air', 'slow', 'irish'],
    abc: 'X:16\nT:He\'s gone, he\'s gone\nM:2/4\nL:1/8\nK:Fmix\nF | B3/2A/ Bc | de c B/A/ | B3/2A/ FF | F3 d/e/ | f3/2e/ df |\ne3/2d/ cF | B c/d/ e/c/B/A/ | B3 d/e/ | f3/2e/ d g3/4f/4 | e3/2d/ c B/A/ | B c/d/ e/d/c/B/ |\nA/F3/2 zA | B3/2A/ Bc | dB e c3/4B/4 | B3/2A/ FF | F3 |]',
    source: { ...SOURCE, where: 'p. 48 (PDF page 76)' },
    transcription: READ(76),
  },
  {
    id: 'petrie-p58-lough-allen',
    title: 'Lough Allen',
    region: 'irish',
    kind: 'reel',
    key: 'A', mode: 'major', meter: '2/4',
    origin: 'Irish reel, Irish title Loch Aillinne (printed in Gaelic type); a very popular dance-tune in Co. Leitrim, probably named from the lake, obtained with other dance-tunes from an itinerant fiddler of that county. Marked Allegro',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:17\nT:Lough Allen\nM:2/4\nL:1/16\nK:A\ncd | eAcA BGE3/2d/2 | eAcA d2cd | eAcA BGEG | AcBG A2c3/2d/2 |\neAcA BGEd | eAcA d2cB | AcBd cefa | gedB A2 ||\nBA | Beef gedB | agab a2ba | gaba gedB | AcBG A2BA |\nBeef gedB | agab a2ba | gaba gedB | AcBG A2 |]',
    source: { ...SOURCE, where: 'p. 58 (PDF page 86)' },
    transcription: READ(86),
  },
  {
    id: 'petrie-p188-the-scolding-wife',
    title: 'The Scolding Wife',
    region: 'irish',
    kind: 'reel',
    key: 'G', mode: 'major', meter: '2/4',
    origin: 'Irish reel taken from one of the O\'Neill manuscripts of Irish music of the year 1787; Petrie thinks it most probably of Munster origin. Marked Allegro. Each strain is printed out twice, as here; the C sharp in bars 9 and 13 is as printed',
    tags: ['dance', 'reel', 'irish'],
    abc: 'X:18\nT:The Scolding Wife\nM:2/4\nL:1/16\nK:G\nD2DE FEFD | GFGA BGAF | D2DE FEFG | AdcA G2G2 |\nD2DE FEFD | GFGA BGAF | D2DE FEFG | AdcA G2G2 ||\ngd^cd fgaf | gfga bgag | fdcd fgag | fdcA G2G2 |\ngd^cd fgaf | gfga bgag | fdcd fgag | fdcA G2G2 |]',
    source: { ...SOURCE, where: 'p. 188 (PDF page 216)' },
    transcription: READ(216),
  },
  {
    id: 'petrie-p92-the-hunt',
    title: 'The Hunt (or the Galtee Hunt)',
    region: 'irish',
    kind: 'set-dance',
    key: 'G', mode: 'major', meter: 'C',
    origin: 'Irish set dance, once very popular in Munster, from Mr. Patrick Joyce; Petrie gives it as an example of the class called "set dances", of hornpipe character, whose second part runs to twelve bars instead of eight. Marked Allegro. The F natural in the tenth bar is as printed',
    tags: ['dance', 'hornpipe', 'irish'],
    abc: 'X:19\nT:The Hunt (or the Galtee Hunt)\nM:C\nL:1/8\nK:G\nD2 | G3/2A/ BG AGED | c3 A dBAB | G3/2A/ BG AGED | A2 A3/2B/ A2 GE |\nG3/2A/ BG AGED | c3 A dBAB | G3/2A/ BG AGED | G2 GG G2 || D2 |\nGABc d3 e | =f2 ed e2 d2 | g3 e d2 dB | GABG A3 B | c2 ed B2 dB | A2 A3/2B/ A2 G2 |\ng3 a gedB | A2 AB A2 GE | G3/2A/ BG AGED | c3 A dBAB | G3/2A/ BG AGED | G2 GG G2 |]',
    source: { ...SOURCE, where: 'p. 92 (PDF page 120)' },
    transcription: READ(120),
  },
  {
    id: 'petrie-p106-the-old-woman-lamenting-her-purse',
    title: 'The Old Woman lamenting her Purse',
    region: 'irish',
    kind: 'jig',
    key: 'A', mode: 'phrygian', meter: '6/8',
    origin: 'Munster dance-tune obtained from Mr. James Fogarty; Petrie did not think it of much antiquity, but strongly marked with Irish character and, like many airs of its class, without the fourth of the scale. Marked Allegro. The signature is one flat and the tune ends on A, so it is entered as A phrygian; no B is sounded, which fits Petrie\'s remark that the tune lacks the fourth of F. The second part runs to sixteen bars without a repeat, its last four bars the close of the first part, as printed',
    tags: ['dance', 'jig', 'irish'],
    abc: 'X:20\nT:The Old Woman lamenting her Purse\nM:6/8\nL:1/8\nK:Aphr\nA |: AGG GFG | AFF F2 A | AGG GAc | ded dcA | AGG GFG |\nAFF F2 C | DFF F2 A | c2 d dcA :|\ncde f3 | ege f3 | cde f3 | e/f/ge f2 g | aaa ggg | fdd dcA |\nAGG GAc | d3/2e/ d dcA | AGG GFG | AFF F2 A | AGG GAc | ded dcA |\nAGG GFG | AFF F2 C | DFF F2 A | c2 d dcA |]',
    source: { ...SOURCE, where: 'p. 106 (PDF page 134)' },
    transcription: READ(134),
  },
];

export default TUNES;
