// settle-hear · tunes/skye1887 - melodies written out by hand from one public-domain printed source.
// The source, its scan and its licence are named in SOURCE below and in wikis/WIKI_OLD_MELODIES/. Each tune
// names its place in the book. The notes were read from the scan; nothing here is copied from a modern
// transcription. Fill this file by the reader brief: SETTLE/runs/melodies200/READER_BRIEF.md.
// Book: wikis/WIKI_OLD_MELODIES/books/BOOK_SKYE1887.md. The melody is the top (violin) staff of the 1887
// Paterson print, read from single page images of Internet Archive skyecollectionb00macdgoog (scan page n).

export const SOURCE = {
  kind: 'print',
  book: 'The Skye Collection of the Best Reels and Strathspeys Extant',
  compiler: 'Keith Norman MacDonald',
  year: 1887,
  scan: 'https://archive.org/details/skyecollectionb00macdgoog',
};

const TR = (n) => `read from the scan (page image n${n}, each staff in halves at full scan resolution, note heads located against measured staff lines) and proofed bar by bar by lane MELODIES200 reader skye1887, 2026-10-02`;
const TR191 = TR(191);

export const TUNES = [
  {
    id: "skye-p171-maccrimmons-lament",
    title: "MacCrimmon's Lament",
    region: "scottish",
    kind: "lament",
    key: "A",
    mode: "dorian",
    meter: "C",
    origin: "Highland lament, printed as MacCrimmon's Lament, Cha till mi tuille, \"Never more shall I return\"; marked Very Slow and Skye set; the book's footnote: as played by the late Miss Jessie Macleod, Gesto",
    tags: ["highlands", "air", "slow", "lament", "scottish"],
    abc: "X:1\nT:MacCrimmon's Lament\nM:C\nL:1/8\nK:Ador\nA>A e2 d2 e2 | A2 f2 e>d eA |1 B>B e2 d2 e2 | G2 (3GBd dB dA :|2 G2 (3GBd e2 dB | G>G B2 e2 d>A ||\n|: g>fe A g>fe A | g>fe A e>dB A |1 g>ed G g>ed G | g>ed G d>B A2 :|2 G2 (3GBd e2 dB | G2 (3GBd e2 d>A |]",
    source: { ...SOURCE, where: "Book VI, p. 171 (scan page n189)" },
    transcription: "read from the scan (page image n189, each staff in halves at full scan resolution, note heads located against measured staff lines) and proofed bar by bar by lane MELODIES200 reader skye1887, 2026-10-02",
  },
  {
    id: "skye-p173-a-skye-air",
    title: "A Skye Air",
    region: "scottish",
    kind: "air",
    key: "E",
    mode: "minor",
    meter: "C",
    origin: "Highland air, printed as Hithil uil agus o, A Skye Air; marked Very Old; in the Solos of Book VI",
    tags: ["highlands", "air", "slow", "scottish"],
    irregular: "bar 3 as printed: the Scotch snap d/d has no dot on its second note (bars 1 and 5 have it), so the bar is a sixteenth short",
    abc: "X:1\nT:A Skye Air\nM:C\nL:1/8\nK:Em\n|: d/d3/ B>A Bd e2 | g>d e2 B>A G2 | d/d B>A B>d e2 | G2 B/A/G/F/ BE E2 |\nd/d3/ B>A B>d e2 | g>d e2 B>A G2 | A>B g2 g/f/e/^d/ e2 | G2 B/A/G/F/ BE E2 :|\n|: e2 e^d e2 e^d | e>f g2 B>A G2 | d2 dB d2 e2 | G2 B/A/G/F/ BE E2 |\nd2 d>B d2 d>B | d2 e2 B>A G2 | AB g2 g/f/e/^d/ e2 | G2 B/A/G/F/ BE E2 :|",
    source: { ...SOURCE, where: "Book VI, p. 173 (scan page n191)" },
    transcription: TR191,
  },
  {
    id: "skye-p173-loch-erroch-side",
    title: "Loch Erroch Side",
    region: "scottish",
    kind: "strathspey",
    key: "C",
    mode: "major",
    meter: "C",
    origin: "Strathspey, printed as Loch Erroch Side (Neil Gow and his 2nd Wife); marked Slow with much Expression; in the Solos of Book VI; the first strain is printed twice in full",
    tags: ["highlands", "strathspey", "dance", "air", "slow", "scottish"],
    abc: "X:1\nT:Loch Erroch Side\nM:C\nL:1/8\nK:C\nG/F/ | EG G>A c/B/c/d/ c2 | A>G Ac d/c/d/e/ dD | EG G>A c>d e>d | c>A G/A/c/E/ D2 CG/F/ |\nEG G>A c/B/c/d/ c2 | A>G Ac d/c/d/e/ dD | EG G>A c>d e>d | c>A G/A/c/E/ D2 C ||\ng/f/ | eg ce/f/ g/f/e/f/ g2 | fa df/g/ a/g/f/g/ ag/f/ | eg ce/f/ g/f/e/f/ g>c | G>c e>c d2 cg/f/ |\neg ce/f/ g/f/e/f/ gf/e/ | fa df/g/ a/g/f/g/ ag/f/ | e>g d>e c>G ca | cG c>E D2 C |]",
    source: { ...SOURCE, where: "Book VI, p. 173 (scan page n191)" },
    transcription: TR191,
  },
  {
    id: "skye-p179-the-shieling-in-the-braes-of-rannoch",
    title: "The Shieling in the Braes of Rannoch",
    region: "scottish",
    kind: "air",
    key: "G",
    mode: "minor",
    meter: "3/4",
    origin: "Highland air, Gaelic title Bothan airidh 'm braighe Raineach; marked Slow and pathetic; in the Solos of Book VI; the book notes it is from Captain Fraser's Collection",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:The Shieling in the Braes of Rannoch\nM:3/4\nL:1/8\nK:Gm\nG>A | d2 f2 =e>c | d2 c z G>A | d2 f2 =e>d | c2 F z c>A |\nc2 d2 c>d | F2 G z d>c | A2 F2 G2 | A2 G z ||\nd>^f | g2 b2 a>g | f2 d z d>^f | g2 b2 a>g | g2 d z f>=e |\nd2 c z A>G | F2 A z d>c | A2 F2 G2 | A2 G z |]",
    source: { ...SOURCE, where: "Book VI, p. 179 (scan page n197)" },
    transcription: TR(197),
  },
  {
    id: "skye-p179-good-wife-admit-the-wanderer",
    title: "Good Wife, Admit the Wanderer",
    region: "scottish",
    kind: "air",
    key: "Bb",
    mode: "major",
    meter: "2/4",
    origin: "Highland air, Gaelic title A bhean an taigh nach leig thu steach am fear a tha air fogairt; marked Slow, with expression of hesitation; in the Solos of Book VI; the book's footnote says it refers to Prince Charles wandering from the place of his defeat to the Isle of Skye, and that it is from Captain Fraser's Collection; melody is the top note of the printed double stops",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:Good Wife, Admit the Wanderer\nM:2/4\nL:1/16\nK:Bb\n(3FGA | B2d2 B2 z d/c/ | B2d2 B2 z d/e/ | f2d2 B2F2 | G6 (3FGA |\nB2d2 B2 z d/c/ | BBdd B2 de | f2f2 f2f2 | B6 :|\n(3Bcd | e3f g3e | f3e d3f | e3d f3F | G6 (3FGA |\nB2d2 B2 z d/c/ | BBdd B2 de | f2f2 f2f2 | B6 (3Bcd |\ne3f g3e | b3g f2d2 | f2d2 B2F2 | G6 (3FGA | B3F GFED | dcde fgab | f3d c4 | B6 |]",
    source: { ...SOURCE, where: "Book VI, p. 179 (scan page n197)" },
    transcription: TR(197),
  },
  {
    id: "skye-p163-lamentation-for-macgregor-of-roro",
    title: "Lamentation for MacGregor of Roro",
    region: "scottish",
    kind: "lament",
    key: "A",
    mode: "major",
    meter: "3/4",
    origin: "Highland lament, printed as Mac Griogair a Ruaro, Lamentation for Mac Gregor of Roro; in the Solos of Book VI",
    tags: ["highlands", "air", "slow", "lament", "scottish"],
    abc: "X:1\nT:Lamentation for MacGregor of Roro\nM:3/4\nL:1/8\nK:A\nE>F | A2 A2 BA/B/ | c2 E z E>F | A2 A2 BA/B/ | c2 E2 A,/C/E |\nc2 c2 e>c | B2 A2 F2 | E2 C>B, CE | F2 A, z E>F |\nA2 A2 BA/B/ | c2 E2 E>F | A2 A2 BA/B/ | c2 E2 A,/C/E/A/ |\nc2 c2 e>c | B2 A2 A>F | E2 C2 E>C | B,2 A,2 |]",
    source: { ...SOURCE, where: "Book VI, p. 163 (scan page n181)" },
    transcription: TR(181),
  },
  {
    id: "skye-p175-blue-bonnets-over-the-border",
    title: "Blue Bonnets over the Border",
    region: "scottish",
    kind: "air",
    key: "Bb",
    mode: "major",
    meter: "6/8",
    origin: "Scottish air, printed among the Solos of Book VI in a slow setting marked Slow with Expression; the second strain is printed twice in full",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:Blue Bonnets over the Border\nM:6/8\nL:1/8\nK:Bb\nB,3 B,C/D/ | B3/2c/d B2F | BGG G2f | g3/2f/d c2B | B,2B, B,3/2C/D | B3/2c/d cBF | G3 FDF | FBD C2B, :|\nBdf fdB | g3/2f/d c2B | Bdf g3/2a/b | B3/2c/d/e/ c2B | Bdf fdB | g3/2f/d cBc | G3 FDF | FBD C2B, |\nBdf fdB | g3/2f/d c2B | Bdf g3/2a/b | B3/2c/d/e/ c2B | Bdf fdB | g3/2f/d cBc | G3 FDF | FBD C2B, |]",
    source: { ...SOURCE, where: "Book VI, p. 175 (scan page n193)" },
    transcription: TR(193),
  },
  {
    id: "skye-p170-the-irish-girl",
    title: "The Irish Girl",
    region: "scottish",
    kind: "air",
    key: "E",
    mode: "minor",
    meter: "6/8",
    origin: "Air printed as The Irish Girl, marked Slow, Very old, Skye set; in the Solos of Book VI",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:The Irish Girl\nM:6/8\nL:1/8\nK:Em\nD | D3/2B,/D D3/2B,/D | D3/2B,/D D2G | E3/2G/E E3/2D/E | G3/2A/B B2A |\nA3/2B/d e3/2g/e | dBA G3/2A/B | B3/2e/d B3/2A/B | GED E2 :|\n|: d | d3/2e/d dBd | d3/2e/d d2g | ege edB | BAB G2G |\nABg edB | cec B2A | ABd ege | GED E2 :|",
    source: { ...SOURCE, where: "Book VI, p. 170 (scan page n188)" },
    transcription: TR(188),
  },
  {
    id: "skye-p8-mrs-macleod-raasay",
    title: "Mrs MacLeod Raasay",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C",
    origin: "Reel, printed as Mrs MacLeod Raasay, by Sir Alexander MacDonald, Skye set; Book I; the two strains are printed once each, without repeat signs",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Mrs MacLeod Raasay\nM:C\nL:1/8\nK:A\nc | A2a2 f3/2e/fa | c/c3/2c3/2B/ c2cB | A2a2 f3/2e/fa | B/B3/2B3/2A/ B2Bc |\nA2a2 f3/2e/fa | c/c3/2c3/2B/ c2c/e3/2 | fafe f2ef | afec B2B3/2c/ ||\nA/A3/2cA eccf | c/c3/2c3/2B/ c2ca | A/A3/2c3/2A/ eccf | B/B3/2B3/2A/ B2Bc |\nA/A3/2c3/2A/ eccf | c/c3/2c3/2B/ c2ce | fafe f2ef | afec B2B |]",
    source: { ...SOURCE, where: "Book I, p. 8 (scan page n22)" },
    transcription: TR(22),
  },
  {
    id: "skye-p167-lady-isabella-wemyss-strathspey",
    title: "Lady Isabella Wemyss' Strathspey",
    region: "scottish",
    kind: "strathspey",
    key: "D",
    mode: "major",
    meter: "C",
    origin: "Strathspey by William Marshall, printed as Lady Isabella Wemyss' Strathspey, marked Slow when not Danced; in the Solos of Book VI; melody is the top note of the printed double stops, grace notes left out",
    tags: ["highlands", "strathspey", "dance", "air", "slow", "scottish"],
    abc: "X:1\nT:Lady Isabella Wemyss' Strathspey\nM:C\nL:1/8\nK:D\nD2 E3/2F/ GB B,2 | A,DDF E2 DA, | DDEF AB B,2 | d3/2B/AF E2D2 :|\nA3/2d/ f3/2d/ g/f/e/d/ B2 | Addf e2 d3/2A/ | B3/2d/ B/A/G/F/ G/F/E/D/ B,2 | A,3/2D/ DF E2 D2 |\nA3/2d/ f3/2d/ g/f/e/d/ B2 | Addf e2 d3/2A/ | B/d/c/d/ B/A/G/F/ G/F/E/D/ B,2 | d3/2B/ A/F3/2 E2 D2 |]",
    source: { ...SOURCE, where: "Book VI, p. 167 (scan page n185)" },
    transcription: TR(185),
  },
  {
    id: "skye-p164-mr-marshalls-compliments-to-niel-gow",
    title: "Mr Marshall's Compliments to Niel Gow",
    region: "scottish",
    kind: "air",
    key: "A",
    mode: "major",
    meter: "C",
    origin: "Slow air by William Marshall, printed as Mr Marshall's Compliment's to Niel Gow, marked Slowly; in the Solos of Book VI; melody is the top note of the printed double stops, grace notes and the fermata in bar 11 left out",
    tags: ["highlands", "air", "slow", "scottish"],
    abc: "X:1\nT:Mr Marshall's Compliments to Niel Gow\nM:C\nL:1/8\nK:A\nE | Ac AE Ac A2 | A/B/c/B/ AE F/B3/2-B2 | cB AE Af e3/2E/ | c/d/e/f/ e/d/c/B/ cA-A :|\nf/g/ | acec ac e2 | a/g/f/e/ d/c/B/A/ G/A/B/c/ B f/g/ | f/e/d/c/ B/c/d/e/ cAA f/g/ | acec ac e2 |\na/g/f/e/ d/c/B/A/ G/A/B/c/ Bc | A3/2c/AE Fc d3/2f/ | f/e/d/c/ B/c/d/e/ c A/-A/ |]",
    source: { ...SOURCE, where: "Book VI, p. 164 (scan page n182)" },
    transcription: TR(182),
  },
  {
    id: "skye-p182-sailors-hornpipe",
    title: "Sailor's Hornpipe",
    region: "english",
    kind: "hornpipe",
    key: "D",
    mode: "major",
    meter: "C",
    origin: "Hornpipe, printed as Sailor's Hornpipe among the Hornpipes of Book VI; melody is the top note of the printed chords, grace notes left out",
    tags: ["dance", "hornpipe", "english"],
    abc: "X:1\nT:Sailor's Hornpipe\nM:C\nL:1/8\nK:D\n|: fe | dcdA FAdf | edcB A2g2 | fdad bdad | edcB Agfe |\ndcdA FAdf | edcB A2g2 | fafd egec | d2f2d2 :|\n|: fg | afaf d2ga | bgbg e2fg | afaf bgaf | edcB A2fe |\ndcdA FAdf | edcB A2g2 | fafd egec | d2f2d2 :|",
    source: { ...SOURCE, where: "Book VI, p. 182 (scan page n200)" },
    transcription: TR(200),
  },
  {
    id: "skye-p8-miss-mackay",
    title: "Miss Mackay",
    region: "scottish",
    kind: "reel",
    key: "A",
    mode: "major",
    meter: "C",
    origin: "Reel, printed as Miss Mackay, Book I; the second strain is printed without repeat signs",
    tags: ["highlands", "reel", "dance", "scottish"],
    abc: "X:1\nT:Miss Mackay\nM:C\nL:1/8\nK:A\na | A/A/A cA eAcA | Bffe fBBa | A/A/A cA eAcA | EFAB cAA :|\na | faea dac2 | Bffe fBBa | faea dacA | EFAB cAAa |\nfaea daca | dffe fBBg | afbg afed | EFAB cAA |]",
    source: { ...SOURCE, where: "Book I, p. 8 (scan page n22)" },
    transcription: TR(22),
  },
];

export default TUNES;
